
/*********************************************************************
	SYSTEM Berliner
	IMPLEMENTATION Arduino
	Error Function Template Module for CIP MACHINE mBerlinerUnit
	Filename: _errBerlinerUnit.tpl
	generated by CIP Tool(R) Version 4.41.00
		August 17, 2012  4:31:43 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/*********************************************************************
	End of Error Function Template Module for CIP MACHINE mBerlinerUnit
*********************************************************************/
