
/*********************************************************************
	SYSTEM Berliner
	Module for PROCESS Drive
	Filename: Drive.c
	generated by CIP Tool(R) Version 4.41.00
		August 17, 2012  4:31:43 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mBerlinerUnit.h"

/* Process Macro Definitions */

#define SELF status_Drive.write_access_
#define STATUS status_Drive.read_access_
#define TIME time_mBerlinerUnit

/* Process Definitions */

/* MODES */
#define normal 1

/* STATES */
#define SimpleDrive 1


/* INPULSES */
#define IP_ForwardLeft 1
#define IP_ForwardRight 2
#define IP_Forward 3
#define IP_Backward 4
#define IP_BackwardLeft 5
#define IP_BackwardRight 6
#define IP_Stop 7


/* OUTPULSES */

#define O3_BWD 10
#define O3_FWD 8
#define O3_GoLeft 11
#define O3_GoRight 12
#define O3_STOP 9
#define O4_Backward 4
#define O4_BackwardLeft 5
#define O4_BackwardRight 6
#define O4_Forward 3
#define O4_ForwardLeft 1
#define O4_ForwardRight 2
#define O4_Stop 7

/* External Declarations */

extern unsigned long time_mBerlinerUnit;
extern union tCHNOUT_mBerlinerUnit CHNOUT_mBerlinerUnit;

void fUPDATE_Locomotion (void);
int fPULSE_Motor (unsigned char name_);
int fPULSE_Steering (unsigned char name_);

/* Global Declarations */

union tSTATUS_Drive status_Drive;

/* Function Prototypes */

int fPULSE_Drive (unsigned char name_);
void fINIT_Drive (void);

/* Input Channel Functions */

int fPULSE_Drive (unsigned char name_)
{
	switch (name_)
	{
		/***  INPULSE Backward  ***/
	case O3_BWD:		/***  PULSE CAST from PROCESS Calibration  ***/
		switch (status_Drive.read_access_.STATE)
		{
		case 1:  /* STATE SimpleDrive */
			status_Drive.write_access_.STATE = 1;  /* STATE SimpleDrive */
			fPULSE_Motor (O4_Backward);
			fPULSE_Steering (O4_Backward);
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE BackwardLeft  ---  untranslated  ***/

		/***  INPULSE BackwardRight  ---  untranslated  ***/

		/***  INPULSE Forward  ***/
	case O3_FWD:		/***  PULSE CAST from PROCESS Calibration  ***/
		switch (status_Drive.read_access_.STATE)
		{
		case 1:  /* STATE SimpleDrive */
			status_Drive.write_access_.STATE = 1;  /* STATE SimpleDrive */
			fPULSE_Motor (O4_Forward);
			fPULSE_Steering (O4_Forward);
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE ForwardLeft  ***/
	case O3_GoLeft:		/***  PULSE CAST from PROCESS Calibration  ***/
		switch (status_Drive.read_access_.STATE)
		{
		case 1:  /* STATE SimpleDrive */
			status_Drive.write_access_.STATE = 1;  /* STATE SimpleDrive */
			fPULSE_Motor (O4_ForwardLeft);
			fPULSE_Steering (O4_ForwardLeft);
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE ForwardRight  ***/
	case O3_GoRight:		/***  PULSE CAST from PROCESS Calibration  ***/
		switch (status_Drive.read_access_.STATE)
		{
		case 1:  /* STATE SimpleDrive */
			status_Drive.write_access_.STATE = 1;  /* STATE SimpleDrive */
			fPULSE_Motor (O4_ForwardRight);
			fPULSE_Steering (O4_ForwardRight);
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE Stop  ***/
	case O3_STOP:		/***  PULSE CAST from PROCESS Calibration  ***/
		switch (status_Drive.read_access_.STATE)
		{
		case 1:  /* STATE SimpleDrive */
			status_Drive.write_access_.STATE = 1;  /* STATE SimpleDrive */
			fPULSE_Motor (O4_Stop);
			fPULSE_Steering (O4_Stop);
			break;
		default: 
			break;
		}
		break;
	default: 
		return 0;
	}
	return 1;
}

/* Process Initialization Function */

void fINIT_Drive (void)
{
	status_Drive.write_access_.STATE = 1;  /* STATE SimpleDrive */
}

/*********************************************************************
	End of Module for PROCESS Drive
*********************************************************************/
