
/*********************************************************************
	SYSTEM Berliner
	IMPLEMENTATION Arduino
	Error Header File for CIP MACHINE mBerlinerUnit
	Filename: eBerlinerUnit.h
	generated by CIP Tool(R) Version 4.41.00
		August 17, 2012  4:31:43 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

#ifndef _EHEADER
#define _EHEADER

/* Include Files */

#include "mBerlinerUnit.h"

#endif 

/*********************************************************************
	End of Error Header File for CIP MACHINE mBerlinerUnit
*********************************************************************/
