
/*********************************************************************
	SYSTEM Berliner
	IMPLEMENTATION Arduino
	Module for CIP MACHINE mBerlinerUnit
	Filename: mBerlinerUnit.c
	generated by CIP Tool(R) Version 4.41.00
		August 17, 2012  4:31:43 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mBerlinerUnit.h"

/* External Declarations */

void fICHAN_CalibrationChannel (unsigned char name_);
void fINIT_Calibration (void);
void fINIT_Drive (void);
void fINIT_Motor (void);
void fINIT_Steering (void);

/* Global Declarations */

unsigned long time_mBerlinerUnit = 0;
union tCHNOUT_mBerlinerUnit CHNOUT_mBerlinerUnit;
struct tTIMING_mBerlinerUnit TIMING_mBerlinerUnit;
struct tTMQE_mBerlinerUnit *tuhead_mBerlinerUnit, *tutail_mBerlinerUnit;

/* Function Prototypes */

void fSETTIM_mBerlinerUnit (unsigned long *delay_, struct tTMEL_mBerlinerUnit *timer_, struct tTMQE_mBerlinerUnit *timeup_);
void fSTOPTIM_mBerlinerUnit (struct tTMEL_mBerlinerUnit *timer_, struct tTMQE_mBerlinerUnit *timeup_);
void fSTEP_mBerlinerUnit(void);
void fCHAIN_mBerlinerUnit(void);
void fTIMEUP_mBerlinerUnit(void);
void fREAD_mBerlinerUnit(void);
void fUPDATE_Locomotion (void);

/* AUTO_ Handler Function */

static void fAUTOHDL_mBerlinerUnit(void)
{
		/* dummy function handling no AUTO_ */
}

/* Timer Functions */

static void fTICK_mBerlinerUnit(void)
{
	time_mBerlinerUnit ++;
	if (TIMING_mBerlinerUnit.set_)
		TIMING_mBerlinerUnit.tkhndl_ ();
	TRG_.PENDING_.TIMEUP_ = tuhead_mBerlinerUnit != 0;
	TRG_.PENDING_.ANY_ = TRG_.PENDING_.ANY_ || TRG_.PENDING_.TIMEUP_;
}

void fSETTIM_mBerlinerUnit (unsigned long *delay_, struct tTMEL_mBerlinerUnit *timer_, struct tTMQE_mBerlinerUnit *timeup_)
{
	if (*delay_ > 0)
	{
		if (! timer_->set_)
			++TIMING_mBerlinerUnit.set_;
		timer_->set_ = TRUE;
		timer_->end_ = time_mBerlinerUnit + *delay_;
		if (tuhead_mBerlinerUnit == timeup_)
			tuhead_mBerlinerUnit = tuhead_mBerlinerUnit->next_;
		if (timeup_->preced_)
			timeup_->preced_->next_ = timeup_->next_;
		if (timeup_->next_)
			timeup_->next_->preced_ = timeup_->preced_;
		if (tutail_mBerlinerUnit == timeup_)
			tutail_mBerlinerUnit = timeup_->preced_;
		timeup_->preced_ = 0;
		timeup_->next_ = 0;
	}
	else 
	{
		if (timer_->set_)
			--TIMING_mBerlinerUnit.set_;
		timer_->set_ = FALSE;
		if (tuhead_mBerlinerUnit != timeup_ && ! timeup_->preced_ && ! timeup_->next_)
		{
			if (! tuhead_mBerlinerUnit)
				tuhead_mBerlinerUnit = tutail_mBerlinerUnit = timeup_;
			else 
			{
				tutail_mBerlinerUnit->next_ = timeup_;
				timeup_->preced_ = tutail_mBerlinerUnit;
				tutail_mBerlinerUnit = timeup_;
			}
		}
	}
}

void fSTOPTIM_mBerlinerUnit (struct tTMEL_mBerlinerUnit *timer_, struct tTMQE_mBerlinerUnit *timeup_)
{
	if (timer_->set_)
		--TIMING_mBerlinerUnit.set_;
	timer_->set_ = FALSE;
	if (tuhead_mBerlinerUnit == timeup_)
		tuhead_mBerlinerUnit = tuhead_mBerlinerUnit->next_;
	if (timeup_->preced_)
		timeup_->preced_->next_ = timeup_->next_;
	if (timeup_->next_)
		timeup_->next_->preced_ = timeup_->preced_;
	if (tutail_mBerlinerUnit == timeup_)
		tutail_mBerlinerUnit = timeup_->preced_;
	timeup_->preced_ = 0;
	timeup_->next_ = 0;
}

/* Control Functions */

	/* Step Function for CIP Machine */

void fSTEP_mBerlinerUnit(void)
{
	if (tuhead_mBerlinerUnit != 0)
		TIMING_mBerlinerUnit.tuhndl_ ();
	return;
}

	/* Chain Function for CIP Machine */

void fCHAIN_mBerlinerUnit(void)
{
	return;
}

	/* Timeup Function for CIP Machine */

void fTIMEUP_mBerlinerUnit(void)
{
	if (tuhead_mBerlinerUnit != 0)
		TIMING_mBerlinerUnit.tuhndl_ ();
	return;
}

	/* Read Function for CIP Machine */

void fREAD_mBerlinerUnit(void)
{
	return;
}

/* Update Functions */

void fUPDATE_Locomotion (void)
{
	TRG_.PENDING_.TIMEUP_ = tuhead_mBerlinerUnit != 0;
	TRG_.PENDING_.ANY_ = 
		TRG_.PENDING_.TIMEUP_;
}

/* Initialization Function */

int fINIT_(void)
{
	tuhead_mBerlinerUnit = tutail_mBerlinerUnit = 0;
	TRG_.TICK_ = fTICK_mBerlinerUnit;
	TRG_.CHAIN_ = fCHAIN_mBerlinerUnit;
	TRG_.TIMEUP_ = fTIMEUP_mBerlinerUnit;
	TRG_.STEP_ = fSTEP_mBerlinerUnit;
	TRG_.READ_ = fREAD_mBerlinerUnit;
	TRG_.AUTO_ = fAUTOHDL_mBerlinerUnit;
	TRG_.PENDING_.ANY_ = 0;
	TRG_.PENDING_.CHAIN_ = 0;
	TRG_.PENDING_.TIMEUP_ = 0;
	TRG_.PENDING_.READ_ = 0;
	TRG_.PENDING_.AUTO_ = 0;
	IN_.CalibrationChannel = fICHAN_CalibrationChannel;
	iCHAN_();
	if (!OUT_.SteeringChannel)
		return 0;
	if (!OUT_.MotorChannel)
		return 0;
	fINIT_Calibration ();
	fINIT_Drive ();
	fINIT_Motor ();
	fINIT_Steering ();
	return 1;
}

/*********************************************************************
	End of Module for CIP MACHINE mBerlinerUnit
*********************************************************************/
