
/*********************************************************************
	SYSTEM FrontDoor
	Module for PROCESS Light
	Filename: Light.c
	generated by CIP Tool(R) Version 4.41.00
		November 10, 2013  9:40:45 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		'unsigned int' for delays
		C-code
*********************************************************************/

/* Include Files */

#include "mArduinoUnit.h"

/* Process Macro Definitions */

#define SELF status_Light.write_access_
#define STATUS status_Light.read_access_
#define TIME time_mArduinoUnit

/* Process Definitions */

/* MODES */
#define normal 1

/* STATES */
#define Off 1
#define On 2


/* INPULSES */
#define IP_SWITCH 1


/* OUTPULSES */

#define O3_OFF 4
#define O3_ON 3
#define O2_DOWN 1
#define O2_UP 2

/* External Declarations */

extern unsigned int time_mArduinoUnit;
extern union tCHNOUT_mArduinoUnit CHNOUT_mArduinoUnit;

void fUPDATE_Sonnerie (void);

/* Global Declarations */

union tSTATUS_Light status_Light;

/* Function Prototypes */

int fPULSE_Light (unsigned char name_);
void fINIT_Light (void);

/* Input Channel Functions */

int fPULSE_Light (unsigned char name_)
{
	switch (name_)
	{
		/***  INPULSE SWITCH  ***/
	case O2_DOWN:		/***  PULSE CAST from PROCESS LightSwitch  ***/
		switch (status_Light.read_access_.STATE)
		{
		case 1:  /* STATE Off */
			status_Light.write_access_.STATE = 2;  /* STATE On */
			CHNOUT_mArduinoUnit.CHAN_LightOutChannel.name_ = C2_ON;
			OUT_.LightOutChannel (CHNOUT_mArduinoUnit.CHAN_LightOutChannel.name_);
			break;
		case 2:  /* STATE On */
			status_Light.write_access_.STATE = 1;  /* STATE Off */
			CHNOUT_mArduinoUnit.CHAN_LightOutChannel.name_ = C2_OFF;
			OUT_.LightOutChannel (CHNOUT_mArduinoUnit.CHAN_LightOutChannel.name_);
			break;
		default: 
			break;
		}
		break;
	default: 
		return 0;
	}
	return 1;
}

/* Process Initialization Function */

void fINIT_Light (void)
{
	status_Light.write_access_.STATE = 1;  /* STATE Off */
}

/*********************************************************************
	End of Module for PROCESS Light
*********************************************************************/
