
/*********************************************************************
	SYSTEM FrontDoor
	IMPLEMENTATION ArduinoImplementation
	Module for CIP SHELL sArduinoUnit
	Filename: sArduinoUnit.c
	generated by CIP Tool(R) Version 4.41.00
		November 10, 2013  9:40:44 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		'unsigned int' for delays
		C-code
*********************************************************************/

/* Include Files */

#include "sArduinoUnit.h"

/* Input Interface */

struct tIN_ IN_;

/* Output Interface */

struct tOUT_ OUT_;

/* Trigger Interface  */

struct tTRG_ TRG_;

/*********************************************************************
	End of Module for CIP SHELL sArduinoUnit
*********************************************************************/
