
/*********************************************************************
	SYSTEM FrontDoor
	IMPLEMENTATION ArduinoImplementation
	Header File for CIP SHELL sArduinoUnit
	Filename: sArduinoUnit.h
	generated by CIP Tool(R) Version 4.41.00
		November 10, 2013  9:40:44 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		'unsigned int' for delays
		C-code
*********************************************************************/

#ifndef _SHEADER
#define _SHEADER

/* Code Option Constants */

#ifdef _EINPUT__
	#undef _EINPUT__
#endif 

/* Channel Enumerations */

#define C_BellInChannel 3
#define C_BellOutChannel 4
#define C_LightOutChannel 2
#define C_LightSwitchInChannel 1

/* MESSAGE Enumeration of CHANNEL LightSwitchInChannel */

#define C1_ 0
#define C1_DOWN 1
#define C1_UP 2

/* MESSAGE Enumeration of CHANNEL LightOutChannel */

#define C2_ 0
#define C2_OFF 1
#define C2_ON 2

/* MESSAGE Enumeration of CHANNEL BellInChannel */

#define C3_ 0
#define C3_DOWN 1

/* MESSAGE Enumeration of CHANNEL BellOutChannel */

#define C4_ 0
#define C4_OFF 1
#define C4_ON 2

/* Input Interface Type */

struct tIN_
{
	void (*BellInChannel) (unsigned char);
	void (*LightSwitchInChannel) (unsigned char);
};

/* Output Interface Type */

struct tOUT_
{
	void (*BellOutChannel) (unsigned char);
	void (*LightOutChannel) (unsigned char);
};

/* Trigger Interface Type */

struct tPENDING_
{
	int ANY_;	/* boolean indicating any pending transitions */
	int CHAIN_;	/* boolean indicating pending CHAIN_ */
	int TIMEUP_;	/* boolean indicating pending TIMEUP_ */
	int READ_;	/* boolean indicating buffered internal message */
	int AUTO_;	/* boolean indicating reading AUTO_ */
};

struct tTRG_
{
	void (*TICK_) (void);		/* increment CIP MACHINE time */
	void (*STEP_) (void);		/* trigger CIP MACHINE transition */
	void (*CHAIN_) (void);		/* trigger pending chain CIP MACHINE transition */
	void (*TIMEUP_) (void);		/* trigger pending timeup CIP MACHINE transition */
	void (*READ_) (void);		/* trigger CIP MACHINE to read from internal message buffer */
	void (*AUTO_) (void);		/* trigger pending auto CIP MACHINE transition */
	struct tPENDING_ PENDING_;		/* information on pending transitions */
};

/* External Interface Declarations */

extern struct tIN_ IN_;		/* Input Channel Interface defined in sArduinoUnit.c */
extern struct tOUT_ OUT_;		/* Output Channel Interface defined in sArduinoUnit.c */
extern struct tTRG_ TRG_;		/* Trigger Interface defined in sArduinoUnit.c */

/* Unit Initialization Function, defined in mArduinoUnit.c
	called by User to initialize CIP Machine
		returning 1 if successful
		returning 0 if failed */

int fINIT_(void);

/* User defined Initialization Function for CIP Shell Interface Initialization 
	called by Unit Initialization Function */

void iCHAN_(void);


#endif 

/*********************************************************************
	End of CIP UNIT Header File for CIP SHELL sArduinoUnit
*********************************************************************/
