
/*********************************************************************
	SYSTEM FrontDoor
	IMPLEMENTATION ArduinoImplementation
	Trace Interface Module for CIP MACHINE mArduinoUnit
	Filename: tArduinoUnit.c
	generated by CIP Tool(R) Version 4.41.00
		November 10, 2013  9:40:45 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		'unsigned int' for delays
		C-code
*********************************************************************/

/* Include Files */

#include "tArduinoUnit.h"

/*********************************************************************
	End of Trace Interface Module for CIP MACHINE mArduinoUnit
*********************************************************************/
