
/*********************************************************************
	SYSTEM Findling01
	IMPLEMENTATION Arduino
	Error Function Template Module for CIP MACHINE mTheUnit
	Filename: _errTheUnit.tpl
	generated by CIP Tool(R) Version 4.41.00
		February 12, 2015  10:58:34 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/*********************************************************************
	End of Error Function Template Module for CIP MACHINE mTheUnit
*********************************************************************/
