
/*********************************************************************
	SYSTEM Findling01
	IMPLEMENTATION Arduino
	Trace Template File for CIP MACHINE mTheUnit
	Filename: _traceTheUnit.tpl
	generated by CIP Tool(R) Version 4.41.00
		October 28, 2014  10:49:01 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/*********************************************************************
	End of Trace Template File for CIP MACHINE mTheUnit
*********************************************************************/
