
/*********************************************************************
	SYSTEM Findling01
	Module for PROCESS Ambient
	Filename: Ambient.c
	generated by CIP Tool(R) Version 4.41.00
		October 29, 2014  7:18:35 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mTheUnit.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define SELF status_Ambient.write_access_
#define STATUS status_Ambient.read_access_
#define TIME time_mTheUnit

/* Process Definitions */

/* MODES */
#define normal 1

/* STATES */
#define Off 1
#define On 2



/* External Declarations */

extern unsigned long time_mTheUnit;
extern union tCHNOUT_mTheUnit CHNOUT_mTheUnit;


/* Global Declarations */

union tSTATUS_Ambient status_Ambient;

/* Function Prototypes */

void fICHAN_AmbientSwitch (unsigned char name_);
void fINIT_Ambient (void);

/* Input Channel Functions */

void fICHAN_AmbientSwitch (unsigned char name_)
{
	switch (name_)
	{
		/***  MESSAGE TOGGLE of INPORT AmbientIn  ***/
	case C11_TOGGLE:
		switch (status_Ambient.read_access_.STATE)
		{
		case 1:  /* STATE Off */
			status_Ambient.write_access_.STATE = 2;  /* STATE On */
			CHNOUT_mTheUnit.CHAN_AmbientAction.name_ = C12_ON;
			OUT_.AmbientAction (CHNOUT_mTheUnit.CHAN_AmbientAction.name_);
			break;
		case 2:  /* STATE On */
			status_Ambient.write_access_.STATE = 1;  /* STATE Off */
			CHNOUT_mTheUnit.CHAN_AmbientAction.name_ = C12_OFF;
			OUT_.AmbientAction (CHNOUT_mTheUnit.CHAN_AmbientAction.name_);
			break;
		default: 
			return;
		}
		break;
	default: 
		return;
	}
	return;
}

#undef EXCEPTION

/* Process Initialization Function */

void fINIT_Ambient (void)
{
	status_Ambient.write_access_.STATE = 1;  /* STATE Off */
}

/*********************************************************************
	End of Module for PROCESS Ambient
*********************************************************************/
