
/*********************************************************************
	SYSTEM Findling01
	Module for PROCESS Ambient
	Filename: Ambient.c
	generated by CIP Tool(R) Version 4.41.00
		December 11, 2014  5:32:34 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mTheUnit.h"

/* Process Macro Definitions */

#define SELF status_Ambient.write_access_
#define STATUS status_Ambient.read_access_
#define TIME time_mTheUnit

/* Process Definitions */

/* MODES */
#define normal 1

/* STATES */
#define Off 1
#define On 2


/* INPULSES */
#define IP_ON 1
#define IP_OFF 2


/* OUTPULSES */

#define O1_OFF 2
#define O1_ON 1

/* External Declarations */

extern unsigned long time_mTheUnit;
extern union tCHNOUT_mTheUnit CHNOUT_mTheUnit;


/* Global Declarations */

union tSTATUS_Ambient status_Ambient;

/* Function Prototypes */

int fPULSE_Ambient (unsigned char name_);
void fINIT_Ambient (void);

/* Input Channel Functions */

int fPULSE_Ambient (unsigned char name_)
{
	switch (name_)
	{
		/***  INPULSE OFF  ***/
	case O1_OFF:		/***  PULSE CAST from PROCESS Light  ***/
		switch (status_Ambient.read_access_.STATE)
		{
		case 2:  /* STATE On */
			status_Ambient.write_access_.STATE = 1;  /* STATE Off */
			CHNOUT_mTheUnit.CHAN_AmbientAction.name_ = C12_OFF;
			OUT_.AmbientAction (CHNOUT_mTheUnit.CHAN_AmbientAction.name_);
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE ON  ***/
	case O1_ON:		/***  PULSE CAST from PROCESS Light  ***/
		switch (status_Ambient.read_access_.STATE)
		{
		case 1:  /* STATE Off */
			status_Ambient.write_access_.STATE = 2;  /* STATE On */
			CHNOUT_mTheUnit.CHAN_AmbientAction.name_ = C12_ON;
			OUT_.AmbientAction (CHNOUT_mTheUnit.CHAN_AmbientAction.name_);
			break;
		default: 
			break;
		}
		break;
	default: 
		return 0;
	}
	return 1;
}

/* Process Initialization Function */

void fINIT_Ambient (void)
{
	status_Ambient.write_access_.STATE = 1;  /* STATE Off */
}

/*********************************************************************
	End of Module for PROCESS Ambient
*********************************************************************/
