
/*********************************************************************
	SYSTEM Findling01
	IMPLEMENTATION Arduino
	Module for CIP SHELL sTheUnit
	Filename: sTheUnit.c
	generated by CIP Tool(R) Version 4.41.00
		February 12, 2015  10:58:33 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "sTheUnit.h"

/* Input Interface */

struct tIN_ IN_;

/* Output Interface */

struct tOUT_ OUT_;

/* Trigger Interface  */

struct tTRG_ TRG_;

/*********************************************************************
	End of Module for CIP SHELL sTheUnit
*********************************************************************/
