
/*********************************************************************
	SYSTEM Findling01
	IMPLEMENTATION Arduino
	Trace Interface Header File for CIP MACHINE mTheUnit
	Filename: tTheUnit.h
	generated by CIP Tool(R) Version 4.41.00
		October 29, 2014  7:18:35 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

#ifndef _THEADER
#define _THEADER

/* Text Switch Constants */

#ifdef _TRACE__
	#undef _TRACE__
#endif 

#ifdef _UTIO__
	#undef _UTIO__
#endif 

/* Include Files */

#include <stdio.h>
#include <string.h>
#include "mTheUnit.h"


#endif 

/*********************************************************************
	End of Trace Interface Header File for CIP MACHINE mTheUnit
*********************************************************************/
