
/*********************************************************************
	SYSTEM Lillebro
	IMPLEMENTATION ArduinoImpl
	Error Function Template Module for CIP MACHINE mDriveUnit
	Filename: _errDriveUnit.tpl
	generated by CIP Tool(R) Version 4.41.00
		January 4, 2015  4:10:34 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		'unsigned char' for delays
		C-code
*********************************************************************/

/*********************************************************************
	End of Error Function Template Module for CIP MACHINE mDriveUnit
*********************************************************************/
