
/*********************************************************************
	SYSTEM Lillebro
	IMPLEMENTATION ArduinoImpl
	Trace Template File for CIP MACHINE mDriveUnit
	Filename: _traceDriveUnit.tpl
	generated by CIP Tool(R) Version 4.41.00
		January 4, 2015  3:20:27 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		'unsigned char' for delays
		C-code
*********************************************************************/

/*********************************************************************
	End of Trace Template File for CIP MACHINE mDriveUnit
*********************************************************************/
