
/*********************************************************************
	SYSTEM Lillebro
	IMPLEMENTATION ArduinoImpl
	Error Interface Module for CIP MACHINE mDriveUnit
	Filename: eDriveUnit.c
	generated by CIP Tool(R) Version 4.41.00
		January 4, 2015  4:10:34 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		'unsigned char' for delays
		C-code
*********************************************************************/

/* Include Files */

#include "eDriveUnit.h"

/*********************************************************************
	End of Error Interface Module for CIP MACHINE mDriveUnit
*********************************************************************/
