
/*********************************************************************
	SYSTEM Lillebro
	IMPLEMENTATION ArduinoImpl
	Error Header File for CIP MACHINE mDriveUnit
	Filename: eDriveUnit.h
	generated by CIP Tool(R) Version 4.41.00
		January 4, 2015  4:10:34 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		'unsigned char' for delays
		C-code
*********************************************************************/

#ifndef _EHEADER
#define _EHEADER

/* Include Files */

#include "mDriveUnit.h"

#endif 

/*********************************************************************
	End of Error Header File for CIP MACHINE mDriveUnit
*********************************************************************/
