
/*********************************************************************
	SYSTEM Lillebro
	IMPLEMENTATION ArduinoImpl
	Module for CIP MACHINE mDriveUnit
	Filename: mDriveUnit.c
	generated by CIP Tool(R) Version 4.41.00
		January 4, 2015  4:10:34 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		'unsigned char' for delays
		C-code
*********************************************************************/

/* Include Files */

#include "mDriveUnit.h"

/* External Declarations */

void fICHAN_Events (unsigned char name_);
void fICHAN_ProximityEvents (unsigned char name_);
void fINIT_Behavior (void);
void fINIT_Demo (void);
void fINIT_Drive (void);
void fINIT_IndicatorLight (void);
void fINIT_MotorLeft (void);
void fINIT_MotorRight (void);
void fINIT_Proximity (void);
void fINIT_WanderLightController (void);

/* Global Declarations */

unsigned char time_mDriveUnit = 0;
union tCHNOUT_mDriveUnit CHNOUT_mDriveUnit;
struct tTIMING_mDriveUnit TIMING_mDriveUnit[2];
struct tTMQE_mDriveUnit *tuhead_mDriveUnit, *tutail_mDriveUnit;

/* Function Prototypes */

void fSETTIM_mDriveUnit (unsigned char *delay_, struct tTMEL_mDriveUnit *timer_, struct tTMQE_mDriveUnit *timeup_);
void fSTOPTIM_mDriveUnit (struct tTMEL_mDriveUnit *timer_, struct tTMQE_mDriveUnit *timeup_);
void fSTEP_mDriveUnit(void);
void fCHAIN_mDriveUnit(void);
void fTIMEUP_mDriveUnit(void);
void fREAD_mDriveUnit(void);
void fUPDATE_Controller (void);

/* AUTO_ Handler Function */

static void fAUTOHDL_mDriveUnit(void)
{
		/* dummy function handling no AUTO_ */
}

/* Timer Functions */

static void fTICK_mDriveUnit(void)
{
	int i_;
	time_mDriveUnit ++;
	for (i_ = 0; i_ < 2; i_ ++)
		if (TIMING_mDriveUnit[i_].set_)
			TIMING_mDriveUnit[i_].tkhndl_ ();
	TRG_.PENDING_.TIMEUP_ = tuhead_mDriveUnit != 0;
	TRG_.PENDING_.ANY_ = TRG_.PENDING_.ANY_ || TRG_.PENDING_.TIMEUP_;
}

void fSETTIM_mDriveUnit (unsigned char *delay_, struct tTMEL_mDriveUnit *timer_, struct tTMQE_mDriveUnit *timeup_)
{
	if (*delay_ > 0)
	{
		if (! timer_->set_)
			++TIMING_mDriveUnit[timeup_->proctype_].set_;
		timer_->set_ = TRUE;
		timer_->end_ = time_mDriveUnit + *delay_;
		if (tuhead_mDriveUnit == timeup_)
			tuhead_mDriveUnit = tuhead_mDriveUnit->next_;
		if (timeup_->preced_)
			timeup_->preced_->next_ = timeup_->next_;
		if (timeup_->next_)
			timeup_->next_->preced_ = timeup_->preced_;
		if (tutail_mDriveUnit == timeup_)
			tutail_mDriveUnit = timeup_->preced_;
		timeup_->preced_ = 0;
		timeup_->next_ = 0;
	}
	else 
	{
		if (timer_->set_)
			--TIMING_mDriveUnit [timeup_->proctype_].set_;
		timer_->set_ = FALSE;
		if (tuhead_mDriveUnit != timeup_ && ! timeup_->preced_ && ! timeup_->next_)
		{
			if (! tuhead_mDriveUnit)
				tuhead_mDriveUnit = tutail_mDriveUnit = timeup_;
			else 
			{
				tutail_mDriveUnit->next_ = timeup_;
				timeup_->preced_ = tutail_mDriveUnit;
				tutail_mDriveUnit = timeup_;
			}
		}
	}
}

void fSTOPTIM_mDriveUnit (struct tTMEL_mDriveUnit *timer_, struct tTMQE_mDriveUnit *timeup_)
{
	if (timer_->set_)
		--TIMING_mDriveUnit [timeup_->proctype_].set_;
	timer_->set_ = FALSE;
	if (tuhead_mDriveUnit == timeup_)
		tuhead_mDriveUnit = tuhead_mDriveUnit->next_;
	if (timeup_->preced_)
		timeup_->preced_->next_ = timeup_->next_;
	if (timeup_->next_)
		timeup_->next_->preced_ = timeup_->preced_;
	if (tutail_mDriveUnit == timeup_)
		tutail_mDriveUnit = timeup_->preced_;
	timeup_->preced_ = 0;
	timeup_->next_ = 0;
}

/* Control Functions */

	/* Step Function for CIP Machine */

void fSTEP_mDriveUnit(void)
{
	if (tuhead_mDriveUnit != 0)
		TIMING_mDriveUnit[tuhead_mDriveUnit->proctype_].tuhndl_ ();
	return;
}

	/* Chain Function for CIP Machine */

void fCHAIN_mDriveUnit(void)
{
	return;
}

	/* Timeup Function for CIP Machine */

void fTIMEUP_mDriveUnit(void)
{
	if (tuhead_mDriveUnit != 0)
		TIMING_mDriveUnit [tuhead_mDriveUnit->proctype_].tuhndl_ ();
	return;
}

	/* Read Function for CIP Machine */

void fREAD_mDriveUnit(void)
{
	return;
}

/* Update Functions */

void fUPDATE_Controller (void)
{
	TRG_.PENDING_.TIMEUP_ = tuhead_mDriveUnit != 0;
	TRG_.PENDING_.ANY_ = 
		TRG_.PENDING_.TIMEUP_;
}

/* Initialization Function */

int fINIT_(void)
{
	tuhead_mDriveUnit = tutail_mDriveUnit = 0;
	TRG_.TICK_ = fTICK_mDriveUnit;
	TRG_.CHAIN_ = fCHAIN_mDriveUnit;
	TRG_.TIMEUP_ = fTIMEUP_mDriveUnit;
	TRG_.STEP_ = fSTEP_mDriveUnit;
	TRG_.READ_ = fREAD_mDriveUnit;
	TRG_.AUTO_ = fAUTOHDL_mDriveUnit;
	TRG_.PENDING_.ANY_ = 0;
	TRG_.PENDING_.CHAIN_ = 0;
	TRG_.PENDING_.TIMEUP_ = 0;
	TRG_.PENDING_.READ_ = 0;
	TRG_.PENDING_.AUTO_ = 0;
	IN_.Events = fICHAN_Events;
	IN_.ProximityEvents = fICHAN_ProximityEvents;
	iCHAN_();
	if (!OUT_.RightMotorActions)
		return 0;
	if (!OUT_.LeftMotorActions)
		return 0;
	if (!OUT_.WanderLightActions)
		return 0;
	fINIT_Behavior ();
	fINIT_Demo ();
	fINIT_Drive ();
	fINIT_IndicatorLight ();
	fINIT_MotorLeft ();
	fINIT_MotorRight ();
	fINIT_Proximity ();
	fINIT_WanderLightController ();
	return 1;
}

/*********************************************************************
	End of Module for CIP MACHINE mDriveUnit
*********************************************************************/
