
/*********************************************************************
	SYSTEM Lillebro
	Module for PROCESS WanderLightController
	Filename: WanderLightController.c
	generated by CIP Tool(R) Version 4.41.00
		January 4, 2015  3:20:27 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		'unsigned char' for delays
		C-code
*********************************************************************/

/* Include Files */

#include "mDriveUnit.h"

/* Process Macro Definitions */

#define SELF status_WanderLightController.write_access_
#define STATUS status_WanderLightController.read_access_
#define TIME time_mDriveUnit

/* Process Definitions */

/* MODES */
#define normal 1

/* STATES */
#define Wander 1


/* INPULSES */
#define IP_WANDER 1
#define TIMEUP_ 2
#define IP_AVOID 3


/* OUTPULSES */

#define O7_AVOID 16
#define O7_WANDER 17
#define O5_GO_BACKWARD 8
#define O5_GO_STRAIGHT 7
#define O5_STOP 9
#define O5_TURN_LEFT 5
#define O5_TURN_RIGHT 6
#define O3_BWD 10
#define O3_FWD 3
#define O3_STOP 4
#define O3_TURN_LEFT 2
#define O3_TURN_RIGHT 1
#define O8_SHOW_AVOID 14
#define O8_SHOW_WANDER 15
#define O6_ATTENTION 11
#define O6_CLEAR 13
#define O6_DANGER 12

/* External Declarations */

extern unsigned char time_mDriveUnit;
extern struct tTMQE_mDriveUnit *tuhead_mDriveUnit, *tutail_mDriveUnit;
extern union tCHNOUT_mDriveUnit CHNOUT_mDriveUnit;
extern struct tTIMING_mDriveUnit TIMING_mDriveUnit[2];

void fUPDATE_Controller (void);
void fSETTIM_mDriveUnit (unsigned char *delay_, struct tTMEL_mDriveUnit *timer_, struct tTMQE_mDriveUnit *timeup_);
void fSTOPTIM_mDriveUnit (struct tTMEL_mDriveUnit *timer_, struct tTMQE_mDriveUnit *timeup_);

/* Global Declarations */

static unsigned char delay_;
struct tPRINST_WanderLightController IO_WanderLightController;
union tSTATUS_WanderLightController status_WanderLightController;

/* Function Prototypes */

int fPULSE_WanderLightController (unsigned char name_);
void fINIT_WanderLightController (void);

/* Input Channel Functions */

int fPULSE_WanderLightController (unsigned char name_)
{
	switch (name_)
	{
		/***  INPULSE AVOID  ***/
	case O8_SHOW_AVOID:		/***  PULSE CAST from PROCESS IndicatorLight  ***/
		switch (status_WanderLightController.read_access_.STATE)
		{
		case 1:  /* STATE Wander */
			status_WanderLightController.write_access_.STATE = 1;  /* STATE Wander */
			fSTOPTIM_mDriveUnit (&IO_WanderLightController.timer_, 
				&IO_WanderLightController.timeup_);
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE WANDER  ***/
	case O8_SHOW_WANDER:		/***  PULSE CAST from PROCESS IndicatorLight  ***/
		switch (status_WanderLightController.read_access_.STATE)
		{
		case 1:  /* STATE Wander */
			{
				delay_ =  10;	/***  DELAY WanderLightDelay  ***/
				status_WanderLightController.write_access_.STATE = 1;  /* STATE Wander */
				CHNOUT_mDriveUnit.CHAN_WanderLightActions.name_ = C5_CHANGE;
				OUT_.WanderLightActions (CHNOUT_mDriveUnit.CHAN_WanderLightActions.name_);
				fSETTIM_mDriveUnit (&delay_, 
					&IO_WanderLightController.timer_, 
					&IO_WanderLightController.timeup_);
			}
			break;
		default: 
			break;
		}
		break;
	default: 
		return 0;
	}
	return 1;
}

/* Timer Functions */

static void fTICK_WanderLightController (void)
{
	if (IO_WanderLightController.timer_.set_ && 
		IO_WanderLightController.timer_.end_ == time_mDriveUnit)
	{
		IO_WanderLightController.timer_.set_ = FALSE;
		--TIMING_mDriveUnit[1].set_;
		if (tuhead_mDriveUnit != &IO_WanderLightController.timeup_ && 
			!IO_WanderLightController.timeup_.preced_ && 
			!IO_WanderLightController.timeup_.next_)
		{
			if (! tuhead_mDriveUnit)
				tuhead_mDriveUnit = tutail_mDriveUnit = &IO_WanderLightController.timeup_;
			else 
			{
				tutail_mDriveUnit->next_ = &IO_WanderLightController.timeup_;
				IO_WanderLightController.timeup_.preced_ = tutail_mDriveUnit;
				tutail_mDriveUnit = &IO_WanderLightController.timeup_;
			}
		}
	}
}

static void fTUHNDL_WanderLightController (void)
{
	struct tTMQE_mDriveUnit *element_ = tuhead_mDriveUnit;
	if (tuhead_mDriveUnit == tutail_mDriveUnit)
		tuhead_mDriveUnit = tutail_mDriveUnit = 0;
	else 
	{
		tuhead_mDriveUnit = element_->next_;
		element_->next_ = 0;
		tuhead_mDriveUnit->preced_ = 0;
	}
	switch (status_WanderLightController.read_access_.STATE)
	{
	case 1:  /* STATE Wander */
		{
			delay_ =  10;	/***  DELAY WanderLightDelay  ***/
			status_WanderLightController.write_access_.STATE = 1;  /* STATE Wander */
			CHNOUT_mDriveUnit.CHAN_WanderLightActions.name_ = C5_CHANGE;
			OUT_.WanderLightActions (CHNOUT_mDriveUnit.CHAN_WanderLightActions.name_);
			fSETTIM_mDriveUnit (&delay_, 
				&IO_WanderLightController.timer_, 
				&IO_WanderLightController.timeup_);
		}
		break;
	default: 
		break;
	}
	fUPDATE_Controller ();
}

/* Process Initialization Function */

void fINIT_WanderLightController (void)
{
	status_WanderLightController.write_access_.STATE = 1;  /* STATE Wander */
	IO_WanderLightController.timer_.set_ = FALSE;
	IO_WanderLightController.timeup_.preced_ = 0;
	IO_WanderLightController.timeup_.next_ = 0;
	IO_WanderLightController.timeup_.proctype_ = 1;
	TIMING_mDriveUnit[1].tkhndl_ = fTICK_WanderLightController;
	TIMING_mDriveUnit[1].tuhndl_ = fTUHNDL_WanderLightController;
}

/*********************************************************************
	End of Module for PROCESS WanderLightController
*********************************************************************/
