
/*********************************************************************
	SYSTEM Fhotibot
	IMPLEMENTATION Arduino
	CIP Connector Template Module for CIP SHELL sTheUnit
	Filename: _conTheUnit.tpl
	generated by CIP Tool(R) Version 4.41.00
		February 3, 2012  8:47:23 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "sTheUnit.h"


/*********************************************************************
	User defined Output Channel Functions
*********************************************************************/

/* Output Channel Functions,
	called by CIP Machine when a Message is written.
	User defined function, with name to consider as suggestion */

/* Parameters
	name_		name value of message */

void uCHAN_LeftDriver (unsigned char name_)
{
//  Serial.println("LeftDriver");
	/* Accessing MESSAGE */
	switch (name_)
	{
	case C4_Backward:
                digitalWrite(13,1);
//		Serial.println("LeftDriver Backward");
		break;
	case C4_Forward:
digitalWrite(13,1);
//		Serial.println("LeftDriver Forward");
		break;
	case C4_Stop:
digitalWrite(13,0);
//		Serial.println("LeftDriver Stop");
		break;
	default: 
		break;
	}

}

void uCHAN_RightDriver (unsigned char name_)
{
	/* Accessing MESSAGE */
	switch (name_)
	{
	case C5_Backward:
		/* user defined code */
		break;
	case C5_Forward:
		/* user defined code */
		break;
	case C5_Stop:
		/* user defined code */
		break;
	default: 
		break;
	}
}


/*********************************************************************
	User defined Output Channel Interface Initialization Function
*********************************************************************/

void iCHAN_(void)
{
		/* Initializing Input Error Function only if Input Error Option set */

	#ifdef _EINPUT__
		IN_.EINPUT_ = uEINPUT_;
	#endif 

		/* Initializing Output Interface */

	OUT_.LeftDriver = uCHAN_LeftDriver;
	OUT_.RightDriver = uCHAN_RightDriver;
}



/* Input Function Calls */

	/* Referenced Input Variables (examples) */

unsigned char name_Radar;

//IN_.Radar(name_Radar);


/* Trigger Function Calls */

// TRG_.TICK_();		/* increment CIP Machine time by one Tick */

// TRG_.STEP_();		/* perform one step, if any transition (in priority order chain, timeup, local message, auto) is pending */

// TRG_.CHAIN_();		/* perform one chain, if any chain is pending */

// TRG_.TIMEUP_();		/* perform one timeup, if any timeup is pending  */

// TRG_.READ_();		/* perform one local read, if any local message is buffered */

// TRG_.AUTO_();		/* perform one auto, if any auto is pending */

/*********************************************************************
	End of CIP Connector Template Module for CIP SHELL sTheUnit
*********************************************************************/
