
/*********************************************************************
	SYSTEM Fhotibot
	IMPLEMENTATION Arduino
	Error Function Template Module for CIP MACHINE mTheUnit
	Filename: _errTheUnit.tpl
	generated by CIP Tool(R) Version 4.41.00
		February 3, 2012  8:47:32 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/*********************************************************************
	End of Error Function Template Module for CIP MACHINE mTheUnit
*********************************************************************/
