
/*********************************************************************
	SYSTEM Fhotibot
	IMPLEMENTATION Arduino
	Trace Template File for CIP MACHINE mTheUnit
	Filename: _traceTheUnit.tpl
	generated by CIP Tool(R) Version 4.41.00
		February 4, 2012  1:11:18 am
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/*********************************************************************
	End of Trace Template File for CIP MACHINE mTheUnit
*********************************************************************/
