
/*********************************************************************
	SYSTEM Fhotibot
	Module for PROCESS Behavior
	Filename: Behavior.c
	generated by CIP Tool(R) Version 4.41.00
		February 15, 2012  12:14:05 am
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mTheUnit.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define SELF status_Behavior.write_access_
#define STATUS status_Behavior.read_access_
#define TIME time_mTheUnit

/* Process Definitions */

/* MODES */
#define Normal 1
#define Autonomous 3
#define Controlled 4

/* STATES */
#define Drive 1
#define DriveBackward 2


/* INPULSES */
#define IP_Suspend 6
#define IP_Attention 7
#define IP_Clear 8
#define IP_Danger 9


/* OUTPULSES */

#define O12_Backward 13
#define O12_BackwardRight 20
#define O12_Forward 12
#define O12_Left 14
#define O12_Right 15
#define O12_Stop 16
#define O13_Attention 18
#define O13_Clear 17
#define O13_Danger 19

/* External Declarations */

extern unsigned long time_mTheUnit;
extern union tCHNOUT_mTheUnit CHNOUT_mTheUnit;
extern union tSTATUS_ObstacleAvoidance status_ObstacleAvoidance;

int fPULSE_TrackDriver (unsigned char name_);

/* Global Declarations */

union tSTATUS_Behavior status_Behavior;
const unsigned char MODTAB_Behavior[3] =       /*  [ObstacleAvoidance states] */
	{3, 1, 4};

/* Function Prototypes */

void fICHAN_RemoteControlEvents (unsigned char name_);
int fPULSE_Behavior (unsigned char name_);
void fINIT_Behavior (void);

/* Input Channel Functions */

void fICHAN_RemoteControlEvents (unsigned char name_)
{
	switch (name_)
	{
		/***  MESSAGE Backward of INPORT Direction  ***/
	case C7_Backward:
		switch (MODTAB_Behavior[status_ObstacleAvoidance.read_access_.STATE -1])
		{
		case 1:  /* MODE Normal */
			switch (status_Behavior.read_access_.STATE)
			{
			case 1:  /* STATE Drive */
				status_Behavior.write_access_.STATE = 1;  /* STATE Drive */
				fPULSE_TrackDriver (O12_Backward);
				break;
			default: 
				return;
			}
			break;
		default: 
			return;
		}
		break;
		/***  MESSAGE Forward of INPORT Direction  ***/
	case C7_Forward:
		switch (MODTAB_Behavior[status_ObstacleAvoidance.read_access_.STATE -1])
		{
		case 1:  /* MODE Normal */
			switch (status_Behavior.read_access_.STATE)
			{
			case 1:  /* STATE Drive */
				status_Behavior.write_access_.STATE = 1;  /* STATE Drive */
				fPULSE_TrackDriver (O12_Forward);
				break;
			default: 
				return;
			}
			break;
		default: 
			return;
		}
		break;
		/***  MESSAGE Left of INPORT Direction  ***/
	case C7_Left:
		switch (MODTAB_Behavior[status_ObstacleAvoidance.read_access_.STATE -1])
		{
		case 1:  /* MODE Normal */
			switch (status_Behavior.read_access_.STATE)
			{
			case 1:  /* STATE Drive */
				status_Behavior.write_access_.STATE = 1;  /* STATE Drive */
				fPULSE_TrackDriver (O12_Left);
				break;
			default: 
				return;
			}
			break;
		default: 
			return;
		}
		break;
		/***  MESSAGE Right of INPORT Direction  ***/
	case C7_Right:
		switch (MODTAB_Behavior[status_ObstacleAvoidance.read_access_.STATE -1])
		{
		case 1:  /* MODE Normal */
			switch (status_Behavior.read_access_.STATE)
			{
			case 1:  /* STATE Drive */
				status_Behavior.write_access_.STATE = 1;  /* STATE Drive */
				fPULSE_TrackDriver (O12_Right);
				break;
			default: 
				return;
			}
			break;
		default: 
			return;
		}
		break;
		/***  MESSAGE Stop of INPORT Direction  ***/
	case C7_Stop:
		switch (MODTAB_Behavior[status_ObstacleAvoidance.read_access_.STATE -1])
		{
		case 3:  /* MODE Autonomous */
			switch (status_Behavior.read_access_.STATE)
			{
			case 1:  /* STATE Drive */
				status_Behavior.write_access_.STATE = 1;  /* STATE Drive */
				fPULSE_TrackDriver (O12_Stop);
				break;
			default: 
				return;
			}
			break;
		case 1:  /* MODE Normal */
			switch (status_Behavior.read_access_.STATE)
			{
			case 1:  /* STATE Drive */
				status_Behavior.write_access_.STATE = 1;  /* STATE Drive */
				fPULSE_TrackDriver (O12_Stop);
				break;
			default: 
				return;
			}
			break;
		default: 
			return;
		}
		break;
	default: 
		return;
	}
	return;
}

#undef EXCEPTION

int fPULSE_Behavior (unsigned char name_)
{
	switch (name_)
	{
		/***  INPULSE Attention  ***/
	case O13_Attention:		/***  PULSE CAST from PROCESS ObstacleAvoidance  ***/
		switch (MODTAB_Behavior[status_ObstacleAvoidance.read_access_.STATE -1])
		{
		case 3:  /* MODE Autonomous */
			switch (status_Behavior.read_access_.STATE)
			{
			case 1:  /* STATE Drive */
				status_Behavior.write_access_.STATE = 1;  /* STATE Drive */
				fPULSE_TrackDriver (O12_Left);
				break;
			case 2:  /* STATE DriveBackward */
				status_Behavior.write_access_.STATE = 2;  /* STATE DriveBackward */
				fPULSE_TrackDriver (O12_BackwardRight);
				break;
			default: 
				break;
			}
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE Clear  ***/
	case O13_Clear:		/***  PULSE CAST from PROCESS ObstacleAvoidance  ***/
		switch (MODTAB_Behavior[status_ObstacleAvoidance.read_access_.STATE -1])
		{
		case 3:  /* MODE Autonomous */
			switch (status_Behavior.read_access_.STATE)
			{
			case 1:  /* STATE Drive */
				status_Behavior.write_access_.STATE = 1;  /* STATE Drive */
				fPULSE_TrackDriver (O12_Forward);
				break;
			default: 
				break;
			}
			break;
		case 1:  /* MODE Normal */
			switch (status_Behavior.read_access_.STATE)
			{
			case 2:  /* STATE DriveBackward */
				status_Behavior.write_access_.STATE = 1;  /* STATE Drive */
				fPULSE_TrackDriver (O12_Forward);
				break;
			default: 
				break;
			}
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE Danger  ***/
	case O13_Danger:		/***  PULSE CAST from PROCESS ObstacleAvoidance  ***/
		switch (MODTAB_Behavior[status_ObstacleAvoidance.read_access_.STATE -1])
		{
		case 3:  /* MODE Autonomous */
			switch (status_Behavior.read_access_.STATE)
			{
			case 1:  /* STATE Drive */
				status_Behavior.write_access_.STATE = 1;  /* STATE Drive */
				fPULSE_TrackDriver (O12_Backward);
				break;
			default: 
				break;
			}
			break;
		case 4:  /* MODE Controlled */
			switch (status_Behavior.read_access_.STATE)
			{
			case 1:  /* STATE Drive */
				status_Behavior.write_access_.STATE = 2;  /* STATE DriveBackward */
				fPULSE_TrackDriver (O12_Backward);
				break;
			default: 
				break;
			}
			break;
		default: 
			break;
		}
		break;
	default: 
		return 0;
	}
	return 1;
}

/* Process Initialization Function */

void fINIT_Behavior (void)
{
	status_Behavior.write_access_.STATE = 1;  /* STATE Drive */
}

/*********************************************************************
	End of Module for PROCESS Behavior
*********************************************************************/
