
/*********************************************************************
	SYSTEM Fhotibot
	IMPLEMENTATION Arduino
	Error Interface Module for CIP MACHINE mTheUnit
	Filename: eTheUnit.c
	generated by CIP Tool(R) Version 4.41.00
		February 4, 2012  1:11:18 am
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "eTheUnit.h"

/*********************************************************************
	End of Error Interface Module for CIP MACHINE mTheUnit
*********************************************************************/
