
/*********************************************************************
	SYSTEM Fhotibot
	IMPLEMENTATION Arduino
	Header File for CIP MACHINE mTheUnit
	Filename: mTheUnit.h
	generated by CIP Tool(R) Version 4.41.00
		February 15, 2012  12:14:04 am
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

#ifndef _MHEADER
#define _MHEADER

/* Include Files */

#include <stdlib.h>
#include "sTheUnit.h"

/* Macro Definitions */

#ifndef FALSE
#define FALSE 0
#endif

#ifndef TRUE
#define TRUE 1
#endif


/* Outpulse Types */

struct tOUTPLS_Behavior
{
	unsigned char  name_;
};

struct tOUTPLS_ObstacleAvoidance
{
	unsigned char  name_;
};

union tOUTPLS_Drive
{
	struct tOUTPLS_Behavior OUTPLS_Behavior;
	struct tOUTPLS_ObstacleAvoidance OUTPLS_ObstacleAvoidance;
};

struct tOUTPLS_DriveObserver
{
	unsigned char  name_;
};

struct tOUTPLS_TargetDirection
{
	unsigned char  name_;
};

union tOUTPLS_TargetFinder
{
	struct tOUTPLS_DriveObserver OUTPLS_DriveObserver;
	struct tOUTPLS_TargetDirection OUTPLS_TargetDirection;
};

/* Global Output Type */

struct tCHAN_RightMotor
{
	unsigned char name_;
};

struct tCHAN_LeftMotor
{
	unsigned char name_;
};

struct tCHAN_ObstacleEvents
{
	unsigned char name_;
};

struct tCHAN_RemoteControlEvents
{
	unsigned char name_;
};

union tCHNOUT_mTheUnit
{
	struct tCHAN_LeftMotor CHAN_LeftMotor;
	struct tCHAN_ObstacleEvents CHAN_ObstacleEvents;
	struct tCHAN_RemoteControlEvents CHAN_RemoteControlEvents;
	struct tCHAN_RightMotor CHAN_RightMotor;
};

/* Global Table Elements */

/* Types for Process Behavior */

struct tPRSTAT_Behavior
{
	unsigned char STATE;
};

union tSTATUS_Behavior
{
	struct tPRSTAT_Behavior write_access_;
	const struct tPRSTAT_Behavior read_access_;
};

/* Types for Process ObstacleAvoidance */

struct tPRSTAT_ObstacleAvoidance
{
	unsigned char STATE;
};

union tSTATUS_ObstacleAvoidance
{
	struct tPRSTAT_ObstacleAvoidance write_access_;
	const struct tPRSTAT_ObstacleAvoidance read_access_;
};

/* Types for Process TrackDriver */

struct tPRSTAT_TrackDriver
{
	unsigned char STATE;
};

union tSTATUS_TrackDriver
{
	struct tPRSTAT_TrackDriver write_access_;
	const struct tPRSTAT_TrackDriver read_access_;
};

/* Types for Process DriveObserver */

struct tPRSTAT_DriveObserver
{
	unsigned char STATE;
};

union tSTATUS_DriveObserver
{
	struct tPRSTAT_DriveObserver write_access_;
	const struct tPRSTAT_DriveObserver read_access_;
};

/* Types for Process Finder */

struct tPRSTAT_Finder
{
	unsigned char STATE;
};

union tSTATUS_Finder
{
	struct tPRSTAT_Finder write_access_;
	const struct tPRSTAT_Finder read_access_;
};

/* Types for Process TargetDirection */

struct tPRSTAT_TargetDirection
{
	unsigned char STATE;
};

union tSTATUS_TargetDirection
{
	struct tPRSTAT_TargetDirection write_access_;
	const struct tPRSTAT_TargetDirection read_access_;
};

#endif 

/*********************************************************************
	End of Header File for CIP MACHINE mTheUnit
*********************************************************************/
