
/*********************************************************************
	SYSTEM Fhotibot
	Module for PROCESS ObstacleAvoidance
	Filename: ObstacleAvoidance.c
	generated by CIP Tool(R) Version 4.41.00
		February 15, 2012  12:14:05 am
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mTheUnit.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define SELF status_ObstacleAvoidance.write_access_
#define STATUS status_ObstacleAvoidance.read_access_
#define TIME time_mTheUnit

/* Process Definitions */

/* MODES */
#define Normal 1

/* STATES */
#define Attention 1
#define Clear 2
#define Danger 3



/* OUTPULSES */

#define O12_Backward 13
#define O12_BackwardRight 20
#define O12_Forward 12
#define O12_Left 14
#define O12_Right 15
#define O12_Stop 16
#define O13_Attention 18
#define O13_Clear 17
#define O13_Danger 19

/* External Declarations */

extern unsigned long time_mTheUnit;
extern union tCHNOUT_mTheUnit CHNOUT_mTheUnit;

int fPULSE_Behavior (unsigned char name_);

/* Global Declarations */

union tSTATUS_ObstacleAvoidance status_ObstacleAvoidance;

/* Function Prototypes */

void fICHAN_AutonomousDriveEvents (unsigned char name_);
void fINIT_ObstacleAvoidance (void);

/* Input Channel Functions */

void fICHAN_AutonomousDriveEvents (unsigned char name_)
{
	switch (name_)
	{
		/***  MESSAGE Attention of INPORT ObstacleAvoidance  ***/
	case C8_Attention:
		switch (status_ObstacleAvoidance.read_access_.STATE)
		{
		case 2:  /* STATE Clear */
			status_ObstacleAvoidance.write_access_.STATE = 1;  /* STATE Attention */
			CHNOUT_mTheUnit.CHAN_ObstacleEvents.name_ = C9_AvoidingObstacle;
			OUT_.ObstacleEvents (CHNOUT_mTheUnit.CHAN_ObstacleEvents.name_);
			fPULSE_Behavior (O13_Attention);
			break;
		case 3:  /* STATE Danger */
			status_ObstacleAvoidance.write_access_.STATE = 1;  /* STATE Attention */
			CHNOUT_mTheUnit.CHAN_ObstacleEvents.name_ = C9_AvoidingObstacle;
			OUT_.ObstacleEvents (CHNOUT_mTheUnit.CHAN_ObstacleEvents.name_);
			fPULSE_Behavior (O13_Attention);
			break;
		default: 
			return;
		}
		break;
		/***  MESSAGE Clear of INPORT ObstacleAvoidance  ***/
	case C8_Clear:
		switch (status_ObstacleAvoidance.read_access_.STATE)
		{
		case 1:  /* STATE Attention */
			status_ObstacleAvoidance.write_access_.STATE = 2;  /* STATE Clear */
			CHNOUT_mTheUnit.CHAN_ObstacleEvents.name_ = C9_ClearOfObstacles;
			OUT_.ObstacleEvents (CHNOUT_mTheUnit.CHAN_ObstacleEvents.name_);
			fPULSE_Behavior (O13_Clear);
			break;
		case 3:  /* STATE Danger */
			status_ObstacleAvoidance.write_access_.STATE = 2;  /* STATE Clear */
			CHNOUT_mTheUnit.CHAN_ObstacleEvents.name_ = C9_ClearOfObstacles;
			OUT_.ObstacleEvents (CHNOUT_mTheUnit.CHAN_ObstacleEvents.name_);
			fPULSE_Behavior (O13_Clear);
			break;
		default: 
			return;
		}
		break;
		/***  MESSAGE Danger of INPORT ObstacleAvoidance  ***/
	case C8_Danger:
		switch (status_ObstacleAvoidance.read_access_.STATE)
		{
		case 1:  /* STATE Attention */
			status_ObstacleAvoidance.write_access_.STATE = 3;  /* STATE Danger */
			CHNOUT_mTheUnit.CHAN_ObstacleEvents.name_ = C9_AvoidingObstacle;
			OUT_.ObstacleEvents (CHNOUT_mTheUnit.CHAN_ObstacleEvents.name_);
			fPULSE_Behavior (O13_Danger);
			break;
		case 2:  /* STATE Clear */
			status_ObstacleAvoidance.write_access_.STATE = 3;  /* STATE Danger */
			CHNOUT_mTheUnit.CHAN_ObstacleEvents.name_ = C9_AvoidingObstacle;
			OUT_.ObstacleEvents (CHNOUT_mTheUnit.CHAN_ObstacleEvents.name_);
			fPULSE_Behavior (O13_Danger);
			break;
		default: 
			return;
		}
		break;
	default: 
		return;
	}
	return;
}

#undef EXCEPTION

/* Process Initialization Function */

void fINIT_ObstacleAvoidance (void)
{
	status_ObstacleAvoidance.write_access_.STATE = 2;  /* STATE Clear */
}

/*********************************************************************
	End of Module for PROCESS ObstacleAvoidance
*********************************************************************/
