
/*********************************************************************
	SYSTEM Fhotibot
	IMPLEMENTATION Arduino
	Header File for CIP SHELL sTheUnit
	Filename: sTheUnit.h
	generated by CIP Tool(R) Version 4.41.00
		February 15, 2012  12:14:03 am
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

#ifndef _SHEADER
#define _SHEADER

/* Code Option Constants */

#ifdef _EINPUT__
	#undef _EINPUT__
#endif 

/* Channel Enumerations */

#define C_AutonomousDriveEvents 8
#define C_Direction 10
#define C_LeftMotor 4
#define C_ObstacleEvents 9
#define C_RemoteControlEvents 7
#define C_RightMotor 5

/* MESSAGE Enumeration of CHANNEL LeftMotor */

#define C4_ 0
#define C4_Backward 2
#define C4_Forward 1
#define C4_Stop 3

/* MESSAGE Enumeration of CHANNEL RightMotor */

#define C5_ 0
#define C5_Backward 1
#define C5_Forward 2
#define C5_Stop 3

/* MESSAGE Enumeration of CHANNEL RemoteControlEvents */

#define C7_ 0
#define C7_Backward 3
#define C7_Forward 4
#define C7_Left 1
#define C7_Right 2
#define C7_Stop 5

/* MESSAGE Enumeration of CHANNEL AutonomousDriveEvents */

#define C8_ 0
#define C8_Attention 2
#define C8_Clear 1
#define C8_Danger 3

/* MESSAGE Enumeration of CHANNEL ObstacleEvents */

#define C9_ 0
#define C9_AvoidingObstacle 1
#define C9_ClearOfObstacles 2

/* MESSAGE Enumeration of CHANNEL Direction */

#define C10_ 0
#define C10_Ahead 1
#define C10_Behind 2
#define C10_Left 3
#define C10_Right 4
#define C10_Unknown 5

/* Input Interface Type */

struct tIN_
{
	void (*AutonomousDriveEvents) (unsigned char);
	void (*Direction) (unsigned char);
	void (*ObstacleEvents) (unsigned char);
	void (*RemoteControlEvents) (unsigned char);
};

/* Output Interface Type */

struct tOUT_
{
	void (*AutonomousDriveEvents) (unsigned char);
	void (*LeftMotor) (unsigned char);
	void (*ObstacleEvents) (unsigned char);
	void (*RemoteControlEvents) (unsigned char);
	void (*RightMotor) (unsigned char);
};

/* Trigger Interface Type */

struct tTRG_
{
	void (*TICK_) (void);		/* increment CIP MACHINE time */
	void (*STEP_) (void);		/* trigger CIP MACHINE transition */
	void (*CHAIN_) (void);		/* trigger pending chain CIP MACHINE transition */
	void (*TIMEUP_) (void);		/* trigger pending timeup CIP MACHINE transition */
	void (*READ_) (void);		/* trigger CIP MACHINE to read from internal message buffer */
	void (*AUTO_) (void);		/* trigger pending auto CIP MACHINE transition */
};

/* External Interface Declarations */

extern struct tIN_ IN_;		/* Input Channel Interface defined in sTheUnit.c */
extern struct tOUT_ OUT_;		/* Output Channel Interface defined in sTheUnit.c */
extern struct tTRG_ TRG_;		/* Trigger Interface defined in sTheUnit.c */

/* Unit Initialization Function, defined in mTheUnit.c
	called by User to initialize CIP Machine
		returning 1 if successful
		returning 0 if failed */

int fINIT_(void);

/* User defined Initialization Function for CIP Shell Interface Initialization 
	called by Unit Initialization Function */

void iCHAN_(void);


#endif 

/*********************************************************************
	End of CIP UNIT Header File for CIP SHELL sTheUnit
*********************************************************************/
