
/*********************************************************************
	SYSTEM Fhotibot
	Module for PROCESS TargetDirection
	Filename: TargetDirection.c
	generated by CIP Tool(R) Version 4.41.00
		February 15, 2012  12:14:06 am
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mTheUnit.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define SELF status_TargetDirection.write_access_
#define STATUS status_TargetDirection.read_access_
#define TIME time_mTheUnit

/* Process Definitions */

/* MODES */
#define Normal 1

/* STATES */
#define Ahead 1
#define Behind 2
#define Left 3
#define Right 4
#define Unknown 5



/* OUTPULSES */

#define O15_AvoidingObstacle 5
#define O15_ClearOfObstacle 6
#define O7_Ahead 1
#define O7_Behind 2
#define O7_ToTheLeft 4
#define O7_ToTheRight 3
#define O7_Unknown 7

/* External Declarations */

extern unsigned long time_mTheUnit;
extern union tCHNOUT_mTheUnit CHNOUT_mTheUnit;

int fPULSE_Finder (unsigned char name_);

/* Global Declarations */

union tSTATUS_TargetDirection status_TargetDirection;

/* Function Prototypes */

void fICHAN_Direction (unsigned char name_);
void fINIT_TargetDirection (void);

/* Input Channel Functions */

void fICHAN_Direction (unsigned char name_)
{
	switch (name_)
	{
		/***  MESSAGE Ahead of INPORT Direction  ***/
	case C10_Ahead:
		switch (status_TargetDirection.read_access_.STATE)
		{
		case 3:  /* STATE Left */
			status_TargetDirection.write_access_.STATE = 1;  /* STATE Ahead */
			fPULSE_Finder (O7_Ahead);
			break;
		case 4:  /* STATE Right */
			status_TargetDirection.write_access_.STATE = 1;  /* STATE Ahead */
			fPULSE_Finder (O7_Ahead);
			break;
		case 5:  /* STATE Unknown */
			status_TargetDirection.write_access_.STATE = 1;  /* STATE Ahead */
			fPULSE_Finder (O7_Ahead);
			break;
		default: 
			return;
		}
		break;
		/***  MESSAGE Behind of INPORT Direction  ***/
	case C10_Behind:
		switch (status_TargetDirection.read_access_.STATE)
		{
		case 3:  /* STATE Left */
			status_TargetDirection.write_access_.STATE = 2;  /* STATE Behind */
			fPULSE_Finder (O7_Behind);
			break;
		case 5:  /* STATE Unknown */
			status_TargetDirection.write_access_.STATE = 2;  /* STATE Behind */
			fPULSE_Finder (O7_Behind);
			break;
		default: 
			return;
		}
		break;
		/***  MESSAGE Left of INPORT Direction  ***/
	case C10_Left:
		switch (status_TargetDirection.read_access_.STATE)
		{
		case 1:  /* STATE Ahead */
			status_TargetDirection.write_access_.STATE = 3;  /* STATE Left */
			fPULSE_Finder (O7_ToTheLeft);
			break;
		case 2:  /* STATE Behind */
			status_TargetDirection.write_access_.STATE = 3;  /* STATE Left */
			fPULSE_Finder (O7_ToTheLeft);
			break;
		case 5:  /* STATE Unknown */
			status_TargetDirection.write_access_.STATE = 3;  /* STATE Left */
			fPULSE_Finder (O7_ToTheLeft);
			break;
		default: 
			return;
		}
		break;
		/***  MESSAGE Right of INPORT Direction  ***/
	case C10_Right:
		switch (status_TargetDirection.read_access_.STATE)
		{
		case 1:  /* STATE Ahead */
			status_TargetDirection.write_access_.STATE = 4;  /* STATE Right */
			fPULSE_Finder (O7_ToTheRight);
			break;
		case 2:  /* STATE Behind */
			status_TargetDirection.write_access_.STATE = 4;  /* STATE Right */
			fPULSE_Finder (O7_ToTheRight);
			break;
		case 4:  /* STATE Right */
			status_TargetDirection.write_access_.STATE = 2;  /* STATE Behind */
			fPULSE_Finder (O7_ToTheRight);
			break;
		case 5:  /* STATE Unknown */
			status_TargetDirection.write_access_.STATE = 4;  /* STATE Right */
			fPULSE_Finder (O7_ToTheRight);
			break;
		default: 
			return;
		}
		break;
		/***  MESSAGE Unknown of INPORT Direction  ***/
	case C10_Unknown:
		switch (status_TargetDirection.read_access_.STATE)
		{
		case 1:  /* STATE Ahead */
			status_TargetDirection.write_access_.STATE = 5;  /* STATE Unknown */
			fPULSE_Finder (O7_Unknown);
			break;
		case 2:  /* STATE Behind */
			status_TargetDirection.write_access_.STATE = 5;  /* STATE Unknown */
			fPULSE_Finder (O7_Unknown);
			break;
		case 3:  /* STATE Left */
			status_TargetDirection.write_access_.STATE = 5;  /* STATE Unknown */
			fPULSE_Finder (O7_Unknown);
			break;
		case 4:  /* STATE Right */
			status_TargetDirection.write_access_.STATE = 5;  /* STATE Unknown */
			fPULSE_Finder (O7_Unknown);
			break;
		default: 
			return;
		}
		break;
	default: 
		return;
	}
	return;
}

#undef EXCEPTION

/* Process Initialization Function */

void fINIT_TargetDirection (void)
{
	status_TargetDirection.write_access_.STATE = 5;  /* STATE Unknown */
}

/*********************************************************************
	End of Module for PROCESS TargetDirection
*********************************************************************/
