
/*********************************************************************
	SYSTEM Fhotibot
	Module for PROCESS TrackDrive
	Filename: TrackDrive.c
	generated by CIP Tool(R) Version 4.41.00
		February 3, 2012  8:47:32 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mTheUnit.h"

/* Process Macro Definitions */

#define SELF status_TrackDrive.write_access_
#define STATUS status_TrackDrive.read_access_
#define TIME time_mTheUnit

/* Process Definitions */

/* MODES */
#define Normal 1

/* STATES */
#define Backward 1
#define Forward 2
#define Left 3
#define Right 4
#define Stop 5


/* INPULSES */
#define IP_Forward 1
#define IP_Backward 2
#define IP_Left 3
#define IP_Right 4
#define IP_Stop 5


/* OUTPULSES */

#define O3_Backward 4
#define O3_Forward 1
#define O3_Left 3
#define O3_Stop 2

/* External Declarations */

extern unsigned long time_mTheUnit;
extern union tCHNOUT_mTheUnit CHNOUT_mTheUnit;


/* Global Declarations */

union tSTATUS_TrackDrive status_TrackDrive;

/* Function Prototypes */

int fPULSE_TrackDrive (unsigned char name_);
void fINIT_TrackDrive (void);

/* Input Channel Functions */

int fPULSE_TrackDrive (unsigned char name_)
{
	switch (name_)
	{
		/***  INPULSE Backward  ***/
	case O3_Backward:		/***  PULSE CAST from PROCESS DriveControl  ***/
		switch (status_TrackDrive.read_access_.STATE)
		{
		case 5:  /* STATE Stop */
			status_TrackDrive.write_access_.STATE = 1;  /* STATE Backward */
			CHNOUT_mTheUnit.CHAN_LeftDriver.name_ = C4_Backward;
			OUT_.LeftDriver (CHNOUT_mTheUnit.CHAN_LeftDriver.name_);
			CHNOUT_mTheUnit.CHAN_RightDriver.name_ = C5_Backward;
			OUT_.RightDriver (CHNOUT_mTheUnit.CHAN_RightDriver.name_);
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE Forward  ***/
	case O3_Forward:		/***  PULSE CAST from PROCESS DriveControl  ***/
		switch (status_TrackDrive.read_access_.STATE)
		{
		case 5:  /* STATE Stop */
			status_TrackDrive.write_access_.STATE = 2;  /* STATE Forward */
			CHNOUT_mTheUnit.CHAN_LeftDriver.name_ = C4_Forward;
			OUT_.LeftDriver (CHNOUT_mTheUnit.CHAN_LeftDriver.name_);
			CHNOUT_mTheUnit.CHAN_RightDriver.name_ = C5_Forward;
			OUT_.RightDriver (CHNOUT_mTheUnit.CHAN_RightDriver.name_);
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE Left  ***/
	case O3_Left:		/***  PULSE CAST from PROCESS DriveControl  ***/
		switch (status_TrackDrive.read_access_.STATE)
		{
		case 5:  /* STATE Stop */
			status_TrackDrive.write_access_.STATE = 3;  /* STATE Left */
			CHNOUT_mTheUnit.CHAN_LeftDriver.name_ = C4_Stop;
			OUT_.LeftDriver (CHNOUT_mTheUnit.CHAN_LeftDriver.name_);
			CHNOUT_mTheUnit.CHAN_RightDriver.name_ = C5_Forward;
			OUT_.RightDriver (CHNOUT_mTheUnit.CHAN_RightDriver.name_);
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE Right  ---  untranslated  ***/

		/***  INPULSE Stop  ***/
	case O3_Stop:		/***  PULSE CAST from PROCESS DriveControl  ***/
		switch (status_TrackDrive.read_access_.STATE)
		{
		case 1:  /* STATE Backward */
			status_TrackDrive.write_access_.STATE = 5;  /* STATE Stop */
			CHNOUT_mTheUnit.CHAN_LeftDriver.name_ = C4_Stop;
			OUT_.LeftDriver (CHNOUT_mTheUnit.CHAN_LeftDriver.name_);
			CHNOUT_mTheUnit.CHAN_RightDriver.name_ = C5_Stop;
			OUT_.RightDriver (CHNOUT_mTheUnit.CHAN_RightDriver.name_);
			break;
		case 2:  /* STATE Forward */
			status_TrackDrive.write_access_.STATE = 5;  /* STATE Stop */
			CHNOUT_mTheUnit.CHAN_LeftDriver.name_ = C4_Stop;
			OUT_.LeftDriver (CHNOUT_mTheUnit.CHAN_LeftDriver.name_);
			CHNOUT_mTheUnit.CHAN_RightDriver.name_ = C5_Stop;
			OUT_.RightDriver (CHNOUT_mTheUnit.CHAN_RightDriver.name_);
			break;
		case 3:  /* STATE Left */
			status_TrackDrive.write_access_.STATE = 5;  /* STATE Stop */
			CHNOUT_mTheUnit.CHAN_LeftDriver.name_ = C4_Stop;
			OUT_.LeftDriver (CHNOUT_mTheUnit.CHAN_LeftDriver.name_);
			CHNOUT_mTheUnit.CHAN_RightDriver.name_ = C5_Stop;
			OUT_.RightDriver (CHNOUT_mTheUnit.CHAN_RightDriver.name_);
			break;
		case 4:  /* STATE Right */
			status_TrackDrive.write_access_.STATE = 5;  /* STATE Stop */
			CHNOUT_mTheUnit.CHAN_LeftDriver.name_ = C4_Stop;
			OUT_.LeftDriver (CHNOUT_mTheUnit.CHAN_LeftDriver.name_);
			CHNOUT_mTheUnit.CHAN_RightDriver.name_ = C5_Stop;
			OUT_.RightDriver (CHNOUT_mTheUnit.CHAN_RightDriver.name_);
			break;
		default: 
			break;
		}
		break;
	default: 
		return 0;
	}
	return 1;
}

/* Process Initialization Function */

void fINIT_TrackDrive (void)
{
	status_TrackDrive.write_access_.STATE = 5;  /* STATE Stop */
}

/*********************************************************************
	End of Module for PROCESS TrackDrive
*********************************************************************/
