
/*********************************************************************
	SYSTEM Fhotibot
	IMPLEMENTATION Arduino
	Trace Interface Module for CIP MACHINE mTheUnit
	Filename: tTheUnit.c
	generated by CIP Tool(R) Version 4.41.00
		February 4, 2012  1:11:18 am
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "tTheUnit.h"

/*********************************************************************
	End of Trace Interface Module for CIP MACHINE mTheUnit
*********************************************************************/
