
/*********************************************************************
	SYSTEM Boesewicht
	IMPLEMENTATION ArduinoImplementation
	Error Function Template Module for CIP MACHINE mBoesewicht
	Filename: _errBoesewicht.tpl
	generated by CIP Tool(R) Version 4.41.00
		September 11, 2012  9:33:06 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/*********************************************************************
	End of Error Function Template Module for CIP MACHINE mBoesewicht
*********************************************************************/
