
/*********************************************************************
	SYSTEM Boesewicht
	Module for PROCESS Eyes
	Filename: Eyes.c
	generated by CIP Tool(R) Version 4.41.00
		September 11, 2012  10:14:42 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mBoesewicht.h"

/* Process Macro Definitions */

#define SELF status_Eyes.write_access_
#define STATUS status_Eyes.read_access_
#define TIME time_mBoesewicht

/* Process Definitions */

/* MODES */
#define normal 1

/* STATES */
#define Closed 1
#define Open 2


/* INPULSES */
#define IP_CLOSE 1
#define IP_OPEN 2


/* OUTPULSES */

#define O7_PLAY 8
#define O7_WAIT 9
#define O7_WAKEUP 7
#define O4_OPEN_EYES 4
#define O4_PLAY 5
#define O4_WAVE 3
#define O3_DOWN 2
#define O3_NEUTRAL 6
#define O3_UP 1

/* External Declarations */

extern unsigned long time_mBoesewicht;
extern union tCHNOUT_mBoesewicht CHNOUT_mBoesewicht;

void fUPDATE_Robot (void);

/* Global Declarations */

union tSTATUS_Eyes status_Eyes;

/* Function Prototypes */

int fPULSE_Eyes (unsigned char name_);
void fINIT_Eyes (void);

/* Input Channel Functions */

int fPULSE_Eyes (unsigned char name_)
{
	switch (name_)
	{
		/***  INPULSE CLOSE  ***/
	case O4_PLAY:		/***  PULSE CAST from PROCESS Initialize  ***/
		switch (status_Eyes.read_access_.STATE)
		{
		case 2:  /* STATE Open */
			status_Eyes.write_access_.STATE = 1;  /* STATE Closed */
			CHNOUT_mBoesewicht.CHAN_EyeOutChannel.name_ = C3_CLOSE;
			OUT_.EyeOutChannel (CHNOUT_mBoesewicht.CHAN_EyeOutChannel.name_);
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE OPEN  ***/
	case O7_PLAY:		/***  PULSE CAST from PROCESS Controller  ***/
	case O7_WAIT:
	case O7_WAKEUP:
	case O4_OPEN_EYES:		/***  PULSE CAST from PROCESS Initialize  ***/
		switch (status_Eyes.read_access_.STATE)
		{
		case 1:  /* STATE Closed */
			status_Eyes.write_access_.STATE = 2;  /* STATE Open */
			CHNOUT_mBoesewicht.CHAN_EyeOutChannel.name_ = C3_OPEN;
			OUT_.EyeOutChannel (CHNOUT_mBoesewicht.CHAN_EyeOutChannel.name_);
			break;
		default: 
			break;
		}
		break;
	default: 
		return 0;
	}
	return 1;
}

/* Process Initialization Function */

void fINIT_Eyes (void)
{
	status_Eyes.write_access_.STATE = 1;  /* STATE Closed */
}

/*********************************************************************
	End of Module for PROCESS Eyes
*********************************************************************/
