
/*********************************************************************
	SYSTEM Boesewicht
	IMPLEMENTATION ArduinoImplementation
	Module for CIP SHELL sBoesewicht
	Filename: sBoesewicht.c
	generated by CIP Tool(R) Version 4.41.00
		September 19, 2012  12:35:50 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "sBoesewicht.h"

/* Input Interface */

struct tIN_ IN_;

/* Output Interface */

struct tOUT_ OUT_;

/* Trigger Interface  */

struct tTRG_ TRG_;

/*********************************************************************
	End of Module for CIP SHELL sBoesewicht
*********************************************************************/
