
/*********************************************************************
	SYSTEM Boesewicht
	IMPLEMENTATION ArduinoImplementation
	Header File for CIP SHELL sBoesewicht
	Filename: sBoesewicht.h
	generated by CIP Tool(R) Version 4.41.00
		September 19, 2012  12:35:50 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

#ifndef _SHEADER
#define _SHEADER

/* Code Option Constants */

#ifdef _EINPUT__
	#undef _EINPUT__
#endif 

/* Channel Enumerations */

#define C_ControllerChannel 6
#define C_EyeOutChannel 3
#define C_InitChannel 5
#define C_MouthOutChannel 4
#define C_WingControllerInC 8
#define C_WingControllerOutC 7
#define C_WingLeftChannel 1
#define C_WingRightChannel 2

/* MESSAGE Enumeration of CHANNEL WingLeftChannel */

#define C1_ 0
#define C1_BOTTOM 2
#define C1_CENTER 1
#define C1_TOP 3

/* MESSAGE Enumeration of CHANNEL WingRightChannel */

#define C2_ 0
#define C2_BOTTOM 2
#define C2_CENTER 1
#define C2_TOP 3

/* MESSAGE Enumeration of CHANNEL EyeOutChannel */

#define C3_ 0
#define C3_CLOSE 1
#define C3_OPEN 2

/* MESSAGE Enumeration of CHANNEL MouthOutChannel */

#define C4_ 0
#define C4_CLOSE 1
#define C4_OPEN 2

/* MESSAGE Enumeration of CHANNEL InitChannel */

#define C5_ 0
#define C5_ON 1

/* MESSAGE Enumeration of CHANNEL ControllerChannel */

#define C6_ 0
#define C6_ATTENTION 1
#define C6_CLEAR 3
#define C6_DANGER 2

/* MESSAGE Enumeration of CHANNEL WingControllerOutC */

#define C7_ 0
#define C7_Move 1

/* MESSAGE Enumeration of CHANNEL WingControllerInC */

#define C8_ 0
#define C8_ReachedAxisEnd 1

/* Input Interface Type */

struct tIN_
{
	void (*ControllerChannel) (unsigned char);
	void (*InitChannel) (unsigned char);
	void (*WingControllerInC) (unsigned char);
};

/* Output Interface Type */

struct tOUT_
{
	void (*EyeOutChannel) (unsigned char);
	void (*MouthOutChannel) (unsigned char);
	void (*WingControllerOutC) (unsigned char);
	void (*WingLeftChannel) (unsigned char);
	void (*WingRightChannel) (unsigned char);
};

/* Trigger Interface Type */

struct tPENDING_
{
	int ANY_;	/* boolean indicating any pending transitions */
	int CHAIN_;	/* boolean indicating pending CHAIN_ */
	int TIMEUP_;	/* boolean indicating pending TIMEUP_ */
	int READ_;	/* boolean indicating buffered internal message */
	int AUTO_;	/* boolean indicating reading AUTO_ */
};

struct tTRG_
{
	void (*TICK_) (void);		/* increment CIP MACHINE time */
	void (*STEP_) (void);		/* trigger CIP MACHINE transition */
	void (*CHAIN_) (void);		/* trigger pending chain CIP MACHINE transition */
	void (*TIMEUP_) (void);		/* trigger pending timeup CIP MACHINE transition */
	void (*READ_) (void);		/* trigger CIP MACHINE to read from internal message buffer */
	void (*AUTO_) (void);		/* trigger pending auto CIP MACHINE transition */
	struct tPENDING_ PENDING_;		/* information on pending transitions */
};

/* External Interface Declarations */

extern struct tIN_ IN_;		/* Input Channel Interface defined in sBoesewicht.c */
extern struct tOUT_ OUT_;		/* Output Channel Interface defined in sBoesewicht.c */
extern struct tTRG_ TRG_;		/* Trigger Interface defined in sBoesewicht.c */

/* Unit Initialization Function, defined in mBoesewicht.c
	called by User to initialize CIP Machine
		returning 1 if successful
		returning 0 if failed */

int fINIT_(void);

/* User defined Initialization Function for CIP Shell Interface Initialization 
	called by Unit Initialization Function */

void iCHAN_(void);


#endif 

/*********************************************************************
	End of CIP UNIT Header File for CIP SHELL sBoesewicht
*********************************************************************/
