
/*********************************************************************
	SYSTEM Boesewicht
	IMPLEMENTATION ArduinoImplementation
	Trace Interface Module for CIP MACHINE mBoesewicht
	Filename: tBoesewicht.c
	generated by CIP Tool(R) Version 4.41.00
		September 11, 2012  10:14:43 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "tBoesewicht.h"

/*********************************************************************
	End of Trace Interface Module for CIP MACHINE mBoesewicht
*********************************************************************/
