
/*********************************************************************
	SYSTEM Boesewicht
	IMPLEMENTATION ArduinoImplementation
	Trace Interface Header File for CIP MACHINE mBoesewicht
	Filename: tBoesewicht.h
	generated by CIP Tool(R) Version 4.41.00
		September 19, 2012  12:35:52 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

#ifndef _THEADER
#define _THEADER

/* Text Switch Constants */

#ifdef _TRACE__
	#undef _TRACE__
#endif 

#ifdef _UTIO__
	#undef _UTIO__
#endif 

/* Include Files */

#include <stdio.h>
#include <string.h>
#include "mBoesewicht.h"


#endif 

/*********************************************************************
	End of Trace Interface Header File for CIP MACHINE mBoesewicht
*********************************************************************/
