
/*********************************************************************
	SYSTEM Boesewicht
	Module for PROCESS WaveWings
	Filename: WaveWings.c
	generated by CIP Tool(R) Version 4.41.00
		September 19, 2012  12:35:52 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mBoesewicht.h"

/* Process Macro Definitions */

#define SELF status_WaveWings.write_access_
#define STATUS status_WaveWings.read_access_
#define TIME time_mBoesewicht

/* Process Definitions */

/* MODES */
#define normal 1
#define ClosedLoop 2

/* STATES */
#define Down 1
#define Off 2
#define Up 3


/* INPULSES */
#define TIMEUP_ 1
#define IP_ON 2
#define IP_OFF 3
#define IP_NEXT 4


/* OUTPULSES */

#define O7_PLAY 8
#define O7_WAIT 9
#define O7_WAKEUP 7
#define O4_OPEN_EYES 4
#define O4_PLAY 5
#define O4_WAVE 3
#define O3_DOWN 2
#define O3_NEUTRAL 6
#define O3_UP 1
#define O8_Still 10

/* External Declarations */

extern unsigned long time_mBoesewicht;
extern struct tTMQE_mBoesewicht *tuhead_mBoesewicht, *tutail_mBoesewicht;
extern union tCHNOUT_mBoesewicht CHNOUT_mBoesewicht;
extern struct tTIMING_mBoesewicht TIMING_mBoesewicht[2];
extern union tSTATUS_Initialize status_Initialize;

void fUPDATE_Robot (void);
int fPULSE_WingLeft (unsigned char name_);
int fPULSE_WingRight (unsigned char name_);
int fPULSE_WingController (unsigned char name_);
void fSETTIM_mBoesewicht (unsigned long *delay_, struct tTMEL_mBoesewicht *timer_, struct tTMQE_mBoesewicht *timeup_);
void fSTOPTIM_mBoesewicht (struct tTMEL_mBoesewicht *timer_, struct tTMQE_mBoesewicht *timeup_);

/* Global Declarations */

static unsigned long delay_;
struct tPRINST_WaveWings IO_WaveWings;
union tSTATUS_WaveWings status_WaveWings;
const unsigned char MODTAB_WaveWings[3] =       /*  [Initialize states] */
	{1, 2, 1};

/* Function Prototypes */

int fPULSE_WaveWings (unsigned char name_);
void fINIT_WaveWings (void);

/* Input Channel Functions */

int fPULSE_WaveWings (unsigned char name_)
{
	switch (name_)
	{
		/***  INPULSE NEXT  ***/
	case O8_Still:		/***  PULSE CAST from PROCESS WingController  ***/
		switch (MODTAB_WaveWings[status_Initialize.read_access_.STATE -1])
		{
		case 2:  /* MODE ClosedLoop */
			switch (status_WaveWings.read_access_.STATE)
			{
			case 1:  /* STATE Down */
				status_WaveWings.write_access_.STATE = 3;  /* STATE Up */
				fPULSE_WingLeft (O3_UP);
				fPULSE_WingRight (O3_UP);
				fPULSE_WingController (O3_UP);
				break;
			case 3:  /* STATE Up */
				status_WaveWings.write_access_.STATE = 1;  /* STATE Down */
				fPULSE_WingLeft (O3_DOWN);
				fPULSE_WingRight (O3_DOWN);
				fPULSE_WingController (O3_DOWN);
				break;
			default: 
				break;
			}
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE OFF  ***/
	case O7_WAIT:		/***  PULSE CAST from PROCESS Controller  ***/
	case O7_WAKEUP:
	case O4_PLAY:		/***  PULSE CAST from PROCESS Initialize  ***/
		switch (MODTAB_WaveWings[status_Initialize.read_access_.STATE -1])
		{
		case 2:  /* MODE ClosedLoop */
			switch (status_WaveWings.read_access_.STATE)
			{
			case 1:  /* STATE Down */
				status_WaveWings.write_access_.STATE = 2;  /* STATE Off */
				fPULSE_WingLeft (O3_NEUTRAL);
				fPULSE_WingRight (O3_NEUTRAL);
				break;
			case 3:  /* STATE Up */
				status_WaveWings.write_access_.STATE = 2;  /* STATE Off */
				fPULSE_WingLeft (O3_NEUTRAL);
				fPULSE_WingRight (O3_NEUTRAL);
				break;
			default: 
				break;
			}
			break;
		case 1:  /* MODE normal */
			switch (status_WaveWings.read_access_.STATE)
			{
			case 1:  /* STATE Down */
				status_WaveWings.write_access_.STATE = 2;  /* STATE Off */
				fSTOPTIM_mBoesewicht (&IO_WaveWings.timer_, 
					&IO_WaveWings.timeup_);
				fPULSE_WingLeft (O3_NEUTRAL);
				fPULSE_WingRight (O3_NEUTRAL);
				break;
			case 3:  /* STATE Up */
				status_WaveWings.write_access_.STATE = 2;  /* STATE Off */
				fSTOPTIM_mBoesewicht (&IO_WaveWings.timer_, 
					&IO_WaveWings.timeup_);
				fPULSE_WingLeft (O3_NEUTRAL);
				fPULSE_WingRight (O3_NEUTRAL);
				break;
			default: 
				break;
			}
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE ON  ***/
	case O7_PLAY:		/***  PULSE CAST from PROCESS Controller  ***/
	case O4_WAVE:		/***  PULSE CAST from PROCESS Initialize  ***/
		switch (MODTAB_WaveWings[status_Initialize.read_access_.STATE -1])
		{
		case 2:  /* MODE ClosedLoop */
			switch (status_WaveWings.read_access_.STATE)
			{
			case 2:  /* STATE Off */
				status_WaveWings.write_access_.STATE = 3;  /* STATE Up */
				fPULSE_WingLeft (O3_UP);
				fPULSE_WingRight (O3_UP);
				fPULSE_WingController (O3_UP);
				break;
			default: 
				break;
			}
			break;
		case 1:  /* MODE normal */
			switch (status_WaveWings.read_access_.STATE)
			{
			case 2:  /* STATE Off */
				{
					delay_ =  10;	/***  DELAY WaveDelay  ***/
					status_WaveWings.write_access_.STATE = 3;  /* STATE Up */
					fSETTIM_mBoesewicht (&delay_, 
						&IO_WaveWings.timer_, 
						&IO_WaveWings.timeup_);
					fPULSE_WingLeft (O3_UP);
					fPULSE_WingRight (O3_UP);
					fPULSE_WingController (O3_UP);
				}
				break;
			default: 
				break;
			}
			break;
		default: 
			break;
		}
		break;
	default: 
		return 0;
	}
	return 1;
}

/* Timer Functions */

static void fTICK_WaveWings (void)
{
	if (IO_WaveWings.timer_.set_ && 
		IO_WaveWings.timer_.end_ == time_mBoesewicht)
	{
		IO_WaveWings.timer_.set_ = FALSE;
		--TIMING_mBoesewicht[1].set_;
		if (tuhead_mBoesewicht != &IO_WaveWings.timeup_ && 
			!IO_WaveWings.timeup_.preced_ && 
			!IO_WaveWings.timeup_.next_)
		{
			if (! tuhead_mBoesewicht)
				tuhead_mBoesewicht = tutail_mBoesewicht = &IO_WaveWings.timeup_;
			else 
			{
				tutail_mBoesewicht->next_ = &IO_WaveWings.timeup_;
				IO_WaveWings.timeup_.preced_ = tutail_mBoesewicht;
				tutail_mBoesewicht = &IO_WaveWings.timeup_;
			}
		}
	}
}

static void fTUHNDL_WaveWings (void)
{
	struct tTMQE_mBoesewicht *element_ = tuhead_mBoesewicht;
	if (tuhead_mBoesewicht == tutail_mBoesewicht)
		tuhead_mBoesewicht = tutail_mBoesewicht = 0;
	else 
	{
		tuhead_mBoesewicht = element_->next_;
		element_->next_ = 0;
		tuhead_mBoesewicht->preced_ = 0;
	}
	switch (MODTAB_WaveWings[status_Initialize.read_access_.STATE -1])
	{
	case 1:  /* MODE normal */
		switch (status_WaveWings.read_access_.STATE)
		{
		case 1:  /* STATE Down */
			{
				delay_ =  10;	/***  DELAY WaveDelay  ***/
				status_WaveWings.write_access_.STATE = 3;  /* STATE Up */
				fSETTIM_mBoesewicht (&delay_, 
					&IO_WaveWings.timer_, 
					&IO_WaveWings.timeup_);
				fPULSE_WingLeft (O3_UP);
				fPULSE_WingRight (O3_UP);
				fPULSE_WingController (O3_UP);
			}
			break;
		case 3:  /* STATE Up */
			{
				delay_ =  10;	/***  DELAY WaveDelay  ***/
				status_WaveWings.write_access_.STATE = 1;  /* STATE Down */
				fSETTIM_mBoesewicht (&delay_, 
					&IO_WaveWings.timer_, 
					&IO_WaveWings.timeup_);
				fPULSE_WingLeft (O3_DOWN);
				fPULSE_WingRight (O3_DOWN);
				fPULSE_WingController (O3_DOWN);
			}
			break;
		default: 
			break;
		}
		break;
	default: 
		break;
	}
	fUPDATE_Robot ();
}

/* Process Initialization Function */

void fINIT_WaveWings (void)
{
	status_WaveWings.write_access_.STATE = 2;  /* STATE Off */
	IO_WaveWings.timer_.set_ = FALSE;
	IO_WaveWings.timeup_.preced_ = 0;
	IO_WaveWings.timeup_.next_ = 0;
	IO_WaveWings.timeup_.proctype_ = 1;
	TIMING_mBoesewicht[1].tkhndl_ = fTICK_WaveWings;
	TIMING_mBoesewicht[1].tuhndl_ = fTUHNDL_WaveWings;
}

/*********************************************************************
	End of Module for PROCESS WaveWings
*********************************************************************/
