
/*********************************************************************
	SYSTEM Boesewicht
	Module for PROCESS WingController
	Filename: WingController.c
	generated by CIP Tool(R) Version 4.41.00
		September 19, 2012  12:35:52 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mBoesewicht.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define SELF status_WingController.write_access_
#define STATUS status_WingController.read_access_
#define TIME time_mBoesewicht

/* Process Definitions */

/* MODES */
#define normal 1

/* STATES */
#define Moving 1
#define Still 2


/* INPULSES */
#define IP_Move 1


/* OUTPULSES */

#define O7_PLAY 8
#define O7_WAIT 9
#define O7_WAKEUP 7
#define O4_OPEN_EYES 4
#define O4_PLAY 5
#define O4_WAVE 3
#define O3_DOWN 2
#define O3_NEUTRAL 6
#define O3_UP 1
#define O8_Still 10

/* External Declarations */

extern unsigned long time_mBoesewicht;
extern union tCHNOUT_mBoesewicht CHNOUT_mBoesewicht;

void fUPDATE_Robot (void);
int fPULSE_WaveWings (unsigned char name_);

/* Global Declarations */

union tSTATUS_WingController status_WingController;

/* Function Prototypes */

void fICHAN_WingControllerInC (unsigned char name_);
int fPULSE_WingController (unsigned char name_);
void fINIT_WingController (void);

/* Input Channel Functions */

void fICHAN_WingControllerInC (unsigned char name_)
{
	switch (name_)
	{
		/***  MESSAGE ReachedAxisEnd of INPORT WingControllerInport  ***/
	case C8_ReachedAxisEnd:
		switch (status_WingController.read_access_.STATE)
		{
		case 1:  /* STATE Moving */
			status_WingController.write_access_.STATE = 2;  /* STATE Still */
			fPULSE_WaveWings (O8_Still);
			break;
		default: 
			return;
		}
		break;
	default: 
		return;
	}
	fUPDATE_Robot ();
	return;
}

#undef EXCEPTION

int fPULSE_WingController (unsigned char name_)
{
	switch (name_)
	{
		/***  INPULSE Move  ***/
	case O3_DOWN:		/***  PULSE CAST from PROCESS WaveWings  ***/
	case O3_UP:
		switch (status_WingController.read_access_.STATE)
		{
		case 2:  /* STATE Still */
			status_WingController.write_access_.STATE = 1;  /* STATE Moving */
			CHNOUT_mBoesewicht.CHAN_WingControllerOutC.name_ = C7_Move;
			OUT_.WingControllerOutC (CHNOUT_mBoesewicht.CHAN_WingControllerOutC.name_);
			break;
		default: 
			break;
		}
		break;
	default: 
		return 0;
	}
	return 1;
}

/* Process Initialization Function */

void fINIT_WingController (void)
{
	status_WingController.write_access_.STATE = 2;  /* STATE Still */
}

/*********************************************************************
	End of Module for PROCESS WingController
*********************************************************************/
