
/*********************************************************************
	SYSTEM CabinetLightController
	IMPLEMENTATION Arduino
	Module for CIP SHELL sCabinetLightController
	Filename: sCabinetLightController.c
	generated by CIP Tool(R) Version 4.41.00
		July 1, 2013  12:00:06 am
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "sCabinetLightController.h"

/* Input Interface */

struct tIN_ IN_;

/* Output Interface */

struct tOUT_ OUT_;

/* Trigger Interface  */

struct tTRG_ TRG_;

/*********************************************************************
	End of Module for CIP SHELL sCabinetLightController
*********************************************************************/
