
/*********************************************************************
	SYSTEM Videobot
	IMPLEMENTATION Control
	Trace Template File for CIP MACHINE mControlUnit
	Filename: _traceControlUnit.tpl
	generated by CIP Tool(R) Version 4.41.00
		May 21, 2012  8:09:18 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/*********************************************************************
	End of Trace Template File for CIP MACHINE mControlUnit
*********************************************************************/
