
/*********************************************************************
	SYSTEM Videobot
	IMPLEMENTATION Control
	Error Interface Module for CIP MACHINE mControlUnit
	Filename: eControlUnit.c
	generated by CIP Tool(R) Version 4.41.00
		May 21, 2012  8:09:18 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "eControlUnit.h"

/*********************************************************************
	End of Error Interface Module for CIP MACHINE mControlUnit
*********************************************************************/
