
/*********************************************************************
	SYSTEM Videobot
	IMPLEMENTATION Control
	Module for CIP MACHINE mControlUnit
	Filename: mControlUnit.c
	generated by CIP Tool(R) Version 4.41.00
		May 21, 2012  8:09:18 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mControlUnit.h"

/* External Declarations */

void fICHAN_PlayerEvents (unsigned char name_);
void fINIT_PlayerMode (void);

/* Global Declarations */

unsigned long time_mControlUnit = 0;
union tCHNOUT_mControlUnit CHNOUT_mControlUnit;

/* Function Prototypes */

void fSTEP_mControlUnit(void);
void fCHAIN_mControlUnit(void);
void fTIMEUP_mControlUnit(void);
void fREAD_mControlUnit(void);

/* AUTO_ Handler Function */

static void fAUTOHDL_mControlUnit(void)
{
		/* dummy function handling no AUTO_ */
}

/* Timer Functions */

static void fTICK_mControlUnit(void)
{
	time_mControlUnit ++;
}

/* Control Functions */

	/* Step Function for CIP Machine */

void fSTEP_mControlUnit(void)
{
	return;
}

	/* Chain Function for CIP Machine */

void fCHAIN_mControlUnit(void)
{
	return;
}

	/* Timeup Function for CIP Machine */

void fTIMEUP_mControlUnit(void)
{
	return;
}

	/* Read Function for CIP Machine */

void fREAD_mControlUnit(void)
{
	return;
}

/* Initialization Function */

int fINIT_(void)
{
	TRG_.TICK_ = fTICK_mControlUnit;
	TRG_.CHAIN_ = fCHAIN_mControlUnit;
	TRG_.TIMEUP_ = fTIMEUP_mControlUnit;
	TRG_.STEP_ = fSTEP_mControlUnit;
	TRG_.READ_ = fREAD_mControlUnit;
	TRG_.AUTO_ = fAUTOHDL_mControlUnit;
	IN_.PlayerEvents = fICHAN_PlayerEvents;
	iCHAN_();
	if (!OUT_.PlayerActions)
		return 0;
	fINIT_PlayerMode ();
	return 1;
}

/*********************************************************************
	End of Module for CIP MACHINE mControlUnit
*********************************************************************/
