
/*********************************************************************
	SYSTEM Videobot
	IMPLEMENTATION Control
	Trace Interface Module for CIP MACHINE mControlUnit
	Filename: tControlUnit.c
	generated by CIP Tool(R) Version 4.41.00
		May 21, 2012  8:09:18 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "tControlUnit.h"

/*********************************************************************
	End of Trace Interface Module for CIP MACHINE mControlUnit
*********************************************************************/
