
/*********************************************************************
	SYSTEM MonsterCatcher
	IMPLEMENTATION MCArduino
	CIP Connector Template Module for CIP SHELL sMCUNit
	Filename: _conMCUNit.tpl
	generated by CIP Tool(R) Version 4.41.00
		August 23, 2012  9:16:05 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "sMCUNit.h"


/*********************************************************************
	User defined Output Channel Functions
*********************************************************************/

/* Output Channel Functions,
	called by CIP Machine when a Message is written.
	User defined function, with name to consider as suggestion */

/* Parameters
	name_		name value of message */

void uCHAN_CatcherChannel (unsigned char name_)
{
	/* Accessing MESSAGE */
	switch (name_)
	{
	case C2_BACK_TO_FRONT:
		/* user defined code */
		break;
	case C2_CENTER:
		/* user defined code */
		break;
	case C2_FRONT:
		/* user defined code */
		break;
	case C2_FRONT_TO_BACK:
		/* user defined code */
		break;
	default: 
		break;
	}
}

void uCHAN_DriveChannel (unsigned char name_)
{
	/* Accessing MESSAGE */
	switch (name_)
	{
	case C1_BACKWARD:
		/* user defined code */
		break;
	case C1_BWD_LEFT:
		/* user defined code */
		break;
	case C1_BWD_RIGHT:
		/* user defined code */
		break;
	case C1_FORWARD:
		/* user defined code */
		break;
	case C1_FWD_LEFT:
		/* user defined code */
		break;
	case C1_FWD_RIGHT:
		/* user defined code */
		break;
	case C1_LEFT:
		/* user defined code */
		break;
	case C1_RIGHT:
		/* user defined code */
		break;
	default: 
		break;
	}
}


/*********************************************************************
	User defined Output Channel Interface Initialization Function
*********************************************************************/

void iCHAN_(void)
{
		/* Initializing Input Error Function only if Input Error Option set */

	#ifdef _EINPUT__
		IN_.EINPUT_ = uEINPUT_;
	#endif 

		/* Initializing Output Interface */

	OUT_.CatcherChannel = uCHAN_CatcherChannel;
	OUT_.DriveChannel = uCHAN_DriveChannel;
}


/*********************************************************************
	Execution of CIP Connector Activities
*********************************************************************/

	/* Initializing CIP Machine */

if (fINIT_())
{
	/* activation of drive loop */
}
else 
{
	/* initialization failed, abort drive */
}


/* Input Function Calls */

	/* Referenced Input Variables (examples) */

unsigned char name_BedDetectorChannel;
unsigned char name_ObstacleDetection;
unsigned char name_WanderChannel;

	/* Calling Input Functions */

IN_.BedDetectorChannel(name_BedDetectorChannel);
IN_.ObstacleDetection(name_ObstacleDetection);
IN_.WanderChannel(name_WanderChannel);


/* Trigger Function Calls */

TRG_.TICK_();		/* increment CIP Machine time by one Tick */

if (TRG_.PENDING_.ANY_)
	TRG_.STEP_();		/* perform one step, if any transition (in priority order chain, timeup, local message, auto) is pending */

if (TRG_.PENDING_.CHAIN_)
	TRG_.CHAIN_();		/* perform one chain, if any chain is pending */

if (TRG_.PENDING_.TIMEUP_)
	TRG_.TIMEUP_();		/* perform one timeup, if any timeup is pending  */

if (TRG_.PENDING_.READ_)
	TRG_.READ_();		/* perform one local read, if any local message is buffered */

if (TRG_.PENDING_.AUTO_)
	TRG_.AUTO_();		/* perform one auto, if any auto is pending */

/*********************************************************************
	End of CIP Connector Template Module for CIP SHELL sMCUNit
*********************************************************************/
