
/*********************************************************************
	SYSTEM MonsterCatcher
	IMPLEMENTATION MCArduino
	Trace Template File for CIP MACHINE mMCUNit
	Filename: _traceMCUNit.tpl
	generated by CIP Tool(R) Version 4.41.00
		August 23, 2012  9:16:07 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/*********************************************************************
	End of Trace Template File for CIP MACHINE mMCUNit
*********************************************************************/
