
/*********************************************************************
	SYSTEM MonsterCatcher
	Module for PROCESS Avoid
	Filename: Avoid.c
	generated by CIP Tool(R) Version 4.41.00
		August 23, 2012  9:16:07 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mMCUNit.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define SELF status_Avoid.write_access_
#define STATUS status_Avoid.read_access_
#define TIME time_mMCUNit

/* Process Definitions */

/* MODES */
#define normal 1

/* STATES */
#define Backward 1
#define On 2
#define TurnAround 3


/* INPULSES */
#define TIMEUP_ 1
#define IP_BUMP_PULSE 2


/* OUTPULSES */

#define O5_AVOIDED 4
#define O5_BACKWARD 5
#define O5_BWD_LEFT 6
#define O6_BED 11
#define O6_NO_BED 10
#define O4_FORWARD 3
#define O4_LEFT 1
#define O4_RIGHT 2
#define O7_DONE 8
#define O7_TURN 9
#define O3_RUN 7

/* External Declarations */

extern unsigned long time_mMCUNit;
extern struct tTMQE_mMCUNit *tuhead_mMCUNit, *tutail_mMCUNit;
extern union tCHNOUT_mMCUNit CHNOUT_mMCUNit;
extern struct tTIMING_mMCUNit TIMING_mMCUNit[4];

void fUPDATE_Body (void);
int fPULSE_Drive (unsigned char name_);
int fPULSE_Wander (unsigned char name_);
void fSETTIM_mMCUNit (unsigned long *delay_, struct tTMEL_mMCUNit *timer_, struct tTMQE_mMCUNit *timeup_);
void fSTOPTIM_mMCUNit (struct tTMEL_mMCUNit *timer_, struct tTMQE_mMCUNit *timeup_);

/* Global Declarations */

static unsigned long delay_;
struct tPRINST_Avoid IO_Avoid;
union tSTATUS_Avoid status_Avoid;

/* Function Prototypes */

void fICHAN_ObstacleDetection (unsigned char name_);
int fPULSE_Avoid (unsigned char name_);
void fINIT_Avoid (void);

/* Input Channel Functions */

void fICHAN_ObstacleDetection (unsigned char name_)
{
	switch (name_)
	{
		/***  MESSAGE BUMP of INPORT AVOID  ***/
	case C3_BUMP:
		switch (status_Avoid.read_access_.STATE)
		{
		case 2:  /* STATE On */
			{
				delay_ =  200;	/***  DELAY BACKWARD_DELAY  ***/
				status_Avoid.write_access_.STATE = 1;  /* STATE Backward */
				fSETTIM_mMCUNit (&delay_, 
					&IO_Avoid.timer_, 
					&IO_Avoid.timeup_);
				fPULSE_Drive (O5_BACKWARD);
			}
			break;
		default: 
			return;
		}
		break;
	default: 
		return;
	}
	fUPDATE_Body ();
	return;
}

#undef EXCEPTION

int fPULSE_Avoid (unsigned char name_)
{
	switch (name_)
	{
	default: 
		return 0;
	}
	return 1;
}

/* Timer Functions */

static void fTICK_Avoid (void)
{
	if (IO_Avoid.timer_.set_ && 
		IO_Avoid.timer_.end_ == time_mMCUNit)
	{
		IO_Avoid.timer_.set_ = FALSE;
		--TIMING_mMCUNit[0].set_;
		if (tuhead_mMCUNit != &IO_Avoid.timeup_ && 
			!IO_Avoid.timeup_.preced_ && 
			!IO_Avoid.timeup_.next_)
		{
			if (! tuhead_mMCUNit)
				tuhead_mMCUNit = tutail_mMCUNit = &IO_Avoid.timeup_;
			else 
			{
				tutail_mMCUNit->next_ = &IO_Avoid.timeup_;
				IO_Avoid.timeup_.preced_ = tutail_mMCUNit;
				tutail_mMCUNit = &IO_Avoid.timeup_;
			}
		}
	}
}

static void fTUHNDL_Avoid (void)
{
	struct tTMQE_mMCUNit *element_ = tuhead_mMCUNit;
	if (tuhead_mMCUNit == tutail_mMCUNit)
		tuhead_mMCUNit = tutail_mMCUNit = 0;
	else 
	{
		tuhead_mMCUNit = element_->next_;
		element_->next_ = 0;
		tuhead_mMCUNit->preced_ = 0;
	}
	switch (status_Avoid.read_access_.STATE)
	{
	case 1:  /* STATE Backward */
		{
			delay_ =  100;	/***  DELAY TURN_DELAY  ***/
			status_Avoid.write_access_.STATE = 3;  /* STATE TurnAround */
			fSETTIM_mMCUNit (&delay_, 
				&IO_Avoid.timer_, 
				&IO_Avoid.timeup_);
			fPULSE_Drive (O5_BWD_LEFT);
		}
		break;
	case 3:  /* STATE TurnAround */
		status_Avoid.write_access_.STATE = 2;  /* STATE On */
		fPULSE_Wander (O5_AVOIDED);
		break;
	default: 
		break;
	}
	fUPDATE_Body ();
}

/* Process Initialization Function */

void fINIT_Avoid (void)
{
	status_Avoid.write_access_.STATE = 2;  /* STATE On */
	IO_Avoid.timer_.set_ = FALSE;
	IO_Avoid.timeup_.preced_ = 0;
	IO_Avoid.timeup_.next_ = 0;
	IO_Avoid.timeup_.proctype_ = 0;
	TIMING_mMCUNit[0].tkhndl_ = fTICK_Avoid;
	TIMING_mMCUNit[0].tuhndl_ = fTUHNDL_Avoid;
}

/*********************************************************************
	End of Module for PROCESS Avoid
*********************************************************************/
