
/*********************************************************************
	SYSTEM MonsterCatcher
	Module for PROCESS Catcher
	Filename: Catcher.c
	generated by CIP Tool(R) Version 4.41.00
		August 23, 2012  9:16:07 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mMCUNit.h"

/* Process Macro Definitions */

#define SELF status_Catcher.write_access_
#define STATUS status_Catcher.read_access_
#define TIME time_mMCUNit

/* Process Definitions */

/* MODES */
#define normal 1

/* STATES */
#define Back 1
#define Front 2
#define Off 3


/* INPULSES */
#define IP_FRONT 1
#define IP_BACK 2
#define IP_STOP 3
#define TIMEUP_ 4
#define IP_START 5


/* OUTPULSES */

#define O5_AVOIDED 4
#define O5_BACKWARD 5
#define O5_BWD_LEFT 6
#define O6_BED 11
#define O6_NO_BED 10
#define O4_FORWARD 3
#define O4_LEFT 1
#define O4_RIGHT 2
#define O7_DONE 8
#define O7_TURN 9
#define O3_RUN 7

/* External Declarations */

extern unsigned long time_mMCUNit;
extern struct tTMQE_mMCUNit *tuhead_mMCUNit, *tutail_mMCUNit;
extern union tCHNOUT_mMCUNit CHNOUT_mMCUNit;
extern struct tTIMING_mMCUNit TIMING_mMCUNit[4];

void fUPDATE_Body (void);
void fSETTIM_mMCUNit (unsigned long *delay_, struct tTMEL_mMCUNit *timer_, struct tTMQE_mMCUNit *timeup_);
void fSTOPTIM_mMCUNit (struct tTMEL_mMCUNit *timer_, struct tTMQE_mMCUNit *timeup_);

/* Global Declarations */

static unsigned long delay_;
struct tPRINST_Catcher IO_Catcher;
union tSTATUS_Catcher status_Catcher;

/* Function Prototypes */

int fPULSE_Catcher (unsigned char name_);
void fINIT_Catcher (void);

/* Input Channel Functions */

int fPULSE_Catcher (unsigned char name_)
{
	switch (name_)
	{
		/***  INPULSE START  ***/
	case O6_BED:		/***  PULSE CAST from PROCESS BedDetector  ***/
		switch (status_Catcher.read_access_.STATE)
		{
		case 3:  /* STATE Off */
			{
				delay_ =  20;	/***  DELAY CATCHER_HALF_DELAY  ***/
				status_Catcher.write_access_.STATE = 2;  /* STATE Front */
				CHNOUT_mMCUNit.CHAN_CatcherChannel.name_ = C2_FRONT;
				OUT_.CatcherChannel (CHNOUT_mMCUNit.CHAN_CatcherChannel.name_);
				fSETTIM_mMCUNit (&delay_, 
					&IO_Catcher.timer_, 
					&IO_Catcher.timeup_);
			}
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE STOP  ***/
	case O6_NO_BED:		/***  PULSE CAST from PROCESS BedDetector  ***/
		switch (status_Catcher.read_access_.STATE)
		{
		case 1:  /* STATE Back */
			status_Catcher.write_access_.STATE = 3;  /* STATE Off */
			CHNOUT_mMCUNit.CHAN_CatcherChannel.name_ = C2_CENTER;
			OUT_.CatcherChannel (CHNOUT_mMCUNit.CHAN_CatcherChannel.name_);
			break;
		case 2:  /* STATE Front */
			status_Catcher.write_access_.STATE = 3;  /* STATE Off */
			CHNOUT_mMCUNit.CHAN_CatcherChannel.name_ = C2_CENTER;
			OUT_.CatcherChannel (CHNOUT_mMCUNit.CHAN_CatcherChannel.name_);
			break;
		default: 
			break;
		}
		break;
	default: 
		return 0;
	}
	return 1;
}

/* Timer Functions */

static void fTICK_Catcher (void)
{
	if (IO_Catcher.timer_.set_ && 
		IO_Catcher.timer_.end_ == time_mMCUNit)
	{
		IO_Catcher.timer_.set_ = FALSE;
		--TIMING_mMCUNit[1].set_;
		if (tuhead_mMCUNit != &IO_Catcher.timeup_ && 
			!IO_Catcher.timeup_.preced_ && 
			!IO_Catcher.timeup_.next_)
		{
			if (! tuhead_mMCUNit)
				tuhead_mMCUNit = tutail_mMCUNit = &IO_Catcher.timeup_;
			else 
			{
				tutail_mMCUNit->next_ = &IO_Catcher.timeup_;
				IO_Catcher.timeup_.preced_ = tutail_mMCUNit;
				tutail_mMCUNit = &IO_Catcher.timeup_;
			}
		}
	}
}

static void fTUHNDL_Catcher (void)
{
	struct tTMQE_mMCUNit *element_ = tuhead_mMCUNit;
	if (tuhead_mMCUNit == tutail_mMCUNit)
		tuhead_mMCUNit = tutail_mMCUNit = 0;
	else 
	{
		tuhead_mMCUNit = element_->next_;
		element_->next_ = 0;
		tuhead_mMCUNit->preced_ = 0;
	}
	switch (status_Catcher.read_access_.STATE)
	{
	case 1:  /* STATE Back */
		{
			delay_ =  40;	/***  DELAY CATCHER_FULL_DELAY  ***/
			status_Catcher.write_access_.STATE = 2;  /* STATE Front */
			CHNOUT_mMCUNit.CHAN_CatcherChannel.name_ = C2_BACK_TO_FRONT;
			OUT_.CatcherChannel (CHNOUT_mMCUNit.CHAN_CatcherChannel.name_);
			fSETTIM_mMCUNit (&delay_, 
				&IO_Catcher.timer_, 
				&IO_Catcher.timeup_);
		}
		break;
	case 2:  /* STATE Front */
		{
			delay_ =  40;	/***  DELAY CATCHER_FULL_DELAY  ***/
			status_Catcher.write_access_.STATE = 1;  /* STATE Back */
			CHNOUT_mMCUNit.CHAN_CatcherChannel.name_ = C2_FRONT_TO_BACK;
			OUT_.CatcherChannel (CHNOUT_mMCUNit.CHAN_CatcherChannel.name_);
			fSETTIM_mMCUNit (&delay_, 
				&IO_Catcher.timer_, 
				&IO_Catcher.timeup_);
		}
		break;
	default: 
		break;
	}
	fUPDATE_Body ();
}

/* Process Initialization Function */

void fINIT_Catcher (void)
{
	status_Catcher.write_access_.STATE = 3;  /* STATE Off */
	IO_Catcher.timer_.set_ = FALSE;
	IO_Catcher.timeup_.preced_ = 0;
	IO_Catcher.timeup_.next_ = 0;
	IO_Catcher.timeup_.proctype_ = 1;
	TIMING_mMCUNit[1].tkhndl_ = fTICK_Catcher;
	TIMING_mMCUNit[1].tuhndl_ = fTUHNDL_Catcher;
}

/*********************************************************************
	End of Module for PROCESS Catcher
*********************************************************************/
