
/*********************************************************************
	SYSTEM MonsterCatcher
	Module for PROCESS Drive
	Filename: Drive.c
	generated by CIP Tool(R) Version 4.41.00
		August 23, 2012  9:16:07 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mMCUNit.h"

/* Process Macro Definitions */

#define SELF status_Drive.write_access_
#define STATUS status_Drive.read_access_
#define TIME time_mMCUNit

/* Process Definitions */

/* MODES */
#define normal 1

/* STATES */
#define On 1


/* INPULSES */
#define IP_LEFT 1
#define IP_RIGHT 2
#define IP_BACKWARD 3
#define IP_FORWARD 4
#define IP_BWD_LEFT 5
#define IP_FWD_RIGHT 6
#define IP_FWD_LEFT 7


/* OUTPULSES */

#define O5_AVOIDED 4
#define O5_BACKWARD 5
#define O5_BWD_LEFT 6
#define O6_BED 11
#define O6_NO_BED 10
#define O4_FORWARD 3
#define O4_LEFT 1
#define O4_RIGHT 2
#define O7_DONE 8
#define O7_TURN 9
#define O3_RUN 7

/* External Declarations */

extern unsigned long time_mMCUNit;
extern union tCHNOUT_mMCUNit CHNOUT_mMCUNit;

void fUPDATE_Body (void);

/* Global Declarations */

union tSTATUS_Drive status_Drive;

/* Function Prototypes */

int fPULSE_Drive (unsigned char name_);
void fINIT_Drive (void);

/* Input Channel Functions */

int fPULSE_Drive (unsigned char name_)
{
	switch (name_)
	{
		/***  INPULSE BACKWARD  ***/
	case O5_BACKWARD:		/***  PULSE CAST from PROCESS Avoid  ***/
		switch (status_Drive.read_access_.STATE)
		{
		case 1:  /* STATE On */
			status_Drive.write_access_.STATE = 1;  /* STATE On */
			CHNOUT_mMCUNit.CHAN_DriveChannel.name_ = C1_BACKWARD;
			OUT_.DriveChannel (CHNOUT_mMCUNit.CHAN_DriveChannel.name_);
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE BWD_LEFT  ***/
	case O5_BWD_LEFT:		/***  PULSE CAST from PROCESS Avoid  ***/
		switch (status_Drive.read_access_.STATE)
		{
		case 1:  /* STATE On */
			status_Drive.write_access_.STATE = 1;  /* STATE On */
			CHNOUT_mMCUNit.CHAN_DriveChannel.name_ = C1_BWD_LEFT;
			OUT_.DriveChannel (CHNOUT_mMCUNit.CHAN_DriveChannel.name_);
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE FORWARD  ***/
	case O4_FORWARD:		/***  PULSE CAST from PROCESS DrunkDrive  ***/
		switch (status_Drive.read_access_.STATE)
		{
		case 1:  /* STATE On */
			status_Drive.write_access_.STATE = 1;  /* STATE On */
			CHNOUT_mMCUNit.CHAN_DriveChannel.name_ = C1_FORWARD;
			OUT_.DriveChannel (CHNOUT_mMCUNit.CHAN_DriveChannel.name_);
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE FWD_LEFT  ***/
	case O4_LEFT:		/***  PULSE CAST from PROCESS DrunkDrive  ***/
		switch (status_Drive.read_access_.STATE)
		{
		case 1:  /* STATE On */
			status_Drive.write_access_.STATE = 1;  /* STATE On */
			CHNOUT_mMCUNit.CHAN_DriveChannel.name_ = C1_FWD_LEFT;
			OUT_.DriveChannel (CHNOUT_mMCUNit.CHAN_DriveChannel.name_);
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE FWD_RIGHT  ***/
	case O4_RIGHT:		/***  PULSE CAST from PROCESS DrunkDrive  ***/
		switch (status_Drive.read_access_.STATE)
		{
		case 1:  /* STATE On */
			status_Drive.write_access_.STATE = 1;  /* STATE On */
			CHNOUT_mMCUNit.CHAN_DriveChannel.name_ = C1_FWD_RIGHT;
			OUT_.DriveChannel (CHNOUT_mMCUNit.CHAN_DriveChannel.name_);
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE LEFT  ---  untranslated  ***/

		/***  INPULSE RIGHT  ***/
	case O7_TURN:		/***  PULSE CAST from PROCESS Finder  ***/
		switch (status_Drive.read_access_.STATE)
		{
		case 1:  /* STATE On */
			status_Drive.write_access_.STATE = 1;  /* STATE On */
			CHNOUT_mMCUNit.CHAN_DriveChannel.name_ = C1_RIGHT;
			OUT_.DriveChannel (CHNOUT_mMCUNit.CHAN_DriveChannel.name_);
			break;
		default: 
			break;
		}
		break;
	default: 
		return 0;
	}
	return 1;
}

/* Process Initialization Function */

void fINIT_Drive (void)
{
	status_Drive.write_access_.STATE = 1;  /* STATE On */
}

/*********************************************************************
	End of Module for PROCESS Drive
*********************************************************************/
