
/*********************************************************************
	SYSTEM MonsterCatcher
	Module for PROCESS DrunkDrive
	Filename: DrunkDrive.c
	generated by CIP Tool(R) Version 4.41.00
		August 23, 2012  9:16:07 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mMCUNit.h"

/* Process Macro Definitions */

#define SELF status_DrunkDrive.write_access_
#define STATUS status_DrunkDrive.read_access_
#define TIME time_mMCUNit

/* Process Definitions */

/* MODES */
#define normal 1

/* STATES */
#define Center 1
#define Left 2
#define Right 3


/* INPULSES */
#define IP_DRUNK 1
#define TIMEUP_ 2
#define IP_STRAIGHT 3


/* OUTPULSES */

#define O5_AVOIDED 4
#define O5_BACKWARD 5
#define O5_BWD_LEFT 6
#define O6_BED 11
#define O6_NO_BED 10
#define O4_FORWARD 3
#define O4_LEFT 1
#define O4_RIGHT 2
#define O7_DONE 8
#define O7_TURN 9
#define O3_RUN 7

/* External Declarations */

extern unsigned long time_mMCUNit;
extern struct tTMQE_mMCUNit *tuhead_mMCUNit, *tutail_mMCUNit;
extern union tCHNOUT_mMCUNit CHNOUT_mMCUNit;
extern struct tTIMING_mMCUNit TIMING_mMCUNit[4];

void fUPDATE_Body (void);
int fPULSE_Drive (unsigned char name_);
void fSETTIM_mMCUNit (unsigned long *delay_, struct tTMEL_mMCUNit *timer_, struct tTMQE_mMCUNit *timeup_);
void fSTOPTIM_mMCUNit (struct tTMEL_mMCUNit *timer_, struct tTMQE_mMCUNit *timeup_);

/* Global Declarations */

static unsigned long delay_;
struct tPRINST_DrunkDrive IO_DrunkDrive;
union tSTATUS_DrunkDrive status_DrunkDrive;

/* Function Prototypes */

int fPULSE_DrunkDrive (unsigned char name_);
void fINIT_DrunkDrive (void);

/* Input Channel Functions */

int fPULSE_DrunkDrive (unsigned char name_)
{
	switch (name_)
	{
		/***  INPULSE DRUNK  ***/
	case O6_BED:		/***  PULSE CAST from PROCESS BedDetector  ***/
		switch (status_DrunkDrive.read_access_.STATE)
		{
		case 1:  /* STATE Center */
			{
				delay_ =  30;	/***  DELAY DRUNK_DELAY  ***/
				status_DrunkDrive.write_access_.STATE = 2;  /* STATE Left */
				fSETTIM_mMCUNit (&delay_, 
					&IO_DrunkDrive.timer_, 
					&IO_DrunkDrive.timeup_);
				fPULSE_Drive (O4_LEFT);
			}
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE STRAIGHT  ***/
	case O3_RUN:		/***  PULSE CAST from PROCESS Wander  ***/
		switch (status_DrunkDrive.read_access_.STATE)
		{
		case 1:  /* STATE Center */
			status_DrunkDrive.write_access_.STATE = 1;  /* STATE Center */
			fPULSE_Drive (O4_FORWARD);
			break;
		case 2:  /* STATE Left */
			status_DrunkDrive.write_access_.STATE = 1;  /* STATE Center */
			fPULSE_Drive (O4_FORWARD);
			break;
		case 3:  /* STATE Right */
			status_DrunkDrive.write_access_.STATE = 1;  /* STATE Center */
			fPULSE_Drive (O4_FORWARD);
			break;
		default: 
			break;
		}
		break;
	default: 
		return 0;
	}
	return 1;
}

/* Timer Functions */

static void fTICK_DrunkDrive (void)
{
	if (IO_DrunkDrive.timer_.set_ && 
		IO_DrunkDrive.timer_.end_ == time_mMCUNit)
	{
		IO_DrunkDrive.timer_.set_ = FALSE;
		--TIMING_mMCUNit[2].set_;
		if (tuhead_mMCUNit != &IO_DrunkDrive.timeup_ && 
			!IO_DrunkDrive.timeup_.preced_ && 
			!IO_DrunkDrive.timeup_.next_)
		{
			if (! tuhead_mMCUNit)
				tuhead_mMCUNit = tutail_mMCUNit = &IO_DrunkDrive.timeup_;
			else 
			{
				tutail_mMCUNit->next_ = &IO_DrunkDrive.timeup_;
				IO_DrunkDrive.timeup_.preced_ = tutail_mMCUNit;
				tutail_mMCUNit = &IO_DrunkDrive.timeup_;
			}
		}
	}
}

static void fTUHNDL_DrunkDrive (void)
{
	struct tTMQE_mMCUNit *element_ = tuhead_mMCUNit;
	if (tuhead_mMCUNit == tutail_mMCUNit)
		tuhead_mMCUNit = tutail_mMCUNit = 0;
	else 
	{
		tuhead_mMCUNit = element_->next_;
		element_->next_ = 0;
		tuhead_mMCUNit->preced_ = 0;
	}
	switch (status_DrunkDrive.read_access_.STATE)
	{
	case 2:  /* STATE Left */
		{
			delay_ =  30;	/***  DELAY DRUNK_DELAY  ***/
			status_DrunkDrive.write_access_.STATE = 3;  /* STATE Right */
			fSETTIM_mMCUNit (&delay_, 
				&IO_DrunkDrive.timer_, 
				&IO_DrunkDrive.timeup_);
			fPULSE_Drive (O4_LEFT);
		}
		break;
	case 3:  /* STATE Right */
		{
			delay_ =  30;	/***  DELAY DRUNK_DELAY  ***/
			status_DrunkDrive.write_access_.STATE = 2;  /* STATE Left */
			fSETTIM_mMCUNit (&delay_, 
				&IO_DrunkDrive.timer_, 
				&IO_DrunkDrive.timeup_);
			fPULSE_Drive (O4_RIGHT);
		}
		break;
	default: 
		break;
	}
	fUPDATE_Body ();
}

/* Process Initialization Function */

void fINIT_DrunkDrive (void)
{
	status_DrunkDrive.write_access_.STATE = 1;  /* STATE Center */
	IO_DrunkDrive.timer_.set_ = FALSE;
	IO_DrunkDrive.timeup_.preced_ = 0;
	IO_DrunkDrive.timeup_.next_ = 0;
	IO_DrunkDrive.timeup_.proctype_ = 2;
	TIMING_mMCUNit[2].tkhndl_ = fTICK_DrunkDrive;
	TIMING_mMCUNit[2].tuhndl_ = fTUHNDL_DrunkDrive;
}

/*********************************************************************
	End of Module for PROCESS DrunkDrive
*********************************************************************/
