
/*********************************************************************
	SYSTEM MonsterCatcher
	IMPLEMENTATION MCArduino
	Error Interface Module for CIP MACHINE mMCUNit
	Filename: eMCUNit.c
	generated by CIP Tool(R) Version 4.41.00
		August 23, 2012  9:16:07 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "eMCUNit.h"

/*********************************************************************
	End of Error Interface Module for CIP MACHINE mMCUNit
*********************************************************************/
