
/*********************************************************************
	SYSTEM MonsterCatcher
	IMPLEMENTATION MCArduino
	Header File for CIP MACHINE mMCUNit
	Filename: mMCUNit.h
	generated by CIP Tool(R) Version 4.41.00
		August 23, 2012  9:16:07 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

#ifndef _MHEADER
#define _MHEADER

/* Include Files */

#include <stdlib.h>
#include "sMCUNit.h"

/* Macro Definitions */

#ifndef FALSE
#define FALSE 0
#endif

#ifndef TRUE
#define TRUE 1
#endif


/* Outpulse Types */

struct tOUTPLS_Avoid
{
	unsigned char  name_;
};

struct tOUTPLS_BedDetector
{
	unsigned char  name_;
};

struct tOUTPLS_DrunkDrive
{
	unsigned char  name_;
};

struct tOUTPLS_Finder
{
	unsigned char  name_;
};

struct tOUTPLS_Wander
{
	unsigned char  name_;
};

union tOUTPLS_Body
{
	struct tOUTPLS_Avoid OUTPLS_Avoid;
	struct tOUTPLS_BedDetector OUTPLS_BedDetector;
	struct tOUTPLS_DrunkDrive OUTPLS_DrunkDrive;
	struct tOUTPLS_Finder OUTPLS_Finder;
	struct tOUTPLS_Wander OUTPLS_Wander;
};

/* Global Output Type */

struct tCHAN_DriveChannel
{
	unsigned char name_;
};

struct tCHAN_CatcherChannel
{
	unsigned char name_;
};

union tCHNOUT_mMCUNit
{
	struct tCHAN_CatcherChannel CHAN_CatcherChannel;
	struct tCHAN_DriveChannel CHAN_DriveChannel;
};

/* Timer- and Queue-Element */

struct tTMEL_mMCUNit
{
	unsigned char set_; /* Boolean */
	unsigned long end_;
};

struct tTMQE_mMCUNit
{
	struct tTMQE_mMCUNit *preced_;
	struct tTMQE_mMCUNit *next_;
	int proctype_;
};

/* Global Table Elements */

struct tTIMING_mMCUNit
{
	void  (*tkhndl_) (void);
	void  (*tuhndl_) (void);
	int  set_;
};

/* Types for Process Avoid */

struct tPRSTAT_Avoid
{
	unsigned char STATE;
};

union tSTATUS_Avoid
{
	struct tPRSTAT_Avoid write_access_;
	const struct tPRSTAT_Avoid read_access_;
};

struct tPRINST_Avoid
{
	struct tTMEL_mMCUNit timer_;
	struct tTMQE_mMCUNit timeup_;
};

/* Types for Process BedDetector */

struct tPRSTAT_BedDetector
{
	unsigned char STATE;
};

union tSTATUS_BedDetector
{
	struct tPRSTAT_BedDetector write_access_;
	const struct tPRSTAT_BedDetector read_access_;
};

/* Types for Process Catcher */

struct tPRSTAT_Catcher
{
	unsigned char STATE;
};

union tSTATUS_Catcher
{
	struct tPRSTAT_Catcher write_access_;
	const struct tPRSTAT_Catcher read_access_;
};

struct tPRINST_Catcher
{
	struct tTMEL_mMCUNit timer_;
	struct tTMQE_mMCUNit timeup_;
};

/* Types for Process Drive */

struct tPRSTAT_Drive
{
	unsigned char STATE;
};

union tSTATUS_Drive
{
	struct tPRSTAT_Drive write_access_;
	const struct tPRSTAT_Drive read_access_;
};

/* Types for Process DrunkDrive */

struct tPRSTAT_DrunkDrive
{
	unsigned char STATE;
};

union tSTATUS_DrunkDrive
{
	struct tPRSTAT_DrunkDrive write_access_;
	const struct tPRSTAT_DrunkDrive read_access_;
};

struct tPRINST_DrunkDrive
{
	struct tTMEL_mMCUNit timer_;
	struct tTMQE_mMCUNit timeup_;
};

/* Types for Process Finder */

struct tPRSTAT_Finder
{
	unsigned char STATE;
};

union tSTATUS_Finder
{
	struct tPRSTAT_Finder write_access_;
	const struct tPRSTAT_Finder read_access_;
};

struct tPRINST_Finder
{
	struct tTMEL_mMCUNit timer_;
	struct tTMQE_mMCUNit timeup_;
};

/* Types for Process Wander */

struct tPRSTAT_Wander
{
	unsigned char STATE;
};

union tSTATUS_Wander
{
	struct tPRSTAT_Wander write_access_;
	const struct tPRSTAT_Wander read_access_;
};

#endif 

/*********************************************************************
	End of Header File for CIP MACHINE mMCUNit
*********************************************************************/
