
/*********************************************************************
	SYSTEM MonsterCatcher
	IMPLEMENTATION MCArduino
	Header File for CIP SHELL sMCUNit
	Filename: sMCUNit.h
	generated by CIP Tool(R) Version 4.41.00
		August 23, 2012  9:16:05 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

#ifndef _SHEADER
#define _SHEADER

/* Code Option Constants */

#ifdef _EINPUT__
	#undef _EINPUT__
#endif 

/* Channel Enumerations */

#define C_BedDetectorChannel 5
#define C_CatcherChannel 2
#define C_DriveChannel 1
#define C_ObstacleDetection 3
#define C_WanderChannel 4

/* MESSAGE Enumeration of CHANNEL DriveChannel */

#define C1_ 0
#define C1_BACKWARD 4
#define C1_BWD_LEFT 1
#define C1_BWD_RIGHT 2
#define C1_FORWARD 6
#define C1_FWD_LEFT 7
#define C1_FWD_RIGHT 8
#define C1_LEFT 5
#define C1_RIGHT 3

/* MESSAGE Enumeration of CHANNEL CatcherChannel */

#define C2_ 0
#define C2_BACK_TO_FRONT 4
#define C2_CENTER 1
#define C2_FRONT 3
#define C2_FRONT_TO_BACK 2

/* MESSAGE Enumeration of CHANNEL ObstacleDetection */

#define C3_ 0
#define C3_BUMP 1

/* MESSAGE Enumeration of CHANNEL WanderChannel */

#define C4_ 0
#define C4_START 1

/* MESSAGE Enumeration of CHANNEL BedDetectorChannel */

#define C5_ 0
#define C5_DETECT 1
#define C5_NOT_DETECT 2

/* Input Interface Type */

struct tIN_
{
	void (*BedDetectorChannel) (unsigned char);
	void (*ObstacleDetection) (unsigned char);
	void (*WanderChannel) (unsigned char);
};

/* Output Interface Type */

struct tOUT_
{
	void (*CatcherChannel) (unsigned char);
	void (*DriveChannel) (unsigned char);
};

/* Trigger Interface Type */

struct tPENDING_
{
	int ANY_;	/* boolean indicating any pending transitions */
	int CHAIN_;	/* boolean indicating pending CHAIN_ */
	int TIMEUP_;	/* boolean indicating pending TIMEUP_ */
	int READ_;	/* boolean indicating buffered internal message */
	int AUTO_;	/* boolean indicating reading AUTO_ */
};

struct tTRG_
{
	void (*TICK_) (void);		/* increment CIP MACHINE time */
	void (*STEP_) (void);		/* trigger CIP MACHINE transition */
	void (*CHAIN_) (void);		/* trigger pending chain CIP MACHINE transition */
	void (*TIMEUP_) (void);		/* trigger pending timeup CIP MACHINE transition */
	void (*READ_) (void);		/* trigger CIP MACHINE to read from internal message buffer */
	void (*AUTO_) (void);		/* trigger pending auto CIP MACHINE transition */
	struct tPENDING_ PENDING_;		/* information on pending transitions */
};

/* External Interface Declarations */

extern struct tIN_ IN_;		/* Input Channel Interface defined in sMCUNit.c */
extern struct tOUT_ OUT_;		/* Output Channel Interface defined in sMCUNit.c */
extern struct tTRG_ TRG_;		/* Trigger Interface defined in sMCUNit.c */

/* Unit Initialization Function, defined in mMCUNit.c
	called by User to initialize CIP Machine
		returning 1 if successful
		returning 0 if failed */

int fINIT_(void);

/* User defined Initialization Function for CIP Shell Interface Initialization 
	called by Unit Initialization Function */

void iCHAN_(void);


#endif 

/*********************************************************************
	End of CIP UNIT Header File for CIP SHELL sMCUNit
*********************************************************************/
