
/*********************************************************************
	SYSTEM MonsterCatcher
	IMPLEMENTATION MCArduino
	Module for CIP SHELL sMCUNit
	Filename: sMCUNit.c
	generated by CIP Tool(R) Version 4.41.00
		August 23, 2012  9:16:05 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "sMCUNit.h"

/* Input Interface */

struct tIN_ IN_;

/* Output Interface */

struct tOUT_ OUT_;

/* Trigger Interface  */

struct tTRG_ TRG_;

/*********************************************************************
	End of Module for CIP SHELL sMCUNit
*********************************************************************/
