
/*********************************************************************
	SYSTEM BabyAlarm
	IMPLEMENTATION Arduino
	Error Function Template Module for CIP MACHINE mTheUnit
	Filename: _errTheUnit.tpl
	generated by CIP Tool(R) Version 4.41.00
		February 9, 2012  2:09:19 am
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/*********************************************************************
	End of Error Function Template Module for CIP MACHINE mTheUnit
*********************************************************************/
