
/*********************************************************************
	SYSTEM BabyAlarm
	IMPLEMENTATION Arduino
	Trace Template File for CIP MACHINE mTheUnit
	Filename: _traceTheUnit.tpl
	generated by CIP Tool(R) Version 4.41.00
		February 9, 2012  3:36:09 am
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/*********************************************************************
	End of Trace Template File for CIP MACHINE mTheUnit
*********************************************************************/
