
/*********************************************************************
	SYSTEM BabyAlarm
	IMPLEMENTATION Arduino
	Error Header File for CIP MACHINE mTheUnit
	Filename: eTheUnit.h
	generated by CIP Tool(R) Version 4.41.00
		February 9, 2012  3:36:10 am
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

#ifndef _EHEADER
#define _EHEADER

/* Include Files */

#include "mTheUnit.h"

#endif 

/*********************************************************************
	End of Error Header File for CIP MACHINE mTheUnit
*********************************************************************/
