
/*********************************************************************
	SYSTEM Workspace
	IMPLEMENTATION Arduino
	CIP Connector Template Module for CIP SHELL sTheUnit
	Filename: _conTheUnit.tpl
	generated by CIP Tool(R) Version 4.41.00
		February 18, 2015  2:26:11 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "sTheUnit.h"


/*********************************************************************
	User defined Output Channel Functions
*********************************************************************/

/* Output Channel Functions,
	called by CIP Machine when a Message is written.
	User defined function, with name to consider as suggestion */

/* Parameters
	name_		name value of message */

void uCHAN_AmbientDimAction (unsigned char name_)
{
	/* Accessing MESSAGE */
	switch (name_)
	{
	case C4_MINUS:
		/* user defined code */
		break;
	case C4_PLUS:
		/* user defined code */
		break;
	default: 
		break;
	}
}

void uCHAN_LightControllerActions (unsigned char name_)
{
	/* Accessing MESSAGE */
	switch (name_)
	{
	case C14_MINUS:
		/* user defined code */
		break;
	case C14_MINUS_STEP:
		/* user defined code */
		break;
	case C14_PLUS:
		/* user defined code */
		break;
	case C14_PLUS_STEP:
		/* user defined code */
		break;
	case C14_PLUS_STEP_DIRECT:
		/* user defined code */
		break;
	default: 
		break;
	}
}

void uCHAN_SoundActions (unsigned char name_)
{
	/* Accessing MESSAGE */
	switch (name_)
	{
	case C11_MINUS:
		/* user defined code */
		break;
	case C11_PLUS:
		/* user defined code */
		break;
	case C11_PLUS_STEP:
		/* user defined code */
		break;
	default: 
		break;
	}
}


/*********************************************************************
	User defined Output Channel Interface Initialization Function
*********************************************************************/

void iCHAN_(void)
{
		/* Initializing Input Error Function only if Input Error Option set */

	#ifdef _EINPUT__
		IN_.EINPUT_ = uEINPUT_;
	#endif 

		/* Initializing Output Interface */

	OUT_.AmbientDimAction = uCHAN_AmbientDimAction;
	OUT_.LightControllerActions = uCHAN_LightControllerActions;
	OUT_.SoundActions = uCHAN_SoundActions;
}


/*********************************************************************
	Execution of CIP Connector Activities
*********************************************************************/

	/* Initializing CIP Machine */

if (fINIT_())
{
	/* activation of drive loop */
}
else 
{
	/* initialization failed, abort drive */
}


/* Input Function Calls */

	/* Referenced Input Variables (examples) */

unsigned char name_AmbientDimReply;
unsigned char name_LightControllerEvents;
unsigned char name_LightDimMinusEvents;
unsigned char name_LightDimPlusEvents;
unsigned char name_LightSwitchEvent;
unsigned char name_SoundControlEvents;
unsigned char name_SoundMinusChannel;
unsigned char name_SoundPlusChannel;
unsigned char name_SoundSwitchChannel;

	/* Calling Input Functions */

IN_.AmbientDimReply(name_AmbientDimReply);
IN_.LightControllerEvents(name_LightControllerEvents);
IN_.LightDimMinusEvents(name_LightDimMinusEvents);
IN_.LightDimPlusEvents(name_LightDimPlusEvents);
IN_.LightSwitchEvent(name_LightSwitchEvent);
IN_.SoundControlEvents(name_SoundControlEvents);
IN_.SoundMinusChannel(name_SoundMinusChannel);
IN_.SoundPlusChannel(name_SoundPlusChannel);
IN_.SoundSwitchChannel(name_SoundSwitchChannel);


/* Trigger Function Calls */

TRG_.TICK_();		/* increment CIP Machine time by one Tick */

if (TRG_.PENDING_.ANY_)
	TRG_.STEP_();		/* perform one step, if any transition (in priority order chain, timeup, local message, auto) is pending */

if (TRG_.PENDING_.CHAIN_)
	TRG_.CHAIN_();		/* perform one chain, if any chain is pending */

if (TRG_.PENDING_.TIMEUP_)
	TRG_.TIMEUP_();		/* perform one timeup, if any timeup is pending  */

if (TRG_.PENDING_.READ_)
	TRG_.READ_();		/* perform one local read, if any local message is buffered */

if (TRG_.PENDING_.AUTO_)
	TRG_.AUTO_();		/* perform one auto, if any auto is pending */

/*********************************************************************
	End of CIP Connector Template Module for CIP SHELL sTheUnit
*********************************************************************/
