
/*********************************************************************
	SYSTEM Workspace
	IMPLEMENTATION Arduino
	Error Interface Module for CIP MACHINE mTheUnit
	Filename: eTheUnit.c
	generated by CIP Tool(R) Version 4.41.00
		February 15, 2015  10:53:56 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "eTheUnit.h"

/*********************************************************************
	End of Error Interface Module for CIP MACHINE mTheUnit
*********************************************************************/
