
/*********************************************************************
	SYSTEM Workspace
	IMPLEMENTATION Arduino
	Error Header File for CIP MACHINE mTheUnit
	Filename: eTheUnit.h
	generated by CIP Tool(R) Version 4.41.00
		February 15, 2015  12:40:50 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

#ifndef _EHEADER
#define _EHEADER

/* Include Files */

#include "mTheUnit.h"

#endif 

/*********************************************************************
	End of Error Header File for CIP MACHINE mTheUnit
*********************************************************************/
