
/*********************************************************************
	SYSTEM Workspace
	Module for PROCESS LightSwitch
	Filename: LightSwitch.c
	generated by CIP Tool(R) Version 4.41.00
		February 18, 2015  2:26:12 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mTheUnit.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define SELF status_LightSwitch.write_access_
#define STATUS status_LightSwitch.read_access_
#define TIME time_mTheUnit

/* Process Definitions */

/* MODES */
#define normal 1

/* STATES */
#define Off 1
#define On 2
#define TurningOff 3
#define TurningOn 4


/* INPULSES */
#define IP_IS_ON 1
#define IP_IS_OFF 2
#define TIMEUP_ 3


/* OUTPULSES */

#define O5_OFF 8
#define O5_ON 7
#define O8_IS_OFF 17
#define O8_IS_ON 18
#define O8_TURN_OFF 16
#define O8_TURN_OFF_STEP 14
#define O8_TURN_ON 15
#define O8_TURN_ON_STEP 13
#define O9_PRESS 20
#define O6_PRESS 9
#define O2_OFF 4
#define O2_ON 3

/* External Declarations */

extern unsigned long time_mTheUnit;
extern struct tTMQE_mTheUnit *tuhead_mTheUnit, *tutail_mTheUnit;
extern union tCHNOUT_mTheUnit CHNOUT_mTheUnit;
extern struct tTIMING_mTheUnit TIMING_mTheUnit[4];

void fUPDATE_Lights (void);
int fPULSE_LightController (unsigned char name_);
void fSETTIM_mTheUnit (unsigned long *delay_, struct tTMEL_mTheUnit *timer_, struct tTMQE_mTheUnit *timeup_);
void fSTOPTIM_mTheUnit (struct tTMEL_mTheUnit *timer_, struct tTMQE_mTheUnit *timeup_);

/* Global Declarations */

static unsigned long delay_;
struct tPRINST_LightSwitch IO_LightSwitch;
union tSTATUS_LightSwitch status_LightSwitch;

/* Function Prototypes */

void fICHAN_LightSwitchEvent (unsigned char name_);
int fPULSE_LightSwitch (unsigned char name_);
void fINIT_LightSwitch (void);

/* Input Channel Functions */

void fICHAN_LightSwitchEvent (unsigned char name_)
{
	switch (name_)
	{
		/***  MESSAGE TOGGLE of INPORT LightSwitchIn  ***/
	case C2_TOGGLE:
		switch (status_LightSwitch.read_access_.STATE)
		{
		case 1:  /* STATE Off */
			status_LightSwitch.write_access_.STATE = 4;  /* STATE TurningOn */
			fPULSE_LightController (O2_ON);
			break;
		case 2:  /* STATE On */
			status_LightSwitch.write_access_.STATE = 3;  /* STATE TurningOff */
			fPULSE_LightController (O2_OFF);
			break;
		default: 
			return;
		}
		break;
	default: 
		return;
	}
	fUPDATE_Lights ();
	return;
}

#undef EXCEPTION

int fPULSE_LightSwitch (unsigned char name_)
{
	switch (name_)
	{
		/***  INPULSE IS_OFF  ***/
	case O8_IS_OFF:		/***  PULSE CAST from PROCESS LightController  ***/
		switch (status_LightSwitch.read_access_.STATE)
		{
		case 2:  /* STATE On */
			status_LightSwitch.write_access_.STATE = 1;  /* STATE Off */
			break;
		case 3:  /* STATE TurningOff */
			status_LightSwitch.write_access_.STATE = 1;  /* STATE Off */
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE IS_ON  ***/
	case O8_IS_ON:		/***  PULSE CAST from PROCESS LightController  ***/
		switch (status_LightSwitch.read_access_.STATE)
		{
		case 1:  /* STATE Off */
			status_LightSwitch.write_access_.STATE = 2;  /* STATE On */
			break;
		case 4:  /* STATE TurningOn */
			status_LightSwitch.write_access_.STATE = 2;  /* STATE On */
			break;
		default: 
			break;
		}
		break;
	default: 
		return 0;
	}
	return 1;
}

/* Timer Functions */

static void fTICK_LightSwitch (void)
{
	if (IO_LightSwitch.timer_.set_ && 
		IO_LightSwitch.timer_.end_ == time_mTheUnit)
	{
		IO_LightSwitch.timer_.set_ = FALSE;
		--TIMING_mTheUnit[2].set_;
		if (tuhead_mTheUnit != &IO_LightSwitch.timeup_ && 
			!IO_LightSwitch.timeup_.preced_ && 
			!IO_LightSwitch.timeup_.next_)
		{
			if (! tuhead_mTheUnit)
				tuhead_mTheUnit = tutail_mTheUnit = &IO_LightSwitch.timeup_;
			else 
			{
				tutail_mTheUnit->next_ = &IO_LightSwitch.timeup_;
				IO_LightSwitch.timeup_.preced_ = tutail_mTheUnit;
				tutail_mTheUnit = &IO_LightSwitch.timeup_;
			}
		}
	}
}

static void fTUHNDL_LightSwitch (void)
{
	struct tTMQE_mTheUnit *element_ = tuhead_mTheUnit;
	if (tuhead_mTheUnit == tutail_mTheUnit)
		tuhead_mTheUnit = tutail_mTheUnit = 0;
	else 
	{
		tuhead_mTheUnit = element_->next_;
		element_->next_ = 0;
		tuhead_mTheUnit->preced_ = 0;
	}
	fUPDATE_Lights ();
}

/* Process Initialization Function */

void fINIT_LightSwitch (void)
{
	status_LightSwitch.write_access_.STATE = 1;  /* STATE Off */
	IO_LightSwitch.timer_.set_ = FALSE;
	IO_LightSwitch.timeup_.preced_ = 0;
	IO_LightSwitch.timeup_.next_ = 0;
	IO_LightSwitch.timeup_.proctype_ = 2;
	TIMING_mTheUnit[2].tkhndl_ = fTICK_LightSwitch;
	TIMING_mTheUnit[2].tuhndl_ = fTUHNDL_LightSwitch;
}

/*********************************************************************
	End of Module for PROCESS LightSwitch
*********************************************************************/
