
/*********************************************************************
	SYSTEM Workspace
	Module for PROCESS Light
	Filename: Light.c
	generated by CIP Tool(R) Version 4.41.00
		February 14, 2015  2:08:51 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mTheUnit.h"

/* Process Macro Definitions */

#define SELF status_Light.write_access_
#define STATUS status_Light.read_access_
#define TIME time_mTheUnit

/* Process Definitions */

/* MODES */
#define normal 1

/* STATES */
#define Off 1
#define On 2


/* INPULSES */
#define IP_ON 1
#define IP_OFF 2


/* OUTPULSES */

#define O3_OFF 2
#define O3_ON 1
#define O1_IS_OFF 6
#define O1_IS_ON 5
#define O2_OFF 4
#define O2_ON 3

/* External Declarations */

extern unsigned long time_mTheUnit;
extern union tCHNOUT_mTheUnit CHNOUT_mTheUnit;

void fUPDATE_Controller (void);
int fPULSE_LightDimmer (unsigned char name_);

/* Global Declarations */

union tSTATUS_Light status_Light;

/* Function Prototypes */

int fPULSE_Light (unsigned char name_);
void fINIT_Light (void);

/* Input Channel Functions */

int fPULSE_Light (unsigned char name_)
{
	switch (name_)
	{
		/***  INPULSE OFF  ***/
	case O2_OFF:		/***  PULSE CAST from PROCESS LightSwitch  ***/
		switch (status_Light.read_access_.STATE)
		{
		case 2:  /* STATE On */
			status_Light.write_access_.STATE = 1;  /* STATE Off */
			fPULSE_LightDimmer (O3_OFF);
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE ON  ***/
	case O2_ON:		/***  PULSE CAST from PROCESS LightSwitch  ***/
		switch (status_Light.read_access_.STATE)
		{
		case 1:  /* STATE Off */
			status_Light.write_access_.STATE = 2;  /* STATE On */
			fPULSE_LightDimmer (O3_ON);
			break;
		default: 
			break;
		}
		break;
	default: 
		return 0;
	}
	return 1;
}

/* Process Initialization Function */

void fINIT_Light (void)
{
	status_Light.write_access_.STATE = 1;  /* STATE Off */
}

/*********************************************************************
	End of Module for PROCESS Light
*********************************************************************/
