
/*********************************************************************
	SYSTEM Workspace
	Module for PROCESS LightDimmer
	Filename: LightDimmer.c
	generated by CIP Tool(R) Version 4.41.00
		February 15, 2015  8:35:01 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mTheUnit.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define SELF status_LightDimmer.write_access_
#define STATUS status_LightDimmer.read_access_
#define TIME time_mTheUnit

/* Process Definitions */

/* MODES */
#define automatic 1
#define manual 2

/* STATES */
#define Fade_In 1
#define Fade_Out 2
#define Off 3
#define On 4


/* INPULSES */
#define IP_FADE_IN 1
#define IP_FADE_OUT 2
#define TIMEUP_ 3
#define IP_FADE_OUT_STEP 5
#define IP_FADE_IN_STEP 6


/* OUTPULSES */

#define O5_OFF 8
#define O5_ON 7
#define O3_OFF 2
#define O3_ON 1
#define O8_IS_OFF 17
#define O8_IS_ON 18
#define O8_TURN_OFF 16
#define O8_TURN_OFF_STEP 14
#define O8_TURN_ON 15
#define O8_TURN_ON_STEP 13
#define O1_IS_OFF 6
#define O1_IS_ON 5
#define O9_PRESS 20
#define O6_PRESS 9
#define O2_OFF 4
#define O2_ON 3

/* External Declarations */

extern unsigned long time_mTheUnit;
extern struct tTMQE_mTheUnit *tuhead_mTheUnit, *tutail_mTheUnit;
extern union tCHNOUT_mTheUnit CHNOUT_mTheUnit;
extern struct tTIMING_mTheUnit TIMING_mTheUnit[2];
extern union tSTATUS_LightMinusButton status_LightMinusButton;
extern union tSTATUS_LightPlusButton status_LightPlusButton;
extern union tSTATUS_LightSwitch status_LightSwitch;

void fUPDATE_Controller (void);
int fPULSE_LightController (unsigned char name_);
void fSETTIM_mTheUnit (unsigned long *delay_, struct tTMEL_mTheUnit *timer_, struct tTMQE_mTheUnit *timeup_);
void fSTOPTIM_mTheUnit (struct tTMEL_mTheUnit *timer_, struct tTMQE_mTheUnit *timeup_);

/* Global Declarations */

static unsigned long delay_;
struct tPRINST_LightDimmer IO_LightDimmer;
union tSTATUS_LightDimmer status_LightDimmer;
const unsigned char MODTAB_LightDimmer[2][2][4] =       /*  [LightMinusButton states] [LightPlusButton states] [LightSwitch states] */
	{{{1, 1, 1, 1}, 
	{2, 2, 2, 2}}, 
	{{2, 2, 2, 2}, 
	{2, 2, 2, 2}}};

/* Function Prototypes */

void fICHAN_LightSwitchDimReply (unsigned char name_);
int fPULSE_LightDimmer (unsigned char name_);
void fINIT_LightDimmer (void);

/* Input Channel Functions */

void fICHAN_LightSwitchDimReply (unsigned char name_)
{
	switch (name_)
	{
		/***  MESSAGE IS_OFF of INPORT LightDimmerEvent  ***/
	case C3_IS_OFF:
		switch (MODTAB_LightDimmer[status_LightMinusButton.read_access_.STATE -1][status_LightPlusButton.read_access_.STATE -1][status_LightSwitch.read_access_.STATE -1])
		{
		case 1:  /* MODE automatic */
			switch (status_LightDimmer.read_access_.STATE)
			{
			case 2:  /* STATE Fade_Out */
				status_LightDimmer.write_access_.STATE = 3;  /* STATE Off */
				fSTOPTIM_mTheUnit (&IO_LightDimmer.timer_, 
					&IO_LightDimmer.timeup_);
				fPULSE_LightController (O1_IS_OFF);
				break;
			default: 
				return;
			}
			break;
		case 2:  /* MODE manual */
			switch (status_LightDimmer.read_access_.STATE)
			{
			case 4:  /* STATE On */
				status_LightDimmer.write_access_.STATE = 3;  /* STATE Off */
				fPULSE_LightController (O1_IS_OFF);
				break;
			default: 
				return;
			}
			break;
		default: 
			return;
		}
		break;
		/***  MESSAGE IS_ON of INPORT LightDimmerEvent  ***/
	case C3_IS_ON:
		switch (MODTAB_LightDimmer[status_LightMinusButton.read_access_.STATE -1][status_LightPlusButton.read_access_.STATE -1][status_LightSwitch.read_access_.STATE -1])
		{
		case 1:  /* MODE automatic */
			switch (status_LightDimmer.read_access_.STATE)
			{
			case 1:  /* STATE Fade_In */
				status_LightDimmer.write_access_.STATE = 4;  /* STATE On */
				fSTOPTIM_mTheUnit (&IO_LightDimmer.timer_, 
					&IO_LightDimmer.timeup_);
				fPULSE_LightController (O1_IS_ON);
				break;
			case 2:  /* STATE Fade_Out */
				status_LightDimmer.write_access_.STATE = 4;  /* STATE On */
				fSTOPTIM_mTheUnit (&IO_LightDimmer.timer_, 
					&IO_LightDimmer.timeup_);
				fPULSE_LightController (O1_IS_ON);
				break;
			default: 
				return;
			}
			break;
		default: 
			return;
		}
		break;
	default: 
		return;
	}
	fUPDATE_Controller ();
	return;
}

#undef EXCEPTION

int fPULSE_LightDimmer (unsigned char name_)
{
	switch (name_)
	{
		/***  INPULSE FADE_IN  ***/
	case O8_TURN_ON:		/***  PULSE CAST from PROCESS LightController  ***/
		switch (MODTAB_LightDimmer[status_LightMinusButton.read_access_.STATE -1][status_LightPlusButton.read_access_.STATE -1][status_LightSwitch.read_access_.STATE -1])
		{
		case 1:  /* MODE automatic */
			switch (status_LightDimmer.read_access_.STATE)
			{
			case 3:  /* STATE Off */
				{
					delay_ =  3;	/***  DELAY LIGHT_FADE_IN_DELAY  ***/
					status_LightDimmer.write_access_.STATE = 1;  /* STATE Fade_In */
					CHNOUT_mTheUnit.CHAN_LightSwitchAction.name_ = C1_PLUS;
					OUT_.LightSwitchAction (CHNOUT_mTheUnit.CHAN_LightSwitchAction.name_);
					fSETTIM_mTheUnit (&delay_, 
						&IO_LightDimmer.timer_, 
						&IO_LightDimmer.timeup_);
				}
				break;
			default: 
				break;
			}
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE FADE_IN_STEP  ***/
	case O8_TURN_ON_STEP:		/***  PULSE CAST from PROCESS LightController  ***/
		switch (MODTAB_LightDimmer[status_LightMinusButton.read_access_.STATE -1][status_LightPlusButton.read_access_.STATE -1][status_LightSwitch.read_access_.STATE -1])
		{
		case 2:  /* MODE manual */
			switch (status_LightDimmer.read_access_.STATE)
			{
			case 1:  /* STATE Fade_In */
				status_LightDimmer.write_access_.STATE = 4;  /* STATE On */
				CHNOUT_mTheUnit.CHAN_LightSwitchAction.name_ = C1_PLUS;
				OUT_.LightSwitchAction (CHNOUT_mTheUnit.CHAN_LightSwitchAction.name_);
				break;
			case 3:  /* STATE Off */
				status_LightDimmer.write_access_.STATE = 4;  /* STATE On */
				CHNOUT_mTheUnit.CHAN_LightSwitchAction.name_ = C1_PLUS_DIRECT_ON;
				OUT_.LightSwitchAction (CHNOUT_mTheUnit.CHAN_LightSwitchAction.name_);
				break;
			case 4:  /* STATE On */
				status_LightDimmer.write_access_.STATE = 4;  /* STATE On */
				CHNOUT_mTheUnit.CHAN_LightSwitchAction.name_ = C1_PLUS;
				OUT_.LightSwitchAction (CHNOUT_mTheUnit.CHAN_LightSwitchAction.name_);
				break;
			default: 
				break;
			}
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE FADE_OUT  ***/
	case O8_TURN_OFF:		/***  PULSE CAST from PROCESS LightController  ***/
		switch (MODTAB_LightDimmer[status_LightMinusButton.read_access_.STATE -1][status_LightPlusButton.read_access_.STATE -1][status_LightSwitch.read_access_.STATE -1])
		{
		case 1:  /* MODE automatic */
			switch (status_LightDimmer.read_access_.STATE)
			{
			case 4:  /* STATE On */
				{
					delay_ =  5;	/***  DELAY LIGHT_FADE_OUT_DELAY  ***/
					status_LightDimmer.write_access_.STATE = 2;  /* STATE Fade_Out */
					CHNOUT_mTheUnit.CHAN_LightSwitchAction.name_ = C1_MINUS;
					OUT_.LightSwitchAction (CHNOUT_mTheUnit.CHAN_LightSwitchAction.name_);
					fSETTIM_mTheUnit (&delay_, 
						&IO_LightDimmer.timer_, 
						&IO_LightDimmer.timeup_);
				}
				break;
			default: 
				break;
			}
			break;
		case 2:  /* MODE manual */
			switch (status_LightDimmer.read_access_.STATE)
			{
			case 2:  /* STATE Fade_Out */
				status_LightDimmer.write_access_.STATE = 4;  /* STATE On */
				CHNOUT_mTheUnit.CHAN_LightSwitchAction.name_ = C1_MINUS;
				OUT_.LightSwitchAction (CHNOUT_mTheUnit.CHAN_LightSwitchAction.name_);
				break;
			default: 
				break;
			}
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE FADE_OUT_STEP  ***/
	case O8_TURN_OFF_STEP:		/***  PULSE CAST from PROCESS LightController  ***/
		switch (MODTAB_LightDimmer[status_LightMinusButton.read_access_.STATE -1][status_LightPlusButton.read_access_.STATE -1][status_LightSwitch.read_access_.STATE -1])
		{
		case 2:  /* MODE manual */
			switch (status_LightDimmer.read_access_.STATE)
			{
			case 4:  /* STATE On */
				status_LightDimmer.write_access_.STATE = 4;  /* STATE On */
				CHNOUT_mTheUnit.CHAN_LightSwitchAction.name_ = C1_MINUS;
				OUT_.LightSwitchAction (CHNOUT_mTheUnit.CHAN_LightSwitchAction.name_);
				break;
			default: 
				break;
			}
			break;
		default: 
			break;
		}
		break;
	default: 
		return 0;
	}
	return 1;
}

/* Timer Functions */

static void fTICK_LightDimmer (void)
{
	if (IO_LightDimmer.timer_.set_ && 
		IO_LightDimmer.timer_.end_ == time_mTheUnit)
	{
		IO_LightDimmer.timer_.set_ = FALSE;
		--TIMING_mTheUnit[1].set_;
		if (tuhead_mTheUnit != &IO_LightDimmer.timeup_ && 
			!IO_LightDimmer.timeup_.preced_ && 
			!IO_LightDimmer.timeup_.next_)
		{
			if (! tuhead_mTheUnit)
				tuhead_mTheUnit = tutail_mTheUnit = &IO_LightDimmer.timeup_;
			else 
			{
				tutail_mTheUnit->next_ = &IO_LightDimmer.timeup_;
				IO_LightDimmer.timeup_.preced_ = tutail_mTheUnit;
				tutail_mTheUnit = &IO_LightDimmer.timeup_;
			}
		}
	}
}

static void fTUHNDL_LightDimmer (void)
{
	struct tTMQE_mTheUnit *element_ = tuhead_mTheUnit;
	if (tuhead_mTheUnit == tutail_mTheUnit)
		tuhead_mTheUnit = tutail_mTheUnit = 0;
	else 
	{
		tuhead_mTheUnit = element_->next_;
		element_->next_ = 0;
		tuhead_mTheUnit->preced_ = 0;
	}
	switch (MODTAB_LightDimmer[status_LightMinusButton.read_access_.STATE -1][status_LightPlusButton.read_access_.STATE -1][status_LightSwitch.read_access_.STATE -1])
	{
	case 1:  /* MODE automatic */
		switch (status_LightDimmer.read_access_.STATE)
		{
		case 1:  /* STATE Fade_In */
			{
				delay_ =  3;	/***  DELAY LIGHT_FADE_IN_DELAY  ***/
				status_LightDimmer.write_access_.STATE = 1;  /* STATE Fade_In */
				CHNOUT_mTheUnit.CHAN_LightSwitchAction.name_ = C1_PLUS;
				OUT_.LightSwitchAction (CHNOUT_mTheUnit.CHAN_LightSwitchAction.name_);
				fSETTIM_mTheUnit (&delay_, 
					&IO_LightDimmer.timer_, 
					&IO_LightDimmer.timeup_);
			}
			break;
		case 2:  /* STATE Fade_Out */
			{
				delay_ =  5;	/***  DELAY LIGHT_FADE_OUT_DELAY  ***/
				status_LightDimmer.write_access_.STATE = 2;  /* STATE Fade_Out */
				CHNOUT_mTheUnit.CHAN_LightSwitchAction.name_ = C1_MINUS;
				OUT_.LightSwitchAction (CHNOUT_mTheUnit.CHAN_LightSwitchAction.name_);
				fSETTIM_mTheUnit (&delay_, 
					&IO_LightDimmer.timer_, 
					&IO_LightDimmer.timeup_);
			}
			break;
		default: 
			break;
		}
		break;
	default: 
		break;
	}
	fUPDATE_Controller ();
}

/* Process Initialization Function */

void fINIT_LightDimmer (void)
{
	status_LightDimmer.write_access_.STATE = 3;  /* STATE Off */
	IO_LightDimmer.timer_.set_ = FALSE;
	IO_LightDimmer.timeup_.preced_ = 0;
	IO_LightDimmer.timeup_.next_ = 0;
	IO_LightDimmer.timeup_.proctype_ = 1;
	TIMING_mTheUnit[1].tkhndl_ = fTICK_LightDimmer;
	TIMING_mTheUnit[1].tuhndl_ = fTUHNDL_LightDimmer;
}

/*********************************************************************
	End of Module for PROCESS LightDimmer
*********************************************************************/
