
/*********************************************************************
	SYSTEM Workspace
	IMPLEMENTATION Arduino
	Module for CIP MACHINE mTheUnit
	Filename: mTheUnit.c
	generated by CIP Tool(R) Version 4.41.00
		February 14, 2015  2:08:51 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mTheUnit.h"

/* External Declarations */

void fICHAN_LightSwitchDimReply (unsigned char name_);
void fICHAN_LightSwitchEvent (unsigned char name_);
void fINIT_Light (void);
void fINIT_LightDimmer (void);
void fINIT_LightSwitch (void);

/* Global Declarations */

unsigned long time_mTheUnit = 0;
union tCHNOUT_mTheUnit CHNOUT_mTheUnit;
struct tTIMING_mTheUnit TIMING_mTheUnit;
struct tTMQE_mTheUnit *tuhead_mTheUnit, *tutail_mTheUnit;

/* Function Prototypes */

void fSETTIM_mTheUnit (unsigned long *delay_, struct tTMEL_mTheUnit *timer_, struct tTMQE_mTheUnit *timeup_);
void fSTOPTIM_mTheUnit (struct tTMEL_mTheUnit *timer_, struct tTMQE_mTheUnit *timeup_);
void fSTEP_mTheUnit(void);
void fCHAIN_mTheUnit(void);
void fTIMEUP_mTheUnit(void);
void fREAD_mTheUnit(void);
void fUPDATE_Controller (void);

/* AUTO_ Handler Function */

static void fAUTOHDL_mTheUnit(void)
{
		/* dummy function handling no AUTO_ */
}

/* Timer Functions */

static void fTICK_mTheUnit(void)
{
	time_mTheUnit ++;
	if (TIMING_mTheUnit.set_)
		TIMING_mTheUnit.tkhndl_ ();
	TRG_.PENDING_.TIMEUP_ = tuhead_mTheUnit != 0;
	TRG_.PENDING_.ANY_ = TRG_.PENDING_.ANY_ || TRG_.PENDING_.TIMEUP_;
}

void fSETTIM_mTheUnit (unsigned long *delay_, struct tTMEL_mTheUnit *timer_, struct tTMQE_mTheUnit *timeup_)
{
	if (*delay_ > 0)
	{
		if (! timer_->set_)
			++TIMING_mTheUnit.set_;
		timer_->set_ = TRUE;
		timer_->end_ = time_mTheUnit + *delay_;
		if (tuhead_mTheUnit == timeup_)
			tuhead_mTheUnit = tuhead_mTheUnit->next_;
		if (timeup_->preced_)
			timeup_->preced_->next_ = timeup_->next_;
		if (timeup_->next_)
			timeup_->next_->preced_ = timeup_->preced_;
		if (tutail_mTheUnit == timeup_)
			tutail_mTheUnit = timeup_->preced_;
		timeup_->preced_ = 0;
		timeup_->next_ = 0;
	}
	else 
	{
		if (timer_->set_)
			--TIMING_mTheUnit.set_;
		timer_->set_ = FALSE;
		if (tuhead_mTheUnit != timeup_ && ! timeup_->preced_ && ! timeup_->next_)
		{
			if (! tuhead_mTheUnit)
				tuhead_mTheUnit = tutail_mTheUnit = timeup_;
			else 
			{
				tutail_mTheUnit->next_ = timeup_;
				timeup_->preced_ = tutail_mTheUnit;
				tutail_mTheUnit = timeup_;
			}
		}
	}
}

void fSTOPTIM_mTheUnit (struct tTMEL_mTheUnit *timer_, struct tTMQE_mTheUnit *timeup_)
{
	if (timer_->set_)
		--TIMING_mTheUnit.set_;
	timer_->set_ = FALSE;
	if (tuhead_mTheUnit == timeup_)
		tuhead_mTheUnit = tuhead_mTheUnit->next_;
	if (timeup_->preced_)
		timeup_->preced_->next_ = timeup_->next_;
	if (timeup_->next_)
		timeup_->next_->preced_ = timeup_->preced_;
	if (tutail_mTheUnit == timeup_)
		tutail_mTheUnit = timeup_->preced_;
	timeup_->preced_ = 0;
	timeup_->next_ = 0;
}

/* Control Functions */

	/* Step Function for CIP Machine */

void fSTEP_mTheUnit(void)
{
	if (tuhead_mTheUnit != 0)
		TIMING_mTheUnit.tuhndl_ ();
	return;
}

	/* Chain Function for CIP Machine */

void fCHAIN_mTheUnit(void)
{
	return;
}

	/* Timeup Function for CIP Machine */

void fTIMEUP_mTheUnit(void)
{
	if (tuhead_mTheUnit != 0)
		TIMING_mTheUnit.tuhndl_ ();
	return;
}

	/* Read Function for CIP Machine */

void fREAD_mTheUnit(void)
{
	return;
}

/* Update Functions */

void fUPDATE_Controller (void)
{
	TRG_.PENDING_.TIMEUP_ = tuhead_mTheUnit != 0;
	TRG_.PENDING_.ANY_ = 
		TRG_.PENDING_.TIMEUP_;
}

/* Initialization Function */

int fINIT_(void)
{
	tuhead_mTheUnit = tutail_mTheUnit = 0;
	TRG_.TICK_ = fTICK_mTheUnit;
	TRG_.CHAIN_ = fCHAIN_mTheUnit;
	TRG_.TIMEUP_ = fTIMEUP_mTheUnit;
	TRG_.STEP_ = fSTEP_mTheUnit;
	TRG_.READ_ = fREAD_mTheUnit;
	TRG_.AUTO_ = fAUTOHDL_mTheUnit;
	TRG_.PENDING_.ANY_ = 0;
	TRG_.PENDING_.CHAIN_ = 0;
	TRG_.PENDING_.TIMEUP_ = 0;
	TRG_.PENDING_.READ_ = 0;
	TRG_.PENDING_.AUTO_ = 0;
	IN_.LightSwitchDimReply = fICHAN_LightSwitchDimReply;
	IN_.LightSwitchEvent = fICHAN_LightSwitchEvent;
	iCHAN_();
	if (!OUT_.LightSwitchAction)
		return 0;
	fINIT_Light ();
	fINIT_LightDimmer ();
	fINIT_LightSwitch ();
	return 1;
}

/*********************************************************************
	End of Module for CIP MACHINE mTheUnit
*********************************************************************/
