
/*********************************************************************
	SYSTEM Workspace
	IMPLEMENTATION Arduino
	Trace Interface Module for CIP MACHINE mTheUnit
	Filename: tTheUnit.c
	generated by CIP Tool(R) Version 4.41.00
		February 17, 2015  10:23:02 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "tTheUnit.h"

/*********************************************************************
	End of Trace Interface Module for CIP MACHINE mTheUnit
*********************************************************************/
