
/*********************************************************************
	SYSTEM Instrument
	IMPLEMENTATION InstrumentImpl
	Error Interface Module for CIP MACHINE mInstrumentUnit
	Filename: eInstrumentUnit.c
	generated by CIP Tool(R) Version 4.41.00
		July 12, 2012  9:11:11 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "eInstrumentUnit.h"

/*********************************************************************
	End of Error Interface Module for CIP MACHINE mInstrumentUnit
*********************************************************************/
