
/*********************************************************************
	SYSTEM Instrument
	IMPLEMENTATION InstrumentImpl
	Trace Interface Module for CIP MACHINE mInstrumentUnit
	Filename: tInstrumentUnit.c
	generated by CIP Tool(R) Version 4.41.00
		July 12, 2012  9:11:11 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "tInstrumentUnit.h"

/*********************************************************************
	End of Trace Interface Module for CIP MACHINE mInstrumentUnit
*********************************************************************/
