
/*********************************************************************
	SYSTEM Instrument
	IMPLEMENTATION InstrumentImpl
	Trace Interface Header File for CIP MACHINE mInstrumentUnit
	Filename: tInstrumentUnit.h
	generated by CIP Tool(R) Version 4.41.00
		July 12, 2012  9:11:11 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

#ifndef _THEADER
#define _THEADER

/* Text Switch Constants */

#ifdef _TRACE__
	#undef _TRACE__
#endif 

#ifdef _UTIO__
	#undef _UTIO__
#endif 

/* Include Files */

#include <stdio.h>
#include <string.h>
#include "mInstrumentUnit.h"


#endif 

/*********************************************************************
	End of Trace Interface Header File for CIP MACHINE mInstrumentUnit
*********************************************************************/
