
/*********************************************************************
	SYSTEM CondensedWaterPump
	IMPLEMENTATION CondensedWaterPumpImpl
	Error Function Template Module for CIP MACHINE mCondensedWaterPumpUnit
	Filename: _errCondensedWaterPumpUnit.tpl
	generated by CIP Tool(R) Version 4.41.00
		December 18, 2012  8:00:09 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/*********************************************************************
	End of Error Function Template Module for CIP MACHINE mCondensedWaterPumpUnit
*********************************************************************/
