
/*********************************************************************
	SYSTEM CondensedWaterPump
	IMPLEMENTATION CondensedWaterPumpImpl
	Trace Template File for CIP MACHINE mCondensedWaterPumpUnit
	Filename: _traceCondensedWaterPumpUnit.tpl
	generated by CIP Tool(R) Version 4.41.00
		December 18, 2012  8:00:09 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/*********************************************************************
	End of Trace Template File for CIP MACHINE mCondensedWaterPumpUnit
*********************************************************************/
