
/*********************************************************************
	SYSTEM CondensedWaterPump
	IMPLEMENTATION CondensedWaterPumpImpl
	Error Interface Module for CIP MACHINE mCondensedWaterPumpUnit
	Filename: eCondensedWaterPumpUnit.c
	generated by CIP Tool(R) Version 4.41.00
		December 18, 2012  8:00:09 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "eCondensedWaterPumpUnit.h"

/*********************************************************************
	End of Error Interface Module for CIP MACHINE mCondensedWaterPumpUnit
*********************************************************************/
