
/*********************************************************************
	SYSTEM CondensedWaterPump
	IMPLEMENTATION CondensedWaterPumpImpl
	Error Header File for CIP MACHINE mCondensedWaterPumpUnit
	Filename: eCondensedWaterPumpUnit.h
	generated by CIP Tool(R) Version 4.41.00
		December 18, 2012  8:00:09 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

#ifndef _EHEADER
#define _EHEADER

/* Include Files */

#include "mCondensedWaterPumpUnit.h"

#endif 

/*********************************************************************
	End of Error Header File for CIP MACHINE mCondensedWaterPumpUnit
*********************************************************************/
