
/*********************************************************************
	SYSTEM CondensedWaterPump
	IMPLEMENTATION CondensedWaterPumpImpl
	Module for CIP MACHINE mCondensedWaterPumpUnit
	Filename: mCondensedWaterPumpUnit.c
	generated by CIP Tool(R) Version 4.41.00
		December 18, 2012  8:00:09 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mCondensedWaterPumpUnit.h"

/* External Declarations */

void fICHAN_LowerLevelSensorInChan (unsigned char name_);
void fICHAN_UpperLevelSensorInChan (unsigned char name_);
void fINIT_LowerLevelSensor (void);
void fINIT_Pump (void);
void fINIT_ThreeStepController (void);
void fINIT_UpperLevelSensor (void);

/* Global Declarations */

unsigned long time_mCondensedWaterPumpUnit = 0;
union tCHNOUT_mCondensedWaterPumpUnit CHNOUT_mCondensedWaterPumpUnit;

/* Function Prototypes */

void fSTEP_mCondensedWaterPumpUnit(void);
void fCHAIN_mCondensedWaterPumpUnit(void);
void fTIMEUP_mCondensedWaterPumpUnit(void);
void fREAD_mCondensedWaterPumpUnit(void);

/* AUTO_ Handler Function */

static void fAUTOHDL_mCondensedWaterPumpUnit(void)
{
		/* dummy function handling no AUTO_ */
}

/* Timer Functions */

static void fTICK_mCondensedWaterPumpUnit(void)
{
	time_mCondensedWaterPumpUnit ++;
}

/* Control Functions */

	/* Step Function for CIP Machine */

void fSTEP_mCondensedWaterPumpUnit(void)
{
	return;
}

	/* Chain Function for CIP Machine */

void fCHAIN_mCondensedWaterPumpUnit(void)
{
	return;
}

	/* Timeup Function for CIP Machine */

void fTIMEUP_mCondensedWaterPumpUnit(void)
{
	return;
}

	/* Read Function for CIP Machine */

void fREAD_mCondensedWaterPumpUnit(void)
{
	return;
}

/* Initialization Function */

int fINIT_(void)
{
	TRG_.TICK_ = fTICK_mCondensedWaterPumpUnit;
	TRG_.CHAIN_ = fCHAIN_mCondensedWaterPumpUnit;
	TRG_.TIMEUP_ = fTIMEUP_mCondensedWaterPumpUnit;
	TRG_.STEP_ = fSTEP_mCondensedWaterPumpUnit;
	TRG_.READ_ = fREAD_mCondensedWaterPumpUnit;
	TRG_.AUTO_ = fAUTOHDL_mCondensedWaterPumpUnit;
	IN_.LowerLevelSensorInChan = fICHAN_LowerLevelSensorInChan;
	IN_.UpperLevelSensorInChan = fICHAN_UpperLevelSensorInChan;
	iCHAN_();
	if (!OUT_.PumpOutChannel)
		return 0;
	fINIT_LowerLevelSensor ();
	fINIT_Pump ();
	fINIT_ThreeStepController ();
	fINIT_UpperLevelSensor ();
	return 1;
}

/*********************************************************************
	End of Module for CIP MACHINE mCondensedWaterPumpUnit
*********************************************************************/
