
/*********************************************************************
	SYSTEM CondensedWaterPump
	IMPLEMENTATION CondensedWaterPumpImpl
	Module for CIP SHELL sCondensedWaterPumpUnit
	Filename: sCondensedWaterPumpUnit.c
	generated by CIP Tool(R) Version 4.41.00
		December 18, 2012  8:00:08 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "sCondensedWaterPumpUnit.h"

/* Input Interface */

struct tIN_ IN_;

/* Output Interface */

struct tOUT_ OUT_;

/* Trigger Interface  */

struct tTRG_ TRG_;

/*********************************************************************
	End of Module for CIP SHELL sCondensedWaterPumpUnit
*********************************************************************/
