
/*********************************************************************
	SYSTEM CondensedWaterPump
	IMPLEMENTATION CondensedWaterPumpImpl
	Trace Interface Module for CIP MACHINE mCondensedWaterPumpUnit
	Filename: tCondensedWaterPumpUnit.c
	generated by CIP Tool(R) Version 4.41.00
		December 18, 2012  8:00:09 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "tCondensedWaterPumpUnit.h"

/*********************************************************************
	End of Trace Interface Module for CIP MACHINE mCondensedWaterPumpUnit
*********************************************************************/
