
/*********************************************************************
	SYSTEM Droid
	Module for PROCESS PrimitiveBehavior
	Filename: PrimitiveBehavior.c
	generated by CIP Tool(R) Version 4.41.00
		January 6, 2012  10:28:36 am
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mTheUnit.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define SELF status_PrimitiveBehavior.write_access_
#define STATUS status_PrimitiveBehavior.read_access_
#define TIME time_mTheUnit

/* Process Definitions */

/* MODES */
#define Toggle 1

/* STATES */
#define Off 1
#define On 2



/* External Declarations */

extern unsigned long time_mTheUnit;
extern union tCHNOUT_mTheUnit CHNOUT_mTheUnit;


/* Global Declarations */

union tSTATUS_PrimitiveBehavior status_PrimitiveBehavior;

/* Function Prototypes */

void fICHAN_Schalter (unsigned char name_);
void fINIT_PrimitiveBehavior (void);

/* Input Channel Functions */

void fICHAN_Schalter (unsigned char name_)
{
	switch (name_)
	{
		/***  MESSAGE Off of INPORT InPort  ***/
	case C1_Off:
		switch (status_PrimitiveBehavior.read_access_.STATE)
		{
		case 2:  /* STATE On */
			status_PrimitiveBehavior.write_access_.STATE = 1;  /* STATE Off */
			CHNOUT_mTheUnit.CHAN_Lampe.name_ = C2_Aus;
			OUT_.Lampe (CHNOUT_mTheUnit.CHAN_Lampe.name_);
			break;
		default: 
			return;
		}
		break;
		/***  MESSAGE On of INPORT InPort  ***/
	case C1_On:
		switch (status_PrimitiveBehavior.read_access_.STATE)
		{
		case 1:  /* STATE Off */
			status_PrimitiveBehavior.write_access_.STATE = 2;  /* STATE On */
			CHNOUT_mTheUnit.CHAN_Lampe.name_ = C2_Ein;
			OUT_.Lampe (CHNOUT_mTheUnit.CHAN_Lampe.name_);
			break;
		default: 
			return;
		}
		break;
	default: 
		return;
	}
	return;
}

#undef EXCEPTION

/* Process Initialization Function */

void fINIT_PrimitiveBehavior (void)
{
	status_PrimitiveBehavior.write_access_.STATE = 1;  /* STATE Off */
}

/*********************************************************************
	End of Module for PROCESS PrimitiveBehavior
*********************************************************************/
