
/*********************************************************************
	SYSTEM Droid
	IMPLEMENTATION Arduino
	Trace Interface Module for CIP MACHINE mTheUnit
	Filename: tTheUnit.c
	generated by CIP Tool(R) Version 4.41.00
		January 6, 2012  10:28:36 am
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "tTheUnit.h"

/*********************************************************************
	End of Trace Interface Module for CIP MACHINE mTheUnit
*********************************************************************/
