
/*********************************************************************
	SYSTEM Fhotibot2
	IMPLEMENTATION Arduino
	Error Function Template Module for CIP MACHINE mTheUnit
	Filename: _errTheUnit.tpl
	generated by CIP Tool(R) Version 4.41.00
		March 8, 2012  1:57:58 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/*********************************************************************
	End of Error Function Template Module for CIP MACHINE mTheUnit
*********************************************************************/
