
/*********************************************************************
	SYSTEM Fhotibot2
	IMPLEMENTATION Arduino
	Trace Template File for CIP MACHINE mTheUnit
	Filename: _traceTheUnit.tpl
	generated by CIP Tool(R) Version 4.41.00
		March 3, 2012  11:31:05 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/*********************************************************************
	End of Trace Template File for CIP MACHINE mTheUnit
*********************************************************************/
