
/*********************************************************************
	SYSTEM Fhotibot2
	Module for PROCESS Bump
	Filename: Bump.c
	generated by CIP Tool(R) Version 4.41.00
		March 8, 2012  1:57:58 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mTheUnit.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define SELF status_Bump.write_access_
#define STATUS status_Bump.read_access_
#define TIME time_mTheUnit

/* Process Definitions */

/* MODES */
#define Normal 1

/* STATES */
#define Hit 1
#define Released 2


/* INPULSES */
#define TIMEUP_ 1


/* OUTPULSES */

#define O5_BWD 7
#define O5_BWD_RIGHT 6
#define O3_BWD 9
#define O3_BWD_RIGHT 11
#define O3_FWD 8
#define O3_LEFT 10
#define O2_AHEAD 3
#define O2_LEFT 1
#define O2_RIGHT 2
#define O2_UNKNOWN 4

/* External Declarations */

extern unsigned long time_mTheUnit;
extern struct tTMQE_mTheUnit *tuhead_mTheUnit, *tutail_mTheUnit;
extern union tCHNOUT_mTheUnit CHNOUT_mTheUnit;
extern struct tTIMING_mTheUnit TIMING_mTheUnit;

void fUPDATE_Simple (void);
int fPULSE_Drive (unsigned char name_);
int fPULSE_ObjectAvoidance (unsigned char name_);
void fSETTIM_mTheUnit (unsigned long *delay_, struct tTMEL_mTheUnit *timer_, struct tTMQE_mTheUnit *timeup_);
void fSTOPTIM_mTheUnit (struct tTMEL_mTheUnit *timer_, struct tTMQE_mTheUnit *timeup_);

/* Global Declarations */

static unsigned long delay_;
struct tPRINST_Bump IO_Bump;
union tSTATUS_Bump status_Bump;

/* Function Prototypes */

void fICHAN_BumperInfo (unsigned char name_);
void fINIT_Bump (void);

/* Input Channel Functions */

void fICHAN_BumperInfo (unsigned char name_)
{
	switch (name_)
	{
		/***  MESSAGE HITTED of INPORT BumperInfo  ***/
	case C4_HITTED:
		switch (status_Bump.read_access_.STATE)
		{
		case 1:  /* STATE Hit */
			{
				delay_ =  3 * 10;	/***  DELAY HitDelay  ***/
				status_Bump.write_access_.STATE = 1;  /* STATE Hit */
				fSETTIM_mTheUnit (&delay_, 
					&IO_Bump.timer_, 
					&IO_Bump.timeup_);
			}
			break;
		case 2:  /* STATE Released */
			{
				delay_ =  3 * 10;	/***  DELAY HitDelay  ***/
				status_Bump.write_access_.STATE = 1;  /* STATE Hit */
				fSETTIM_mTheUnit (&delay_, 
					&IO_Bump.timer_, 
					&IO_Bump.timeup_);
				fPULSE_Drive (O5_BWD_RIGHT);
			}
			break;
		default: 
			return;
		}
		break;
	case C4_RELEASED:
		return;
	default: 
		return;
	}
	fUPDATE_Simple ();
	return;
}

#undef EXCEPTION

/* Timer Functions */

static void fTICK_Bump (void)
{
	if (IO_Bump.timer_.set_ && 
		IO_Bump.timer_.end_ == time_mTheUnit)
	{
		IO_Bump.timer_.set_ = FALSE;
		--TIMING_mTheUnit.set_;
		if (tuhead_mTheUnit != &IO_Bump.timeup_ && 
			!IO_Bump.timeup_.preced_ && 
			!IO_Bump.timeup_.next_)
		{
			if (! tuhead_mTheUnit)
				tuhead_mTheUnit = tutail_mTheUnit = &IO_Bump.timeup_;
			else 
			{
				tutail_mTheUnit->next_ = &IO_Bump.timeup_;
				IO_Bump.timeup_.preced_ = tutail_mTheUnit;
				tutail_mTheUnit = &IO_Bump.timeup_;
			}
		}
	}
}

static void fTUHNDL_Bump (void)
{
	struct tTMQE_mTheUnit *element_ = tuhead_mTheUnit;
	if (tuhead_mTheUnit == tutail_mTheUnit)
		tuhead_mTheUnit = tutail_mTheUnit = 0;
	else 
	{
		tuhead_mTheUnit = element_->next_;
		element_->next_ = 0;
		tuhead_mTheUnit->preced_ = 0;
	}
	switch (status_Bump.read_access_.STATE)
	{
	case 1:  /* STATE Hit */
		status_Bump.write_access_.STATE = 2;  /* STATE Released */
		fPULSE_Drive (O5_BWD);
		fPULSE_ObjectAvoidance (O5_BWD);
		break;
	default: 
		break;
	}
	fUPDATE_Simple ();
}

/* Process Initialization Function */

void fINIT_Bump (void)
{
	status_Bump.write_access_.STATE = 2;  /* STATE Released */
	IO_Bump.timer_.set_ = FALSE;
	IO_Bump.timeup_.preced_ = 0;
	IO_Bump.timeup_.next_ = 0;
	IO_Bump.timeup_.proctype_ = 0;
	TIMING_mTheUnit.tkhndl_ = fTICK_Bump;
	TIMING_mTheUnit.tuhndl_ = fTUHNDL_Bump;
}

/*********************************************************************
	End of Module for PROCESS Bump
*********************************************************************/
