
/*********************************************************************
	SYSTEM Fhotibot2
	IMPLEMENTATION Arduino
	Error Header File for CIP MACHINE mTheUnit
	Filename: eTheUnit.h
	generated by CIP Tool(R) Version 4.41.00
		March 3, 2012  10:30:25 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

#ifndef _EHEADER
#define _EHEADER

/* Include Files */

#include "mTheUnit.h"

#endif 

/*********************************************************************
	End of Error Header File for CIP MACHINE mTheUnit
*********************************************************************/
