
/*********************************************************************
	SYSTEM Fhotibot2
	Module for PROCESS Target
	Filename: Target.c
	generated by CIP Tool(R) Version 4.41.00
		February 20, 2012  9:08:41 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mTheUnit.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define SELF status_Target.write_access_
#define STATUS status_Target.read_access_
#define TIME time_mTheUnit

/* Process Definitions */

/* MODES */
#define Normal 1

/* STATES */
#define Ahead 1
#define Left 2
#define Right 3
#define Unknown 4



/* OUTPULSES */

#define O2_FWD 3
#define O2_LEFT 1
#define O2_RIGHT 2
#define O2_STOP 4

/* External Declarations */

extern unsigned long time_mTheUnit;
extern union tCHNOUT_mTheUnit CHNOUT_mTheUnit;

int fPULSE_Drive (unsigned char name_);

/* Global Declarations */

union tSTATUS_Target status_Target;

/* Function Prototypes */

void fICHAN_Position (unsigned char name_);
void fINIT_Target (void);

/* Input Channel Functions */

void fICHAN_Position (unsigned char name_)
{
	switch (name_)
	{
		/***  MESSAGE Ahead of INPORT Target  ***/
	case C1_Ahead:
		switch (status_Target.read_access_.STATE)
		{
		case 2:  /* STATE Left */
			status_Target.write_access_.STATE = 1;  /* STATE Ahead */
			fPULSE_Drive (O2_FWD);
			break;
		case 3:  /* STATE Right */
			status_Target.write_access_.STATE = 1;  /* STATE Ahead */
			fPULSE_Drive (O2_FWD);
			break;
		case 4:  /* STATE Unknown */
			status_Target.write_access_.STATE = 1;  /* STATE Ahead */
			fPULSE_Drive (O2_FWD);
			break;
		default: 
			return;
		}
		break;
		/***  MESSAGE Left of INPORT Target  ***/
	case C1_Left:
		switch (status_Target.read_access_.STATE)
		{
		case 1:  /* STATE Ahead */
			status_Target.write_access_.STATE = 2;  /* STATE Left */
			fPULSE_Drive (O2_LEFT);
			break;
		case 3:  /* STATE Right */
			status_Target.write_access_.STATE = 2;  /* STATE Left */
			fPULSE_Drive (O2_LEFT);
			break;
		case 4:  /* STATE Unknown */
			status_Target.write_access_.STATE = 2;  /* STATE Left */
			fPULSE_Drive (O2_LEFT);
			break;
		default: 
			return;
		}
		break;
		/***  MESSAGE Right of INPORT Target  ***/
	case C1_Right:
		switch (status_Target.read_access_.STATE)
		{
		case 1:  /* STATE Ahead */
			status_Target.write_access_.STATE = 3;  /* STATE Right */
			fPULSE_Drive (O2_RIGHT);
			break;
		case 2:  /* STATE Left */
			status_Target.write_access_.STATE = 3;  /* STATE Right */
			fPULSE_Drive (O2_RIGHT);
			break;
		case 4:  /* STATE Unknown */
			status_Target.write_access_.STATE = 3;  /* STATE Right */
			fPULSE_Drive (O2_RIGHT);
			break;
		default: 
			return;
		}
		break;
		/***  MESSAGE Unknown of INPORT Target  ***/
	case C1_Unknown:
		switch (status_Target.read_access_.STATE)
		{
		case 1:  /* STATE Ahead */
			status_Target.write_access_.STATE = 4;  /* STATE Unknown */
			fPULSE_Drive (O2_STOP);
			break;
		case 2:  /* STATE Left */
			status_Target.write_access_.STATE = 4;  /* STATE Unknown */
			fPULSE_Drive (O2_STOP);
			break;
		case 3:  /* STATE Right */
			status_Target.write_access_.STATE = 4;  /* STATE Unknown */
			fPULSE_Drive (O2_STOP);
			break;
		default: 
			return;
		}
		break;
	default: 
		return;
	}
	return;
}

#undef EXCEPTION

/* Process Initialization Function */

void fINIT_Target (void)
{
	status_Target.write_access_.STATE = 4;  /* STATE Unknown */
}

/*********************************************************************
	End of Module for PROCESS Target
*********************************************************************/
