
/*********************************************************************
	SYSTEM FrontDoor
	IMPLEMENTATION ArduinoImplementation
	Error Function Template Module for CIP MACHINE mArduinoUnit
	Filename: _errArduinoUnit.tpl
	generated by CIP Tool(R) Version 4.41.00
		November 10, 2013  9:40:45 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		'unsigned int' for delays
		C-code
*********************************************************************/

/*********************************************************************
	End of Error Function Template Module for CIP MACHINE mArduinoUnit
*********************************************************************/
