
/*********************************************************************
	SYSTEM FrontDoor
	IMPLEMENTATION ArduinoImplementation
	Error Function Template Module for CIP MACHINE mArduinoUnit
	Filename: _errArduinoUnit.tpl
	generated by CIP Tool(R) Version 4.41.00
		November 10, 2013  8:45:11 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/*********************************************************************
	End of Error Function Template Module for CIP MACHINE mArduinoUnit
*********************************************************************/
