
/*********************************************************************
	SYSTEM FrontDoor
	IMPLEMENTATION ArduinoImplementation
	Trace Template File for CIP MACHINE mArduinoUnit
	Filename: _traceArduinoUnit.tpl
	generated by CIP Tool(R) Version 4.41.00
		November 10, 2013  8:45:11 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/*********************************************************************
	End of Trace Template File for CIP MACHINE mArduinoUnit
*********************************************************************/
