
/*********************************************************************
	SYSTEM FrontDoor
	IMPLEMENTATION ArduinoImplementation
	Error Header File for CIP MACHINE mArduinoUnit
	Filename: eArduinoUnit.h
	generated by CIP Tool(R) Version 4.41.00
		November 10, 2013  9:40:45 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		'unsigned int' for delays
		C-code
*********************************************************************/

#ifndef _EHEADER
#define _EHEADER

/* Include Files */

#include "mArduinoUnit.h"

#endif 

/*********************************************************************
	End of Error Header File for CIP MACHINE mArduinoUnit
*********************************************************************/
