
/*********************************************************************
	SYSTEM FrontDoor
	IMPLEMENTATION ArduinoImplementation
	Header File for CIP MACHINE mArduinoUnit
	Filename: mArduinoUnit.h
	generated by CIP Tool(R) Version 4.41.00
		November 10, 2013  9:40:45 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		'unsigned int' for delays
		C-code
*********************************************************************/

#ifndef _MHEADER
#define _MHEADER

/* Include Files */

#include <stdlib.h>
#include "sArduinoUnit.h"

/* Macro Definitions */

#ifndef FALSE
#define FALSE 0
#endif

#ifndef TRUE
#define TRUE 1
#endif


/* Outpulse Types */

struct tOUTPLS_BellSwitch
{
	unsigned char  name_;
};

struct tOUTPLS_LightSwitch
{
	unsigned char  name_;
};

union tOUTPLS_Sonnerie
{
	struct tOUTPLS_BellSwitch OUTPLS_BellSwitch;
	struct tOUTPLS_LightSwitch OUTPLS_LightSwitch;
};

/* Global Output Type */

struct tCHAN_BellOutChannel
{
	unsigned char name_;
};

struct tCHAN_LightOutChannel
{
	unsigned char name_;
};

union tCHNOUT_mArduinoUnit
{
	struct tCHAN_BellOutChannel CHAN_BellOutChannel;
	struct tCHAN_LightOutChannel CHAN_LightOutChannel;
};

/* Timer- and Queue-Element */

struct tTMEL_mArduinoUnit
{
	unsigned char set_; /* Boolean */
	unsigned int end_;
};

struct tTMQE_mArduinoUnit
{
	struct tTMQE_mArduinoUnit *preced_;
	struct tTMQE_mArduinoUnit *next_;
	int proctype_;
};

/* Global Table Elements */

struct tTIMING_mArduinoUnit
{
	void  (*tkhndl_) (void);
	void  (*tuhndl_) (void);
	int  set_;
};

/* Types for Process Bell */

struct tPRSTAT_Bell
{
	unsigned char STATE;
};

union tSTATUS_Bell
{
	struct tPRSTAT_Bell write_access_;
	const struct tPRSTAT_Bell read_access_;
};

/* Types for Process BellSwitch */

struct tPRSTAT_BellSwitch
{
	unsigned char STATE;
};

union tSTATUS_BellSwitch
{
	struct tPRSTAT_BellSwitch write_access_;
	const struct tPRSTAT_BellSwitch read_access_;
};

struct tPRINST_BellSwitch
{
	struct tTMEL_mArduinoUnit timer_;
	struct tTMQE_mArduinoUnit timeup_;
};

/* Types for Process Light */

struct tPRSTAT_Light
{
	unsigned char STATE;
};

union tSTATUS_Light
{
	struct tPRSTAT_Light write_access_;
	const struct tPRSTAT_Light read_access_;
};

/* Types for Process LightSwitch */

struct tPRSTAT_LightSwitch
{
	unsigned char STATE;
};

union tSTATUS_LightSwitch
{
	struct tPRSTAT_LightSwitch write_access_;
	const struct tPRSTAT_LightSwitch read_access_;
};

#endif 

/*********************************************************************
	End of Header File for CIP MACHINE mArduinoUnit
*********************************************************************/
