
/*********************************************************************
	SYSTEM FrontDoor
	IMPLEMENTATION ArduinoImplementation
	Module for CIP MACHINE mArduinoUnit
	Filename: mArduinoUnit.c
	generated by CIP Tool(R) Version 4.41.00
		November 10, 2013  8:45:12 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mArduinoUnit.h"

/* External Declarations */

void fICHAN_LightSwitchInChannel (unsigned char name_);
void fINIT_Light (void);
void fINIT_LightSwitch (void);

/* Global Declarations */

unsigned long time_mArduinoUnit = 0;
union tCHNOUT_mArduinoUnit CHNOUT_mArduinoUnit;

/* Function Prototypes */

void fSTEP_mArduinoUnit(void);
void fCHAIN_mArduinoUnit(void);
void fTIMEUP_mArduinoUnit(void);
void fREAD_mArduinoUnit(void);

/* AUTO_ Handler Function */

static void fAUTOHDL_mArduinoUnit(void)
{
		/* dummy function handling no AUTO_ */
}

/* Timer Functions */

static void fTICK_mArduinoUnit(void)
{
	time_mArduinoUnit ++;
}

/* Control Functions */

	/* Step Function for CIP Machine */

void fSTEP_mArduinoUnit(void)
{
	return;
}

	/* Chain Function for CIP Machine */

void fCHAIN_mArduinoUnit(void)
{
	return;
}

	/* Timeup Function for CIP Machine */

void fTIMEUP_mArduinoUnit(void)
{
	return;
}

	/* Read Function for CIP Machine */

void fREAD_mArduinoUnit(void)
{
	return;
}

/* Initialization Function */

int fINIT_(void)
{
	TRG_.TICK_ = fTICK_mArduinoUnit;
	TRG_.CHAIN_ = fCHAIN_mArduinoUnit;
	TRG_.TIMEUP_ = fTIMEUP_mArduinoUnit;
	TRG_.STEP_ = fSTEP_mArduinoUnit;
	TRG_.READ_ = fREAD_mArduinoUnit;
	TRG_.AUTO_ = fAUTOHDL_mArduinoUnit;
	IN_.LightSwitchInChannel = fICHAN_LightSwitchInChannel;
	iCHAN_();
	if (!OUT_.LightOutChannel)
		return 0;
	fINIT_Light ();
	fINIT_LightSwitch ();
	return 1;
}

/*********************************************************************
	End of Module for CIP MACHINE mArduinoUnit
*********************************************************************/
