
/*********************************************************************
	SYSTEM FrontDoor
	IMPLEMENTATION ArduinoImplementation
	Trace Interface Header File for CIP MACHINE mArduinoUnit
	Filename: tArduinoUnit.h
	generated by CIP Tool(R) Version 4.41.00
		November 10, 2013  8:45:12 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

#ifndef _THEADER
#define _THEADER

/* Text Switch Constants */

#ifdef _TRACE__
	#undef _TRACE__
#endif 

#ifdef _UTIO__
	#undef _UTIO__
#endif 

/* Include Files */

#include <stdio.h>
#include <string.h>
#include "mArduinoUnit.h"


#endif 

/*********************************************************************
	End of Trace Interface Header File for CIP MACHINE mArduinoUnit
*********************************************************************/
