
/*********************************************************************
	SYSTEM FrontDoor
	IMPLEMENTATION ArduinoImplementation
	Trace Interface Module for CIP MACHINE mArduinoUnit
	Filename: tArduinoUnit.c
	generated by CIP Tool(R) Version 4.41.00
		November 10, 2013  8:45:12 pm
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "tArduinoUnit.h"

/*********************************************************************
	End of Trace Interface Module for CIP MACHINE mArduinoUnit
*********************************************************************/
