
/*********************************************************************
	SYSTEM Chaot
	IMPLEMENTATION ChaotImpl
	Trace Template File for CIP MACHINE mChaotUnit
	Filename: _traceChaotUnit.tpl
	generated by CIP Tool(R) Version 4.41.00
		April 9, 2012  11:44:47 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/*********************************************************************
	End of Trace Template File for CIP MACHINE mChaotUnit
*********************************************************************/
