
/*********************************************************************
	SYSTEM Chaot
	Module for PROCESS Controller
	Filename: Controller.c
	generated by CIP Tool(R) Version 4.41.00
		May 1, 2012  3:31:51 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mChaotUnit.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define SELF status_Controller.write_access_
#define STATUS status_Controller.read_access_
#define TIME time_mChaotUnit

/* Process Definitions */

/* MODES */
#define normal 1

/* STATES */
#define Drawing1 1
#define Drawing2 2
#define Ready 3


/* INPULSES */
#define IP_DRAW 1
#define TIMEUP_ 2


/* OUTPULSES */

#define O5_DONE 7
#define O3_SHAKE 1
#define O3_START 6
#define O2_INDICATING 5
#define O4_MEASURED 4
#define O1_DONE 3

/* External Declarations */

extern unsigned long time_mChaotUnit;
extern struct tTMQE_mChaotUnit *tuhead_mChaotUnit, *tutail_mChaotUnit;
extern union tCHNOUT_mChaotUnit CHNOUT_mChaotUnit;
extern struct tTIMING_mChaotUnit TIMING_mChaotUnit[2];

void fUPDATE_Robot (void);
int fPULSE_Shaker (unsigned char name_);
int fPULSE_Indicator (unsigned char name_, 
	union tOUTPLS_Robot *data_);
void fSETTIM_mChaotUnit (unsigned long *delay_, struct tTMEL_mChaotUnit *timer_, struct tTMQE_mChaotUnit *timeup_);
void fSTOPTIM_mChaotUnit (struct tTMEL_mChaotUnit *timer_, struct tTMQE_mChaotUnit *timeup_);

/* Global Declarations */

static unsigned long delay_;
struct tPRINST_Controller IO_Controller;
union tSTATUS_Controller status_Controller;

/* Function Prototypes */

void fICHAN_Start (unsigned char name_);
int fPULSE_Controller (unsigned char name_);
void fINIT_Controller (void);

/* Input Channel Functions */

void fICHAN_Start (unsigned char name_)
{
	union tOUTPLS_Robot OUTPLS_Controller = {{0}};
	switch (name_)
	{
		/***  MESSAGE START of INPORT InCommands  ***/
	case C1_START:
		switch (status_Controller.read_access_.STATE)
		{
		case 3:  /* STATE Ready */
			status_Controller.write_access_.STATE = 1;  /* STATE Drawing1 */
			fPULSE_Shaker (O3_START);
			fPULSE_Indicator (O3_START, 
				&OUTPLS_Controller);
			break;
		default: 
			return;
		}
		break;
	default: 
		return;
	}
	fUPDATE_Robot ();
	return;
}

#undef EXCEPTION

int fPULSE_Controller (unsigned char name_)
{
	switch (name_)
	{
		/***  INPULSE DRAW  ***/
	case O2_INDICATING:		/***  PULSE CAST from PROCESS Indicator  ***/
		switch (status_Controller.read_access_.STATE)
		{
		case 1:  /* STATE Drawing1 */
			status_Controller.write_access_.STATE = 2;  /* STATE Drawing2 */
			fPULSE_Shaker (O3_SHAKE);
			break;
		case 2:  /* STATE Drawing2 */
			{
				delay_ =  30;	/***  DELAY INDICATE  ***/
				status_Controller.write_access_.STATE = 3;  /* STATE Ready */
				CHNOUT_mChaotUnit.CHAN_ControllerActions.name_ = C6_DRAWED;
				OUT_.ControllerActions (CHNOUT_mChaotUnit.CHAN_ControllerActions.name_);
				fSETTIM_mChaotUnit (&delay_, 
					&IO_Controller.timer_, 
					&IO_Controller.timeup_);
				fPULSE_Shaker (O3_SHAKE);
			}
			break;
		default: 
			break;
		}
		break;
	default: 
		return 0;
	}
	return 1;
}

/* Timer Functions */

static void fTICK_Controller (void)
{
	if (IO_Controller.timer_.set_ && 
		IO_Controller.timer_.end_ == time_mChaotUnit)
	{
		IO_Controller.timer_.set_ = FALSE;
		--TIMING_mChaotUnit[0].set_;
		if (tuhead_mChaotUnit != &IO_Controller.timeup_ && 
			!IO_Controller.timeup_.preced_ && 
			!IO_Controller.timeup_.next_)
		{
			if (! tuhead_mChaotUnit)
				tuhead_mChaotUnit = tutail_mChaotUnit = &IO_Controller.timeup_;
			else 
			{
				tutail_mChaotUnit->next_ = &IO_Controller.timeup_;
				IO_Controller.timeup_.preced_ = tutail_mChaotUnit;
				tutail_mChaotUnit = &IO_Controller.timeup_;
			}
		}
	}
}

static void fTUHNDL_Controller (void)
{
	union tOUTPLS_Robot OUTPLS_Controller = {{0}};
	struct tTMQE_mChaotUnit *element_ = tuhead_mChaotUnit;
	if (tuhead_mChaotUnit == tutail_mChaotUnit)
		tuhead_mChaotUnit = tutail_mChaotUnit = 0;
	else 
	{
		tuhead_mChaotUnit = element_->next_;
		element_->next_ = 0;
		tuhead_mChaotUnit->preced_ = 0;
	}
	switch (status_Controller.read_access_.STATE)
	{
	case 3:  /* STATE Ready */
		status_Controller.write_access_.STATE = 1;  /* STATE Drawing1 */
		fPULSE_Shaker (O3_START);
		fPULSE_Indicator (O3_START, 
			&OUTPLS_Controller);
		break;
	default: 
		break;
	}
	fUPDATE_Robot ();
}

/* Process Initialization Function */

void fINIT_Controller (void)
{
	status_Controller.write_access_.STATE = 3;  /* STATE Ready */
	IO_Controller.timer_.set_ = FALSE;
	IO_Controller.timeup_.preced_ = 0;
	IO_Controller.timeup_.next_ = 0;
	IO_Controller.timeup_.proctype_ = 0;
	TIMING_mChaotUnit[0].tkhndl_ = fTICK_Controller;
	TIMING_mChaotUnit[0].tuhndl_ = fTUHNDL_Controller;
}

/*********************************************************************
	End of Module for PROCESS Controller
*********************************************************************/
