
/*********************************************************************
	SYSTEM Chaot
	IMPLEMENTATION ChaotImpl
	Error Header File for CIP MACHINE mChaotUnit
	Filename: eChaotUnit.h
	generated by CIP Tool(R) Version 4.41.00
		April 3, 2012  2:01:11 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

#ifndef _EHEADER
#define _EHEADER

/* Include Files */

#include "mChaotUnit.h"

#endif 

/*********************************************************************
	End of Error Header File for CIP MACHINE mChaotUnit
*********************************************************************/
