
/*********************************************************************
	SYSTEM Chaot
	IMPLEMENTATION ChaotImpl
	Error Interface Module for CIP MACHINE mChaotUnit
	Filename: eChaotUnit.c
	generated by CIP Tool(R) Version 4.41.00
		May 1, 2012  3:31:51 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "eChaotUnit.h"

/*********************************************************************
	End of Error Interface Module for CIP MACHINE mChaotUnit
*********************************************************************/
