
/*********************************************************************
	SYSTEM Chaot
	Module for PROCESS Indicator
	Filename: Indicator.c
	generated by CIP Tool(R) Version 4.41.00
		April 9, 2012  11:44:47 pm
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mChaotUnit.h"

/* Process Macro Definitions */

#define IN (*in_)
#define OUTMSG (*outmsg_)
#define SELF status_Indicator.write_access_
#define STATUS status_Indicator.read_access_
#define TIME time_mChaotUnit

/* Process Definitions */

/* MODES */
#define normal 1

/* STATES */
#define HighNumber 1
#define LowNumber 2
#define MiddleNumber 3
#define On 4


/* INPULSES */
#define IP_SHOW 1
#define IP_RESET 2


/* OUTPULSES */

#define O5_DONE 7
#define O3_SHAKE 1
#define O3_START 6
#define O2_INDICATING 5
#define O4_MEASURED 4
#define O1_DONE 3

/* External Declarations */

extern unsigned long time_mChaotUnit;
extern union tCHNOUT_mChaotUnit CHNOUT_mChaotUnit;

void fUPDATE_Robot (void);
int fPULSE_Controller (unsigned char name_);

/* Global Declarations */

union tSTATUS_Indicator status_Indicator;

/* Function Prototypes */

int fPULSE_Indicator (unsigned char name_, 
	union tOUTPLS_Robot *data_);
void fINIT_Indicator (void);

/* Input Channel Functions */

int fPULSE_Indicator (unsigned char name_, 
	union tOUTPLS_Robot *data_)
{
	switch (name_)
	{
		/***  INPULSE RESET  ***/
	case O3_START:		/***  PULSE CAST from PROCESS Controller  ***/
		switch (status_Indicator.read_access_.STATE)
		{
		case 1:  /* STATE HighNumber */
			status_Indicator.write_access_.STATE = 4;  /* STATE On */
			CHNOUT_mChaotUnit.CHAN_IndicatorActions.name_ = C5_RESET;
			OUT_.IndicatorActions (CHNOUT_mChaotUnit.CHAN_IndicatorActions.name_, 
				&CHNOUT_mChaotUnit.CHAN_IndicatorActions.data_);
			break;
		default: 
			break;
		}
		break;
		/***  INPULSE SHOW  ***/
	case O4_MEASURED:		/***  PULSE CAST from PROCESS Measure  ***/
		{
			struct tCIPREC_Results IN = &data_->OUTPLS_Measure.data_._Results;
			switch (status_Indicator.read_access_.STATE)
			{
			case 2:  /* STATE LowNumber */
				status_Indicator.write_access_.STATE = 3;  /* STATE MiddleNumber */
				{
					struct tCIPREC_Results OUTMSG = &CHNOUT_mChaotUnit.CHAN_IndicatorActions.data_._Results;
						/***  OUTPUT MESSAGE OPERATIONS  ***/
						/***  indicateNumber  ***/
					{
						OUTMSG.Number = IN.Number;
					}
					CHNOUT_mChaotUnit.CHAN_IndicatorActions.name_ = C5_INDICATE_MEDIUM;
					OUT_.IndicatorActions (CHNOUT_mChaotUnit.CHAN_IndicatorActions.name_, 
						&CHNOUT_mChaotUnit.CHAN_IndicatorActions.data_);
				}
				fPULSE_Controller (O2_INDICATING);
				break;
			case 3:  /* STATE MiddleNumber */
				status_Indicator.write_access_.STATE = 1;  /* STATE HighNumber */
				{
					struct tCIPREC_Results OUTMSG = &CHNOUT_mChaotUnit.CHAN_IndicatorActions.data_._Results;
						/***  OUTPUT MESSAGE OPERATIONS  ***/
						/***  indicateNumber  ***/
					{
						OUTMSG.Number = IN.Number;
					}
					CHNOUT_mChaotUnit.CHAN_IndicatorActions.name_ = C5_INDICATE_HIGH;
					OUT_.IndicatorActions (CHNOUT_mChaotUnit.CHAN_IndicatorActions.name_, 
						&CHNOUT_mChaotUnit.CHAN_IndicatorActions.data_);
				}
				fPULSE_Controller (O2_INDICATING);
				break;
			case 4:  /* STATE On */
				status_Indicator.write_access_.STATE = 2;  /* STATE LowNumber */
				{
					struct tCIPREC_Results OUTMSG = &CHNOUT_mChaotUnit.CHAN_IndicatorActions.data_._Results;
						/***  OUTPUT MESSAGE OPERATIONS  ***/
						/***  indicateNumber  ***/
					{
						OUTMSG.Number = IN.Number;
					}
					CHNOUT_mChaotUnit.CHAN_IndicatorActions.name_ = C5_INDICATE_LOW;
					OUT_.IndicatorActions (CHNOUT_mChaotUnit.CHAN_IndicatorActions.name_, 
						&CHNOUT_mChaotUnit.CHAN_IndicatorActions.data_);
				}
				fPULSE_Controller (O2_INDICATING);
				break;
			default: 
				break;
			}
		}
		break;
	default: 
		return 0;
	}
	return 1;
}

/* Process Initialization Function */

void fINIT_Indicator (void)
{
	status_Indicator.write_access_.STATE = 4;  /* STATE On */
}

/*********************************************************************
	End of Module for PROCESS Indicator
*********************************************************************/
