
/*********************************************************************
	SYSTEM Chaot
	IMPLEMENTATION ChaotImpl
	Module for CIP SHELL sChaotUnit
	Filename: sChaotUnit.c
	generated by CIP Tool(R) Version 4.41.00
		April 1, 2012  1:29:26 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "sChaotUnit.h"

/* Input Interface */

struct tIN_ IN_;

/* Output Interface */

struct tOUT_ OUT_;

/* Trigger Interface  */

struct tTRG_ TRG_;

/*********************************************************************
	End of Module for CIP SHELL sChaotUnit
*********************************************************************/
