
/*********************************************************************
	SYSTEM Chaot
	IMPLEMENTATION ChaotImpl
	Trace Interface Header File for CIP MACHINE mChaotUnit
	Filename: tChaotUnit.h
	generated by CIP Tool(R) Version 4.41.00
		April 27, 2012  2:32:31 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

#ifndef _THEADER
#define _THEADER

/* Text Switch Constants */

#ifdef _TRACE__
	#undef _TRACE__
#endif 

#ifdef _UTIO__
	#undef _UTIO__
#endif 

/* Include Files */

#include <stdio.h>
#include <string.h>
#include "mChaotUnit.h"


#endif 

/*********************************************************************
	End of Trace Interface Header File for CIP MACHINE mChaotUnit
*********************************************************************/
