
/*********************************************************************
	SYSTEM Chaot
	IMPLEMENTATION ChaotImpl
	Trace Interface Module for CIP MACHINE mChaotUnit
	Filename: tChaotUnit.c
	generated by CIP Tool(R) Version 4.41.00
		April 1, 2012  1:29:28 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "tChaotUnit.h"

/*********************************************************************
	End of Trace Interface Module for CIP MACHINE mChaotUnit
*********************************************************************/
