
/*********************************************************************
	SYSTEM Droid
	IMPLEMENTATION Arduino
	Error Interface Module for CIP MACHINE mTheUnit
	Filename: eTheUnit.c
	generated by CIP Tool(R) Version 4.41.00
		January 6, 2012  10:28:36 am
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "eTheUnit.h"

/*********************************************************************
	End of Error Interface Module for CIP MACHINE mTheUnit
*********************************************************************/
