
/*********************************************************************
	SYSTEM Droid
	IMPLEMENTATION Arduino
	Module for CIP SHELL sTheUnit
	Filename: sTheUnit.c
	generated by CIP Tool(R) Version 4.41.00
		January 6, 2012  10:28:35 am
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "sTheUnit.h"

/* Input Interface */

struct tIN_ IN_;

/* Output Interface */

struct tOUT_ OUT_;

/* Trigger Interface  */

struct tTRG_ TRG_;

/*********************************************************************
	End of Module for CIP SHELL sTheUnit
*********************************************************************/
