
/*********************************************************************
	SYSTEM IlluminatedTigerCabinet
	IMPLEMENTATION IlluminatedTigerCabImp
	Error Function Template Module for CIP MACHINE mTheUnit
	Filename: _errTheUnit.tpl
	generated by CIP Tool(R) Version 4.41.00
		December 26, 2012  12:42:40 am
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/*********************************************************************
	End of Error Function Template Module for CIP MACHINE mTheUnit
*********************************************************************/
