
/*********************************************************************
	SYSTEM IlluminatedTigerCabinet
	IMPLEMENTATION IlluminatedTigerCabImp
	Trace Template File for CIP MACHINE mTheUnit
	Filename: _traceTheUnit.tpl
	generated by CIP Tool(R) Version 4.41.00
		December 26, 2012  12:42:40 am
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/*********************************************************************
	End of Trace Template File for CIP MACHINE mTheUnit
*********************************************************************/
