
/*********************************************************************
	SYSTEM IlluminatedTigerCabinet
	Module for PROCESS CommandReceiver
	Filename: CommandReceiver.c
	generated by CIP Tool(R) Version 4.41.00
		December 26, 2012  12:42:40 am
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mTheUnit.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define SELF status_CommandReceiver.write_access_
#define STATUS status_CommandReceiver.read_access_
#define TIME time_mTheUnit

/* Process Definitions */

/* MODES */
#define normal 1

/* STATES */
#define idle 1



/* OUTPULSES */

#define O2_UPPER_CENTER_OFF 2
#define O2_UPPER_CENTER_ON 1

/* External Declarations */

extern unsigned long time_mTheUnit;
extern union tCHNOUT_mTheUnit CHNOUT_mTheUnit;

int fPULSE_UpperCenterLight (unsigned char name_);

/* Global Declarations */

union tSTATUS_CommandReceiver status_CommandReceiver;

/* Function Prototypes */

void fICHAN_CommandChannel (unsigned char name_);
void fINIT_CommandReceiver (void);

/* Input Channel Functions */

void fICHAN_CommandChannel (unsigned char name_)
{
	switch (name_)
	{
		/***  MESSAGE UPPER_CENTER_OFF of INPORT CommandReceiverIn  ***/
	case C1_UPPER_CENTER_OFF:
		switch (status_CommandReceiver.read_access_.STATE)
		{
		case 1:  /* STATE idle */
			status_CommandReceiver.write_access_.STATE = 1;  /* STATE idle */
			fPULSE_UpperCenterLight (O2_UPPER_CENTER_OFF);
			break;
		default: 
			return;
		}
		break;
		/***  MESSAGE UPPER_CENTER_ON of INPORT CommandReceiverIn  ***/
	case C1_UPPER_CENTER_ON:
		switch (status_CommandReceiver.read_access_.STATE)
		{
		case 1:  /* STATE idle */
			status_CommandReceiver.write_access_.STATE = 1;  /* STATE idle */
			fPULSE_UpperCenterLight (O2_UPPER_CENTER_ON);
			break;
		default: 
			return;
		}
		break;
	default: 
		return;
	}
	return;
}

#undef EXCEPTION

/* Process Initialization Function */

void fINIT_CommandReceiver (void)
{
	status_CommandReceiver.write_access_.STATE = 1;  /* STATE idle */
}

/*********************************************************************
	End of Module for PROCESS CommandReceiver
*********************************************************************/
