
/*********************************************************************
	SYSTEM IlluminatedTigerCabinet
	IMPLEMENTATION IlluminatedTigerCabImp
	Error Interface Module for CIP MACHINE mTheUnit
	Filename: eTheUnit.c
	generated by CIP Tool(R) Version 4.41.00
		December 26, 2012  12:42:40 am
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "eTheUnit.h"

/*********************************************************************
	End of Error Interface Module for CIP MACHINE mTheUnit
*********************************************************************/
