
/*********************************************************************
	SYSTEM IlluminatedTigerCabinet
	IMPLEMENTATION IlluminatedTigerCabImp
	Trace Interface Module for CIP MACHINE mTheUnit
	Filename: tTheUnit.c
	generated by CIP Tool(R) Version 4.41.00
		December 26, 2012  12:42:40 am
	activated code options:
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "tTheUnit.h"

/*********************************************************************
	End of Trace Interface Module for CIP MACHINE mTheUnit
*********************************************************************/
