
/*********************************************************************
	SYSTEM Starbot
	Module for PROCESS Attrack
	Filename: Attrack.c
	generated by CIP Tool(R) Version 4.41.00
		June 12, 2012  12:31:41 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mStarbotUnit.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define SELF status_Attrack.write_access_
#define STATUS status_Attrack.read_access_
#define TIME time_mStarbotUnit

/* Process Definitions */

/* MODES */
#define normal 1

/* STATES */
#define Detect 1
#define Idle 2


/* INPULSES */
#define TIMEUP_ 1
#define IP_DetectPlayer 2


/* OUTPULSES */

#define O4_ATTRACTED_PLAYER 3
#define O1_ATTRACKING_PLAYER 2
#define O1_RUNNING 1

/* External Declarations */

extern unsigned long time_mStarbotUnit;
extern struct tTMQE_mStarbotUnit *tuhead_mStarbotUnit, *tutail_mStarbotUnit;
extern union tCHNOUT_mStarbotUnit CHNOUT_mStarbotUnit;
extern struct tTIMING_mStarbotUnit TIMING_mStarbotUnit[3];

void fUPDATE_Behavior (void);
int fPULSE_Start (unsigned char name_);
void fSETTIM_mStarbotUnit (unsigned long *delay_, struct tTMEL_mStarbotUnit *timer_, struct tTMQE_mStarbotUnit *timeup_);
void fSTOPTIM_mStarbotUnit (struct tTMEL_mStarbotUnit *timer_, struct tTMQE_mStarbotUnit *timeup_);

/* Global Declarations */

static unsigned long delay_;
struct tPRINST_Attrack IO_Attrack;
union tSTATUS_Attrack status_Attrack;

/* Function Prototypes */

void fICHAN_DetectionChannel (unsigned char name_);
int fPULSE_Attrack (unsigned char name_);
void fINIT_Attrack (void);

/* Input Channel Functions */

void fICHAN_DetectionChannel (unsigned char name_)
{
	switch (name_)
	{
		/***  MESSAGE DETECTED_PLAYER of INPORT AttrackEvent  ***/
	case C5_DETECTED_PLAYER:
		switch (status_Attrack.read_access_.STATE)
		{
		case 1:  /* STATE Detect */
			status_Attrack.write_access_.STATE = 2;  /* STATE Idle */
			fSTOPTIM_mStarbotUnit (&IO_Attrack.timer_, 
				&IO_Attrack.timeup_);
			fPULSE_Start (O4_ATTRACTED_PLAYER);
			break;
		default: 
			return;
		}
		break;
	default: 
		return;
	}
	fUPDATE_Behavior ();
	return;
}

#undef EXCEPTION

int fPULSE_Attrack (unsigned char name_)
{
	switch (name_)
	{
		/***  INPULSE DetectPlayer  ***/
	case O1_ATTRACKING_PLAYER:		/***  PULSE CAST from PROCESS Start  ***/
		switch (status_Attrack.read_access_.STATE)
		{
		case 2:  /* STATE Idle */
			{
				delay_ =  20;	/***  DELAY AttractionTime  ***/
				status_Attrack.write_access_.STATE = 1;  /* STATE Detect */
				fSETTIM_mStarbotUnit (&delay_, 
					&IO_Attrack.timer_, 
					&IO_Attrack.timeup_);
			}
			break;
		default: 
			break;
		}
		break;
	default: 
		return 0;
	}
	return 1;
}

/* Timer Functions */

static void fTICK_Attrack (void)
{
	if (IO_Attrack.timer_.set_ && 
		IO_Attrack.timer_.end_ == time_mStarbotUnit)
	{
		IO_Attrack.timer_.set_ = FALSE;
		--TIMING_mStarbotUnit[0].set_;
		if (tuhead_mStarbotUnit != &IO_Attrack.timeup_ && 
			!IO_Attrack.timeup_.preced_ && 
			!IO_Attrack.timeup_.next_)
		{
			if (! tuhead_mStarbotUnit)
				tuhead_mStarbotUnit = tutail_mStarbotUnit = &IO_Attrack.timeup_;
			else 
			{
				tutail_mStarbotUnit->next_ = &IO_Attrack.timeup_;
				IO_Attrack.timeup_.preced_ = tutail_mStarbotUnit;
				tutail_mStarbotUnit = &IO_Attrack.timeup_;
			}
		}
	}
}

static void fTUHNDL_Attrack (void)
{
	struct tTMQE_mStarbotUnit *element_ = tuhead_mStarbotUnit;
	if (tuhead_mStarbotUnit == tutail_mStarbotUnit)
		tuhead_mStarbotUnit = tutail_mStarbotUnit = 0;
	else 
	{
		tuhead_mStarbotUnit = element_->next_;
		element_->next_ = 0;
		tuhead_mStarbotUnit->preced_ = 0;
	}
	switch (status_Attrack.read_access_.STATE)
	{
	case 1:  /* STATE Detect */
		{
			delay_ =  20;	/***  DELAY AttractionTime  ***/
			status_Attrack.write_access_.STATE = 1;  /* STATE Detect */
			CHNOUT_mStarbotUnit.CHAN_DetectChannel.name_ = C4_DETECT_PLAYER;
			OUT_.DetectChannel (CHNOUT_mStarbotUnit.CHAN_DetectChannel.name_);
			fSETTIM_mStarbotUnit (&delay_, 
				&IO_Attrack.timer_, 
				&IO_Attrack.timeup_);
		}
		break;
	default: 
		break;
	}
	fUPDATE_Behavior ();
}

/* Process Initialization Function */

void fINIT_Attrack (void)
{
	status_Attrack.write_access_.STATE = 2;  /* STATE Idle */
	IO_Attrack.timer_.set_ = FALSE;
	IO_Attrack.timeup_.preced_ = 0;
	IO_Attrack.timeup_.next_ = 0;
	IO_Attrack.timeup_.proctype_ = 0;
	TIMING_mStarbotUnit[0].tkhndl_ = fTICK_Attrack;
	TIMING_mStarbotUnit[0].tuhndl_ = fTUHNDL_Attrack;
}

/*********************************************************************
	End of Module for PROCESS Attrack
*********************************************************************/
