
/*********************************************************************
	SYSTEM Starbot
	IMPLEMENTATION StarbotImpl
	Error Interface Module for CIP MACHINE mStarbotUnit
	Filename: eStarbotUnit.c
	generated by CIP Tool(R) Version 4.41.00
		June 12, 2012  12:31:41 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "eStarbotUnit.h"

/*********************************************************************
	End of Error Interface Module for CIP MACHINE mStarbotUnit
*********************************************************************/
