
/*********************************************************************
	SYSTEM Starbot
	IMPLEMENTATION StarbotImpl
	Module for CIP MACHINE mStarbotUnit
	Filename: mStarbotUnit.c
	generated by CIP Tool(R) Version 4.41.00
		June 12, 2012  12:31:41 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mStarbotUnit.h"

/* External Declarations */

void fICHAN_DetectionChannel (unsigned char name_);
void fICHAN_StartChannel (unsigned char name_);
void fICHAN_TrackInChannel (unsigned char name_);
void fINIT_Attrack (void);
void fINIT_Shine (void);
void fINIT_Start (void);
void fINIT_Track (void);

/* Global Declarations */

unsigned long time_mStarbotUnit = 0;
union tCHNOUT_mStarbotUnit CHNOUT_mStarbotUnit;
struct tTIMING_mStarbotUnit TIMING_mStarbotUnit[3];
struct tTMQE_mStarbotUnit *tuhead_mStarbotUnit, *tutail_mStarbotUnit;

/* Function Prototypes */

void fSETTIM_mStarbotUnit (unsigned long *delay_, struct tTMEL_mStarbotUnit *timer_, struct tTMQE_mStarbotUnit *timeup_);
void fSTOPTIM_mStarbotUnit (struct tTMEL_mStarbotUnit *timer_, struct tTMQE_mStarbotUnit *timeup_);
void fSTEP_mStarbotUnit(void);
void fCHAIN_mStarbotUnit(void);
void fTIMEUP_mStarbotUnit(void);
void fREAD_mStarbotUnit(void);
void fUPDATE_Behavior (void);

/* AUTO_ Handler Function */

static void fAUTOHDL_mStarbotUnit(void)
{
		/* dummy function handling no AUTO_ */
}

/* Timer Functions */

static void fTICK_mStarbotUnit(void)
{
	int i_;
	time_mStarbotUnit ++;
	for (i_ = 0; i_ < 3; i_ ++)
		if (TIMING_mStarbotUnit[i_].set_)
			TIMING_mStarbotUnit[i_].tkhndl_ ();
	TRG_.PENDING_.TIMEUP_ = tuhead_mStarbotUnit != 0;
	TRG_.PENDING_.ANY_ = TRG_.PENDING_.ANY_ || TRG_.PENDING_.TIMEUP_;
}

void fSETTIM_mStarbotUnit (unsigned long *delay_, struct tTMEL_mStarbotUnit *timer_, struct tTMQE_mStarbotUnit *timeup_)
{
	if (*delay_ > 0)
	{
		if (! timer_->set_)
			++TIMING_mStarbotUnit[timeup_->proctype_].set_;
		timer_->set_ = TRUE;
		timer_->end_ = time_mStarbotUnit + *delay_;
		if (tuhead_mStarbotUnit == timeup_)
			tuhead_mStarbotUnit = tuhead_mStarbotUnit->next_;
		if (timeup_->preced_)
			timeup_->preced_->next_ = timeup_->next_;
		if (timeup_->next_)
			timeup_->next_->preced_ = timeup_->preced_;
		if (tutail_mStarbotUnit == timeup_)
			tutail_mStarbotUnit = timeup_->preced_;
		timeup_->preced_ = 0;
		timeup_->next_ = 0;
	}
	else 
	{
		if (timer_->set_)
			--TIMING_mStarbotUnit [timeup_->proctype_].set_;
		timer_->set_ = FALSE;
		if (tuhead_mStarbotUnit != timeup_ && ! timeup_->preced_ && ! timeup_->next_)
		{
			if (! tuhead_mStarbotUnit)
				tuhead_mStarbotUnit = tutail_mStarbotUnit = timeup_;
			else 
			{
				tutail_mStarbotUnit->next_ = timeup_;
				timeup_->preced_ = tutail_mStarbotUnit;
				tutail_mStarbotUnit = timeup_;
			}
		}
	}
}

void fSTOPTIM_mStarbotUnit (struct tTMEL_mStarbotUnit *timer_, struct tTMQE_mStarbotUnit *timeup_)
{
	if (timer_->set_)
		--TIMING_mStarbotUnit [timeup_->proctype_].set_;
	timer_->set_ = FALSE;
	if (tuhead_mStarbotUnit == timeup_)
		tuhead_mStarbotUnit = tuhead_mStarbotUnit->next_;
	if (timeup_->preced_)
		timeup_->preced_->next_ = timeup_->next_;
	if (timeup_->next_)
		timeup_->next_->preced_ = timeup_->preced_;
	if (tutail_mStarbotUnit == timeup_)
		tutail_mStarbotUnit = timeup_->preced_;
	timeup_->preced_ = 0;
	timeup_->next_ = 0;
}

/* Control Functions */

	/* Step Function for CIP Machine */

void fSTEP_mStarbotUnit(void)
{
	if (tuhead_mStarbotUnit != 0)
		TIMING_mStarbotUnit[tuhead_mStarbotUnit->proctype_].tuhndl_ ();
	return;
}

	/* Chain Function for CIP Machine */

void fCHAIN_mStarbotUnit(void)
{
	return;
}

	/* Timeup Function for CIP Machine */

void fTIMEUP_mStarbotUnit(void)
{
	if (tuhead_mStarbotUnit != 0)
		TIMING_mStarbotUnit [tuhead_mStarbotUnit->proctype_].tuhndl_ ();
	return;
}

	/* Read Function for CIP Machine */

void fREAD_mStarbotUnit(void)
{
	return;
}

/* Update Functions */

void fUPDATE_Behavior (void)
{
	TRG_.PENDING_.TIMEUP_ = tuhead_mStarbotUnit != 0;
	TRG_.PENDING_.ANY_ = 
		TRG_.PENDING_.TIMEUP_;
}

/* Initialization Function */

int fINIT_(void)
{
	tuhead_mStarbotUnit = tutail_mStarbotUnit = 0;
	TRG_.TICK_ = fTICK_mStarbotUnit;
	TRG_.CHAIN_ = fCHAIN_mStarbotUnit;
	TRG_.TIMEUP_ = fTIMEUP_mStarbotUnit;
	TRG_.STEP_ = fSTEP_mStarbotUnit;
	TRG_.READ_ = fREAD_mStarbotUnit;
	TRG_.AUTO_ = fAUTOHDL_mStarbotUnit;
	TRG_.PENDING_.ANY_ = 0;
	TRG_.PENDING_.CHAIN_ = 0;
	TRG_.PENDING_.TIMEUP_ = 0;
	TRG_.PENDING_.READ_ = 0;
	TRG_.PENDING_.AUTO_ = 0;
	IN_.DetectionChannel = fICHAN_DetectionChannel;
	IN_.StartChannel = fICHAN_StartChannel;
	IN_.TrackInChannel = fICHAN_TrackInChannel;
	iCHAN_();
	if (!OUT_.DetectChannel)
		return 0;
	if (!OUT_.ShineChannel)
		return 0;
	if (!OUT_.AttrackChannel)
		return 0;
	if (!OUT_.TrackOutChannel)
		return 0;
	fINIT_Attrack ();
	fINIT_Shine ();
	fINIT_Start ();
	fINIT_Track ();
	return 1;
}

/*********************************************************************
	End of Module for CIP MACHINE mStarbotUnit
*********************************************************************/
