
/*********************************************************************
	SYSTEM Starbot
	Module for PROCESS Shine
	Filename: Shine.c
	generated by CIP Tool(R) Version 4.41.00
		June 12, 2012  12:31:41 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mStarbotUnit.h"

/* Process Macro Definitions */

#define SELF status_Shine.write_access_
#define STATUS status_Shine.read_access_
#define TIME time_mStarbotUnit

/* Process Definitions */

/* MODES */
#define normal 1

/* STATES */
#define On 1
#define ShineOn 2


/* INPULSES */
#define IP_SHINING 1
#define TIMEUP_ 2


/* OUTPULSES */

#define O4_ATTRACTED_PLAYER 3
#define O1_ATTRACKING_PLAYER 2
#define O1_RUNNING 1

/* External Declarations */

extern unsigned long time_mStarbotUnit;
extern struct tTMQE_mStarbotUnit *tuhead_mStarbotUnit, *tutail_mStarbotUnit;
extern union tCHNOUT_mStarbotUnit CHNOUT_mStarbotUnit;
extern struct tTIMING_mStarbotUnit TIMING_mStarbotUnit[3];

void fUPDATE_Behavior (void);
void fSETTIM_mStarbotUnit (unsigned long *delay_, struct tTMEL_mStarbotUnit *timer_, struct tTMQE_mStarbotUnit *timeup_);
void fSTOPTIM_mStarbotUnit (struct tTMEL_mStarbotUnit *timer_, struct tTMQE_mStarbotUnit *timeup_);

/* Global Declarations */

static unsigned long delay_;
struct tPRINST_Shine IO_Shine;
union tSTATUS_Shine status_Shine;

/* Function Prototypes */

int fPULSE_Shine (unsigned char name_);
void fINIT_Shine (void);

/* Input Channel Functions */

int fPULSE_Shine (unsigned char name_)
{
	switch (name_)
	{
		/***  INPULSE SHINING  ***/
	case O1_RUNNING:		/***  PULSE CAST from PROCESS Start  ***/
		switch (status_Shine.read_access_.STATE)
		{
		case 1:  /* STATE On */
			{
				delay_ =  60;	/***  DELAY ShineTime  ***/
				status_Shine.write_access_.STATE = 2;  /* STATE ShineOn */
				CHNOUT_mStarbotUnit.CHAN_ShineChannel.name_ = C2_SHINE;
				OUT_.ShineChannel (CHNOUT_mStarbotUnit.CHAN_ShineChannel.name_);
				fSETTIM_mStarbotUnit (&delay_, 
					&IO_Shine.timer_, 
					&IO_Shine.timeup_);
			}
			break;
		default: 
			break;
		}
		break;
	default: 
		return 0;
	}
	return 1;
}

/* Timer Functions */

static void fTICK_Shine (void)
{
	if (IO_Shine.timer_.set_ && 
		IO_Shine.timer_.end_ == time_mStarbotUnit)
	{
		IO_Shine.timer_.set_ = FALSE;
		--TIMING_mStarbotUnit[1].set_;
		if (tuhead_mStarbotUnit != &IO_Shine.timeup_ && 
			!IO_Shine.timeup_.preced_ && 
			!IO_Shine.timeup_.next_)
		{
			if (! tuhead_mStarbotUnit)
				tuhead_mStarbotUnit = tutail_mStarbotUnit = &IO_Shine.timeup_;
			else 
			{
				tutail_mStarbotUnit->next_ = &IO_Shine.timeup_;
				IO_Shine.timeup_.preced_ = tutail_mStarbotUnit;
				tutail_mStarbotUnit = &IO_Shine.timeup_;
			}
		}
	}
}

static void fTUHNDL_Shine (void)
{
	struct tTMQE_mStarbotUnit *element_ = tuhead_mStarbotUnit;
	if (tuhead_mStarbotUnit == tutail_mStarbotUnit)
		tuhead_mStarbotUnit = tutail_mStarbotUnit = 0;
	else 
	{
		tuhead_mStarbotUnit = element_->next_;
		element_->next_ = 0;
		tuhead_mStarbotUnit->preced_ = 0;
	}
	switch (status_Shine.read_access_.STATE)
	{
	case 2:  /* STATE ShineOn */
		status_Shine.write_access_.STATE = 1;  /* STATE On */
		CHNOUT_mStarbotUnit.CHAN_ShineChannel.name_ = C2_END;
		OUT_.ShineChannel (CHNOUT_mStarbotUnit.CHAN_ShineChannel.name_);
		break;
	default: 
		break;
	}
	fUPDATE_Behavior ();
}

/* Process Initialization Function */

void fINIT_Shine (void)
{
	status_Shine.write_access_.STATE = 1;  /* STATE On */
	IO_Shine.timer_.set_ = FALSE;
	IO_Shine.timeup_.preced_ = 0;
	IO_Shine.timeup_.next_ = 0;
	IO_Shine.timeup_.proctype_ = 1;
	TIMING_mStarbotUnit[1].tkhndl_ = fTICK_Shine;
	TIMING_mStarbotUnit[1].tuhndl_ = fTUHNDL_Shine;
}

/*********************************************************************
	End of Module for PROCESS Shine
*********************************************************************/
