
/*********************************************************************
	SYSTEM Starbot
	IMPLEMENTATION StarbotImpl
	Header File for CIP SHELL sStarbotUnit
	Filename: sStarbotUnit.h
	generated by CIP Tool(R) Version 4.41.00
		June 12, 2012  12:31:39 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

#ifndef _SHEADER
#define _SHEADER

/* Code Option Constants */

#ifdef _EINPUT__
	#undef _EINPUT__
#endif 

/* Channel Enumerations */

#define C_AttrackChannel 3
#define C_DetectChannel 4
#define C_DetectionChannel 5
#define C_ShineChannel 2
#define C_StartChannel 1
#define C_TrackInChannel 7
#define C_TrackOutChannel 6

/* MESSAGE Enumeration of CHANNEL StartChannel */

#define C1_ 0
#define C1_END 2
#define C1_START 1

/* MESSAGE Enumeration of CHANNEL ShineChannel */

#define C2_ 0
#define C2_END 2
#define C2_SHINE 1

/* MESSAGE Enumeration of CHANNEL AttrackChannel */

#define C3_ 0
#define C3_ATTRACK 1

/* MESSAGE Enumeration of CHANNEL DetectChannel */

#define C4_ 0
#define C4_DETECT_PLAYER 1

/* MESSAGE Enumeration of CHANNEL DetectionChannel */

#define C5_ 0
#define C5_DETECTED_PLAYER 1

/* MESSAGE Enumeration of CHANNEL TrackOutChannel */

#define C6_ 0
#define C6_TRACK_CENTER 4
#define C6_TRACK_LEFT 2
#define C6_TRACK_PLAYER 1
#define C6_TRACK_RIGHT 3

/* MESSAGE Enumeration of CHANNEL TrackInChannel */

#define C7_ 0
#define C7_CENTER 1
#define C7_LEFT 2
#define C7_RIGHT 3

/* Input Interface Type */

struct tIN_
{
	void (*DetectionChannel) (unsigned char);
	void (*StartChannel) (unsigned char);
	void (*TrackInChannel) (unsigned char);
};

/* Output Interface Type */

struct tOUT_
{
	void (*AttrackChannel) (unsigned char);
	void (*DetectChannel) (unsigned char);
	void (*ShineChannel) (unsigned char);
	void (*TrackOutChannel) (unsigned char);
};

/* Trigger Interface Type */

struct tPENDING_
{
	int ANY_;	/* boolean indicating any pending transitions */
	int CHAIN_;	/* boolean indicating pending CHAIN_ */
	int TIMEUP_;	/* boolean indicating pending TIMEUP_ */
	int READ_;	/* boolean indicating buffered internal message */
	int AUTO_;	/* boolean indicating reading AUTO_ */
};

struct tTRG_
{
	void (*TICK_) (void);		/* increment CIP MACHINE time */
	void (*STEP_) (void);		/* trigger CIP MACHINE transition */
	void (*CHAIN_) (void);		/* trigger pending chain CIP MACHINE transition */
	void (*TIMEUP_) (void);		/* trigger pending timeup CIP MACHINE transition */
	void (*READ_) (void);		/* trigger CIP MACHINE to read from internal message buffer */
	void (*AUTO_) (void);		/* trigger pending auto CIP MACHINE transition */
	struct tPENDING_ PENDING_;		/* information on pending transitions */
};

/* External Interface Declarations */

extern struct tIN_ IN_;		/* Input Channel Interface defined in sStarbotUnit.c */
extern struct tOUT_ OUT_;		/* Output Channel Interface defined in sStarbotUnit.c */
extern struct tTRG_ TRG_;		/* Trigger Interface defined in sStarbotUnit.c */

/* Unit Initialization Function, defined in mStarbotUnit.c
	called by User to initialize CIP Machine
		returning 1 if successful
		returning 0 if failed */

int fINIT_(void);

/* User defined Initialization Function for CIP Shell Interface Initialization 
	called by Unit Initialization Function */

void iCHAN_(void);


#endif 

/*********************************************************************
	End of CIP UNIT Header File for CIP SHELL sStarbotUnit
*********************************************************************/
