
/*********************************************************************
	SYSTEM Starbot
	Module for PROCESS Start
	Filename: Start.c
	generated by CIP Tool(R) Version 4.41.00
		June 12, 2012  12:31:41 am
	activated code options:
		PENDING_ information
		'unsigned char' for 'enum'
		C-code
*********************************************************************/

/* Include Files */

#include "mStarbotUnit.h"

/* Process Macro Definitions */

#define EXCEPTION return;
#define SELF status_Start.write_access_
#define STATUS status_Start.read_access_
#define TIME time_mStarbotUnit

/* Process Definitions */

/* MODES */
#define normal 1

/* STATES */
#define Attracking 1
#define Running 2
#define Stop 3


/* INPULSES */
#define IP_RUN 1


/* OUTPULSES */

#define O4_ATTRACTED_PLAYER 3
#define O1_ATTRACKING_PLAYER 2
#define O1_RUNNING 1

/* External Declarations */

extern unsigned long time_mStarbotUnit;
extern union tCHNOUT_mStarbotUnit CHNOUT_mStarbotUnit;

void fUPDATE_Behavior (void);
int fPULSE_Shine (unsigned char name_);
int fPULSE_Attrack (unsigned char name_);
int fPULSE_Track (unsigned char name_);

/* Global Declarations */

union tSTATUS_Start status_Start;

/* Function Prototypes */

void fICHAN_StartChannel (unsigned char name_);
int fPULSE_Start (unsigned char name_);
void fINIT_Start (void);

/* Input Channel Functions */

void fICHAN_StartChannel (unsigned char name_)
{
	switch (name_)
	{
		/***  MESSAGE END of INPORT PlayEvent  ***/
	case C1_END:
		switch (status_Start.read_access_.STATE)
		{
		case 1:  /* STATE Attracking */
			status_Start.write_access_.STATE = 3;  /* STATE Stop */
			break;
		default: 
			return;
		}
		break;
		/***  MESSAGE START of INPORT PlayEvent  ***/
	case C1_START:
		switch (status_Start.read_access_.STATE)
		{
		case 3:  /* STATE Stop */
			status_Start.write_access_.STATE = 1;  /* STATE Attracking */
			CHNOUT_mStarbotUnit.CHAN_AttrackChannel.name_ = C3_ATTRACK;
			OUT_.AttrackChannel (CHNOUT_mStarbotUnit.CHAN_AttrackChannel.name_);
			fPULSE_Attrack (O1_ATTRACKING_PLAYER);
			break;
		default: 
			return;
		}
		break;
	default: 
		return;
	}
	fUPDATE_Behavior ();
	return;
}

#undef EXCEPTION

int fPULSE_Start (unsigned char name_)
{
	switch (name_)
	{
		/***  INPULSE RUN  ***/
	case O4_ATTRACTED_PLAYER:		/***  PULSE CAST from PROCESS Attrack  ***/
		switch (status_Start.read_access_.STATE)
		{
		case 1:  /* STATE Attracking */
			status_Start.write_access_.STATE = 2;  /* STATE Running */
			fPULSE_Shine (O1_RUNNING);
			fPULSE_Track (O1_RUNNING);
			break;
		case 2:  /* STATE Running */
			status_Start.write_access_.STATE = 1;  /* STATE Attracking */
			break;
		default: 
			break;
		}
		break;
	default: 
		return 0;
	}
	return 1;
}

/* Process Initialization Function */

void fINIT_Start (void)
{
	status_Start.write_access_.STATE = 3;  /* STATE Stop */
}

/*********************************************************************
	End of Module for PROCESS Start
*********************************************************************/
